Repository pomerium/pomerium, pull requests merged in 2019-12, with the labels that each got.

#419 errors: use %w verb directive
  authenticate/authenticate.go
  authorize/authorize.go
  config/options.go
  config/policy.go
  internal/cryptutil/certificates.go
  internal/cryptutil/encrypt.go
  internal/encoding/ecjson/ecjson.go
  internal/identity/google.go
  internal/telemetry/metrics/providers.go
  proxy/clients/clients.go
  proxy/proxy.go
Labels: improvement

#417 dependency: have renovate-bot check weekly
  renovate.json
Labels: dependency

#416 authenticate: session expiry now matches identity provider's
  authenticate/authenticate.go
  authenticate/handlers.go
  internal/sessions/state.go
  internal/sessions/state_test.go
  proxy/middleware.go
Labels: improvement

#413 httputil : wrap handlers for additional context
  authenticate/handlers.go
  authenticate/handlers_test.go
  internal/frontend/assets/html/dashboard.go.html
  internal/frontend/assets/html/error.go.html
  internal/frontend/assets/html/footer.go.html
  internal/frontend/assets/html/header.go.html
  internal/frontend/assets/img/error-24px.svg
  internal/frontend/assets/img/pomerium_circle_96.svg
  internal/frontend/assets/img/supervised_user_circle-24px.svg
  internal/frontend/assets/style/main.css
  internal/frontend/statik/statik.go
  internal/httputil/errors.go
  internal/httputil/errors_test.go
  internal/httputil/handlers.go
  internal/httputil/handlers_test.go
  internal/httputil/router.go
  internal/httputil/router_test.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
  internal/urlutil/signed.go
  internal/urlutil/url.go
  proxy/forward_auth.go
  proxy/forward_auth_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/proxy.go
Labels: improvement

#422 docs(background): improved sentence flow and other stuff
  docs/docs/background.md
Labels: docs

#429 docs: add cookie settings
  docs/configuration/readme.md
Labels: docs

#436 config: Remove CookieRefresh (#428)
  config/options.go
  config/options_test.go
Labels: improvement

#438 authenticate/proxy: add backend refresh
  .golangci.yml
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  config/options.go
  go.mod
  go.sum
  internal/encoding/mock/mock_encoder.go
  internal/httputil/client.go
  internal/sessions/cache/cache_store.go
  internal/sessions/cache/cache_store_test.go
  internal/sessions/cookie/cookie_store.go
  internal/sessions/cookie/cookie_store_test.go
  internal/sessions/cookie/middleware_test.go
  internal/sessions/errors.go
  internal/sessions/header/header_store.go
  internal/sessions/header/middleware_test.go
  internal/sessions/middleware.go
  internal/sessions/middleware_test.go
  internal/sessions/mock/mock_store.go
  internal/sessions/mock/mock_store_test.go
  internal/sessions/mock_store.go
  internal/sessions/queryparam/middleware_test.go
  internal/sessions/queryparam/query_store.go
  internal/sessions/queryparam/query_store_test.go
  internal/sessions/state.go
  internal/sessions/state_test.go
  internal/sessions/store.go
  internal/telemetry/metrics/const.go
  proxy/forward_auth_test.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
Labels: improvement

#443 authorize: rename grpc files s/gprc/grpc
  authorize/grpc.go
  authorize/grpc_test.go
Labels: improvement
