Repository pomerium/pomerium, pull requests merged in 2019-08, with the labels that each got.

#250 Prevent nil pointer when reloading in single service mode
  CHANGELOG.md
  authorize/authorize.go
  authorize/authorize_test.go
  proxy/proxy.go
  proxy/proxy_test.go
Labels: bug

#241 authenticate: copy redirect url by value
  Makefile
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  cmd/pomerium/main_test.go
  internal/config/options.go
  internal/config/options_test.go
  internal/identity/providers.go
  proxy/proxy.go
  proxy/proxy_test.go
Labels: bug

#252 Fix info metrics registration
  authorize/authorize.go
  cmd/pomerium/main.go
  internal/config/options.go
  internal/telemetry/metrics/const.go
  proxy/proxy.go
Labels: bug

#254 config: fix url type regression (#253)
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  cmd/pomerium/main_test.go
  internal/config/options.go
  internal/config/options_test.go
  internal/identity/providers.go
  internal/urlutil/url.go
  internal/urlutil/url_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/proxy.go
  proxy/proxy_test.go
Labels: bug

#258 docs: readd programmatic-access
  docs/.vuepress/config.js
Labels: docs

#260 docs: add contributing guide for docs
  Makefile
  docs/.vuepress/config.js
  docs/community/contributing.md
  docs/community/developers-guide.md
  docs/community/from-source.md
  docs/community/img/contributing-edit-this-page-github.png
  docs/community/img/contributing-edit-this-page.png
  docs/community/img/local-development-osx-dns.png
Labels: docs

#265 docs: add mailing list and twitter
  docs/community/readme.md
Labels: docs

#270 docs: update kubernetes example
  docs/docs/quick-start/img/kubernetes-gke.png
  docs/docs/quick-start/kubernetes.md
  docs/docs/reference/examples.md
  docs/docs/reference/examples/docker/basic.docker-compose.yml
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/authenticate.service.yml
  docs/docs/reference/examples/kubernetes/authorize.service.yml
  docs/docs/reference/examples/kubernetes/httpbin.yml
  docs/docs/reference/examples/kubernetes/ingress.nginx.yml
  docs/docs/reference/examples/kubernetes/ingress.yml
  docs/docs/reference/examples/kubernetes/kubernetes-config.yaml
  docs/docs/reference/examples/kubernetes/kubernetes_gke.sh
  docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
  docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
  docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
  docs/docs/reference/examples/kubernetes/proxy.service.yml
  docs/docs/reference/reference.md
  scripts/kubernetes_gke.sh
Labels: docs

#271 docs: use algolia for search
  docs/.vuepress/config.js
  docs/.vuepress/theme/components/AlgoliaSearchBox.vue
Labels: docs

#276 dev: add code climate
  .travis.yml
Labels: NeedsDecision, improvement

#272 httputil: standardize http error handling
  authenticate/handlers.go
  authenticate/handlers_test.go
  docs/docs/CHANGELOG.md
  go.mod
  go.sum
  internal/httputil/errors.go
  internal/httputil/errors_test.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
  proxy/handlers.go
  proxy/handlers_test.go
Labels: improvement

#286 Fix pomerium cookie stripping
  internal/middleware/reverse_proxy.go
  internal/middleware/reverse_proxy_test.go
Labels: bug

#288 Move docker image builds to Travis CI
  .travis.yml
  .travis/docker_build.sh
  hooks/post_checkout
  hooks/pre_build
Labels: deployment

#293 Fix image build conditions
  .travis.yml
Labels: deployment
