Repository pomerium/pomerium, pull requests merged in 2019-10, with the labels that each got.

#327 internal/log: add unit tests
  internal/log/example_test.go
  internal/log/middleware_test.go
Labels: improvement

#332 internal/config: Switch to using struct scoped viper instance
  authenticate/authenticate_test.go
  cmd/pomerium/main_test.go
  docs/docs/CHANGELOG.md
  internal/config/options.go
  internal/config/options_test.go
  proxy/proxy_test.go
Labels: improvement

#336 docs: use updated build in examples (v0.3.X branch)
  docs/docs/reference/examples/docker/basic.docker-compose.yml
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
  docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
  docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
Labels: docs

#334 docs: add nist publication to background
  docs/docs/background.md
Labels: docs

#340 github: make issue templates less annoying
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE
Labels: docs

#335 docs: add version dropdown
  docs/.vuepress/config.js
  docs/.vuepress/theme/components/DropdownLink.vue
  docs/.vuepress/theme/components/NavLinks.vue
  docs/docs/reference/examples/docker/basic.docker-compose.yml
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
  docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
  docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
Labels: docs

#341 docs: use dev for current master branch
  docs/.vuepress/config.js
Labels: docs

#342 internal/config: fix on config change
  cmd/pomerium/main.go
  internal/config/options.go
Labels: bug

#324 proxy: support external access control request handling (forward auth)
  authenticate/handlers.go
  docs/docs/CHANGELOG.md
  docs/docs/reference/img/auth-flow-diagram.svg
  docs/docs/reference/reference.md
  internal/config/options.go
  internal/config/policy.go
  internal/templates/templates.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/proxy.go
Labels: improvement

#348 proxy: use custom 404 handler
  proxy/proxy.go
Labels: bug

#347 proxy: fix dashboard path prefix
  proxy/proxy.go
Labels: bug

#346 proxy: add per-route request headers setting
  docs/docs/CHANGELOG.md
  docs/docs/reference/reference.md
  internal/config/policy.go
  internal/middleware/middleware.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
Labels: feature

#353 proxy: fix routes with non-standard ports
  go.mod
  go.sum
Labels: bug

#351 internal/sessions: separate query params, auth-header, and cookie stores
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
  internal/sessions/header_store.go
  internal/sessions/middleware.go
  internal/sessions/middleware_test.go
  internal/sessions/query_store.go
  internal/sessions/store.go
  internal/sessions/util.go
  internal/sessions/util_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/proxy.go
Labels: improvement

#355 authorize: change http addr if conflict
  internal/config/options.go
  internal/httputil/server.go
Labels: bug

#350 deployment: prepare v0.4.0
  VERSION
  docs/.vuepress/config.js
  docs/docs/CHANGELOG.md
  docs/docs/identity-providers/cognito.md
  docs/docs/quick-start/helm.md
  docs/docs/quick-start/img/synology-reverse-proxy.png
  docs/docs/quick-start/kubernetes.md
  docs/docs/quick-start/synology.md
  docs/docs/readme.md
  docs/docs/reference/certificates.md
  docs/docs/reference/examples/config/config.example.env
  docs/docs/reference/examples/config/config.example.yaml
  docs/docs/reference/examples/docker/basic.docker-compose.yml
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/ingress.nginx.yml
  docs/docs/reference/examples/kubernetes/kubernetes-config.yaml
  docs/docs/reference/examples/kubernetes/kubernetes_nginx.sh
  docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
  docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
  docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
  docs/docs/reference/getting-users-identity.md
  docs/docs/reference/reference.md
  docs/docs/releases.md
  docs/docs/upgrading.md
Labels: deployment

#356 docs: use master for docs again
  docs/.vuepress/config.js
  docs/docs/reference/examples/docker/basic.docker-compose.yml
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
  docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
  docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
Labels: docs

#360 docs: make authorize service url more clear
  docs/docs/reference/examples/config/config.example.env
  docs/docs/reference/examples/config/config.example.yaml
  docs/docs/reference/examples/config/config.minimal.yaml
  docs/docs/reference/examples/config/config.visual-studio-code.yaml
  docs/docs/reference/reference.md
  docs/recipes/vs-code-server.md
Labels: docs

#361 docs: add faq / troubleshooting guide
  docs/.vuepress/config.js
  docs/docs/FAQ.md
  docs/docs/reference/reference.md
Labels: docs

#364 bug: fix forward-auth redirect & add Kubernetes recipe example
  docs/docs/CHANGELOG.md
  docs/docs/reference/reference.md
  docs/docs/upgrading.md
  proxy/handlers.go
  proxy/handlers_test.go
Labels: bug, cherry-pick

#368 proxy: strip added params from verify callback
  docs/docs/CHANGELOG.md
  docs/docs/reference/reference.md
  docs/docs/upgrading.md
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/proxy.go
Labels: bug, cherry-pick

#365 docs: add k8s dashboard recipe
  docs/.vuepress/config.js
  docs/recipes/img/k8s-dashboard-login.png
  docs/recipes/img/k8s-fresh-dashboard.png
  docs/recipes/img/k8s-fwd-auth-example.mp4
  docs/recipes/img/k8s-proxied-example.mp4
  docs/recipes/img/k8s-tesla-hacked.png
  docs/recipes/kubernetes.md
  docs/recipes/yml/dashboard-fwdauth.ingress.yaml
  docs/recipes/yml/dashboard-proxied.ingress.yaml
  docs/recipes/yml/letsencrypt-prod.yaml
  docs/recipes/yml/pomerium.ingress.yaml
Labels: docs

#369 v0.4.1
  VERSION
  docs/docs/CHANGELOG.md
  docs/docs/reference/examples/docker/basic.docker-compose.yml
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
  docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
  docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
Labels: cherry-pick, deployment

#370 v0.4.2
  VERSION
  docs/docs/CHANGELOG.md
  docs/docs/reference/examples/docker/basic.docker-compose.yml
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
  docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
  docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
Labels: blocked, cherry-pick

#371 docs: add enterprise contact form
  docs/.vuepress/config.js
  docs/.vuepress/theme/components/Home.vue
  docs/enterprise/readme.md
Labels: docs
