Repository pomerium/pomerium, pull requests merged in 2019-07, with the labels that each got.

#206 internal/sessions: support custom session domain
  CHANGELOG.md
  authenticate/authenticate.go
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
Labels: feature

#218 GRPC Metrics Improvements
  CHANGELOG.md
  cmd/pomerium/main.go
  docs/reference/readme.md
  internal/metrics/helpers_test.go
  internal/metrics/interceptors.go
  internal/metrics/interceptors_test.go
  internal/metrics/middleware_test.go
  internal/metrics/tags.go
  internal/metrics/view.go
  internal/metrics/view_test.go
  proxy/clients/clients.go
Labels: improvement

#220 HTTP metrics improvements
  CHANGELOG.md
  docs/reference/readme.md
  internal/metrics/helpers_test.go
  internal/metrics/middleware.go
  internal/metrics/middleware_test.go
  internal/metrics/tags.go
  internal/metrics/view.go
  proxy/proxy.go
Labels: improvement

#222 internal/sessions: add (chocolate chip) cookie chunks
  CHANGELOG.md
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
  internal/sessions/session_state.go
  internal/sessions/session_state_test.go
Labels: bug

#224 development: replace vet/lint with golangci-lint
  .golangci.yml
  Makefile
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/grpc_test.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  authorize/authorize_test.go
  cmd/pomerium/main.go
  cmd/pomerium/main_test.go
  internal/config/options.go
  internal/config/options_test.go
  internal/cryptutil/encrypt.go
  internal/cryptutil/encrypt_test.go
  internal/httputil/client.go
  internal/httputil/https.go
  internal/log/log_test.go
  internal/log/middleware_test.go
  internal/metrics/exporter.go
  internal/metrics/interceptors.go
  internal/metrics/middleware.go
  internal/metrics/tags.go
  internal/middleware/chain.go
  internal/middleware/chain_test.go
  internal/middleware/middleware_test.go
  internal/middleware/reverse_proxy_test.go
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
  internal/sessions/rest_store_test.go
  internal/sessions/session_state_test.go
  internal/tripper/chain.go
  proxy/clients/mock_clients_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/proxy.go
Labels: improvement

#223 docs: add contributing.md
  docs/.vuepress/config.js
  docs/docs/contributing.md
  docs/docs/local-development.md
Labels: docs

#226 internal/cryptutil: fixed potential panic on nil pubkey block
  internal/cryptutil/encrypt.go
  internal/cryptutil/encrypt_test.go
  internal/cryptutil/marshal.go
  internal/cryptutil/marshal_test.go
  internal/cryptutil/sign_test.go
Labels: bug

#234 internal/httputil: prefer X25519 over P256
  CHANGELOG.md
  internal/httputil/https.go
Labels: improvement

#228 deployment: fix 'dirty' build tag
  Makefile
Labels: NeedsInvestigation

#240 cryptutil: fix potential race with signer
  CHANGELOG.md
  internal/cryptutil/encrypt.go
  internal/cryptutil/marshal.go
  internal/cryptutil/mock_cipher_test.go
  internal/cryptutil/sign.go
Labels: bug

#243 cmd/pomerium: fix close on nil proxy clients
  cmd/pomerium/main.go
Labels: bug
