Repository pomerium/pomerium, pull requests merged in 2019-11, with the labels that each got.

#373 all: support route scoped sessions
  authenticate/authenticate.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  docs/docs/CHANGELOG.md
  docs/docs/upgrading.md
  go.mod
  go.sum
  internal/cryptutil/certificates.go
  internal/cryptutil/certificates_test.go
  internal/cryptutil/encrypt.go
  internal/cryptutil/encrypt_test.go
  internal/cryptutil/hmac.go
  internal/cryptutil/marshal.go
  internal/cryptutil/marshal_test.go
  internal/cryptutil/sign.go
  internal/cryptutil/sign_test.go
  internal/encoding/ecjson/ecjson.go
  internal/encoding/jws/jws.go
  internal/encoding/mock_encoder.go
  internal/encoding/mock_encoder_test.go
  internal/httputil/client.go
  internal/httputil/proxy.go
  internal/identity/google.go
  internal/identity/microsoft.go
  internal/identity/mock_provider.go
  internal/identity/okta.go
  internal/identity/onelogin.go
  internal/identity/providers.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
  internal/sessions/header_store.go
  internal/sessions/middleware.go
  internal/sessions/middleware_test.go
  internal/sessions/mock_store.go
  internal/sessions/mock_store_test.go
  internal/sessions/query_store.go
  internal/sessions/query_store_test.go
  internal/sessions/state.go
  internal/sessions/state_test.go
  internal/sessions/store.go
  internal/sessions/util.go
  internal/sessions/util_test.go
  internal/templates/templates.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
  proxy/proxy_test.go
  scripts/programmatic_access.py
  scripts/programmatic_access.sh
Labels: improvement

#376 internal/sessions: fix cookie clear session
  authenticate/authenticate.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  docs/docs/CHANGELOG.md
  internal/encoding/ecjson/ecjson.go
  internal/encoding/econding.go
  internal/encoding/jws/jws.go
  internal/encoding/mock/mock_encoder.go
  internal/encoding/mock/mock_encoder_test.go
  internal/encoding/mock_encoder.go
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
  internal/sessions/header_store.go
  internal/sessions/query_store.go
  internal/sessions/query_store_test.go
  internal/sessions/store.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/proxy.go
Labels: bug

#381 bug: fix bad callback url for programmatic
  authenticate/handlers.go
Labels: bug

#382 internal/sessions: fix upgrade path for new sessions
  internal/sessions/cookie_store.go
  proxy/middleware.go
Labels: bug

#386 internal/templates: properly truncate fields
  internal/templates/templates.go
Labels: bug

#387 authenticate: handle XHR redirect flow
  authenticate/handlers.go
  authenticate/handlers_test.go
  go.mod
  go.sum
  internal/httputil/constants.go
  internal/httputil/errors.go
  internal/httputil/handlers.go
  internal/httputil/handlers_test.go
  internal/middleware/middleware.go
  proxy/handlers.go
  proxy/middleware.go
Labels: discuss

#391 lint: bump golangci-lint 1.21.0
  .golangci.yml
  Makefile
  proxy/handlers.go
Labels: deployment

#396 proxy: Fix policy reload regression
  cmd/pomerium/main.go
  docs/docs/CHANGELOG.md
  proxy/proxy.go
  proxy/proxy_test.go
Labels: bug

#398 deployment: add release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: deployment

#389 proxy: fix forward auth, request signing
  authenticate/handlers.go
  authenticate/handlers_test.go
  cmd/pomerium/main.go
  config/options.go
  config/options_test.go
  docs/docs/reference/programmatic-access.md
  docs/recipes/yml/dashboard-fwdauth.ingress.yaml
  internal/httputil/constants.go
  internal/httputil/errors.go
  internal/httputil/headers.go
  internal/identity/providers.go
  internal/log/middleware.go
  internal/log/middleware_test.go
  internal/middleware/cors_test.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
  internal/sessions/middleware.go
  internal/urlutil/errors.go
  internal/urlutil/query_params.go
  internal/urlutil/signed.go
  internal/urlutil/signed_test.go
  internal/urlutil/url.go
  internal/urlutil/url_test.go
  proxy/forward_auth.go
  proxy/forward_auth_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
  scripts/programmatic_access.py
Labels: bug, cherry-pick

#402 depedencies: update minor and patch
  .github/PULL_REQUEST_TEMPLATE
  .github/release-drafter.yml
  go.mod
  go.sum
  renovate.json
Labels: dependency

#407 dependency: update protoc-gen-go generated protobuffs
  go.mod
  go.sum
  proto/authorize/authorize.pb.go
  proto/authorize/mock_authorize/mock_authorize.go
Labels: dependency

#408 docs: update v0.3.0 regarding all service mode
  docs/docs/upgrading.md
Labels: docs

#411 authenticate: fix impersonation getting cleared
  authenticate/handlers.go
  authenticate/handlers_test.go
  internal/frontend/assets/html/dashboard.go.html
  internal/frontend/statik/statik.go
  internal/urlutil/query_params.go
  proxy/handlers.go
Labels: bug
