Repository pomerium/pomerium, pull requests merged in 2019-09, with the labels that each got.

#290 authenticate: make service http only
  Makefile
  authenticate/authenticate.go
  authenticate/grpc.go
  authenticate/grpc_test.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  cmd/pomerium/main.go
  cmd/pomerium/main_test.go
  docs/docs/quick-start/synology.md
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/kubernetes-config.yaml
  docs/docs/reference/reference.md
  go.mod
  go.sum
  internal/config/options.go
  internal/config/options_test.go
  internal/cryptutil/encrypt.go
  internal/cryptutil/encrypt_test.go
  internal/cryptutil/sign.go
  internal/cryptutil/sign_test.go
  internal/httputil/errors.go
  internal/identity/google.go
  internal/identity/microsoft.go
  internal/identity/mock_provider.go
  internal/identity/okta.go
  internal/identity/onelogin.go
  internal/identity/providers.go
  internal/middleware/middleware.go
  internal/middleware/reverse_proxy_test.go
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
  internal/sessions/mock_store.go
  internal/sessions/rest_store.go
  internal/sessions/rest_store_test.go
  internal/sessions/state.go
  internal/sessions/state_test.go
  internal/sessions/store.go
  internal/telemetry/metrics/const.go
  proto/authenticate/authenticate.pb.go
  proto/authenticate/authenticate.proto
  proto/authenticate/convert.go
  proto/authenticate/mock_authenticate/mock_authenticate.go
  proxy/clients/authenticate_client.go
  proxy/clients/authenticate_client_test.go
  proxy/clients/authorize_client.go
  proxy/clients/authorize_client_test.go
  proxy/clients/clients.go
  proxy/clients/mock_clients.go
  proxy/clients/mock_clients_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/proxy.go
  proxy/proxy_test.go
Labels: improvement

#301 docs: fix example configuration urls
  docs/docs/reference/examples/config/config.example.env
  docs/docs/reference/examples/config/config.example.yaml
  docs/docs/reference/examples/config/config.minimal.env
  docs/docs/reference/examples/config/config.minimal.yaml
  docs/docs/reference/examples/config/config.visual-studio-code.yaml
  docs/docs/reference/examples/config/policy.example.yaml
  docs/docs/reference/examples/docker/basic.docker-compose.yml
  docs/docs/reference/examples/docker/nginx.docker-compose.yml
  docs/docs/reference/examples/kubernetes/kubernetes-config.yaml
Labels: docs

#300 all: refactor handler logic
  .gitignore
  3RD-PARTY
  authenticate/authenticate.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  authorize/authorize.go
  cmd/pomerium/main.go
  cmd/pomerium/main_test.go
  docs/docs/CHANGELOG.md
  docs/docs/reference/reference.md
  go.mod
  go.sum
  internal/config/options.go
  internal/config/policy.go
  internal/config/policy_test.go
  internal/cryptutil/encrypt.go
  internal/cryptutil/encrypt_test.go
  internal/httputil/router.go
  internal/httputil/router_test.go
  internal/middleware/chain.go
  internal/middleware/chain_test.go
  internal/middleware/doc.go
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
  internal/sessions/middleware.go
  internal/sessions/middleware_test.go
  internal/sessions/mock_store.go
  internal/sessions/state.go
  internal/sessions/state_test.go
  internal/sessions/store.go
  internal/templates/templates.go
  internal/urlutil/url.go
  internal/urlutil/url_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/proxy.go
  proxy/proxy_test.go
Labels: improvement

#315 docs: fix existing links
  docs/.vuepress/public/_redirects
  docs/docs/quick-start/synology.md
Labels: docs

#317 proxy: remove accidental csrf checks from proxied routes
  proxy/handlers.go
Labels: bug

#309 docs: production configuration
  docs/.vuepress/config.js
  docs/docs/reference/production-deployment.md
Labels: docs

#304 proxy: fix group impersonation bug
  docs/docs/CHANGELOG.md
  proxy/handlers.go
Labels: bug

#310 proxy: handle double slash in paths
  cmd/pomerium/main.go
  docs/docs/CHANGELOG.md
  proxy/handlers.go
  proxy/proxy.go
Labels: bug

#314 docs: add AWS Cognito identity provider instructions
  docs/.vuepress/config.js
  docs/docs/identity-providers/cognito.md
  docs/docs/identity-providers/img/cognito-app-client-create.png
  docs/docs/identity-providers/img/cognito-app-client-details.png
  docs/docs/identity-providers/img/cognito-app-client-settings.png
  docs/docs/identity-providers/img/cognito-create-pool.png
  docs/docs/identity-providers/img/cognito-domain-name.png
  docs/docs/identity-providers/img/cognito-pool-settings.png
  docs/docs/identity-providers/img/cognito-pools.png
  docs/docs/identity-providers/img/cognito-service.png
  docs/docs/identity-providers/img/cognito-side-menu.png
  docs/docs/identity-providers/img/cognito-user-pool-name.png
Labels: docs

#320 middleware: health-check return 405 for non-get
  docs/docs/CHANGELOG.md
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
Labels: improvement

#316 authenticate: encrypt & mac oauth callback state
  authenticate/authenticate.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  docs/docs/CHANGELOG.md
  go.mod
  go.sum
  internal/cryptutil/encrypt.go
  internal/cryptutil/encrypt_test.go
  internal/cryptutil/helpers.go
  internal/cryptutil/helpers_test.go
  internal/cryptutil/hmac.go
  internal/cryptutil/hmac_test.go
  internal/cryptutil/mock_cipher.go
  internal/cryptutil/mock_cipher_test.go
  internal/cryptutil/sign.go
  internal/httputil/router_test.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
  internal/sessions/cookie_store.go
  internal/sessions/cookie_store_test.go
  internal/sessions/middleware_test.go
  internal/sessions/state.go
  internal/sessions/state_test.go
  internal/urlutil/url.go
  proxy/handlers_test.go
  proxy/proxy.go
Labels: improvement

#321 proxy: use middleware to handle request flow
  cmd/pomerium/main.go
  go.sum
  internal/httputil/proxy.go
  internal/httputil/proxy_test.go
  internal/httputil/tls_test.go
  internal/middleware/cors.go
  internal/middleware/cors_test.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
  internal/middleware/reverse_proxy.go
  internal/middleware/reverse_proxy_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
  proxy/proxy_test.go
Labels: improvement

#322 scripts: fix helm gke script
  scripts/helm_gke.sh
Labels: bug, docs

#326 internal/log: return full `X-Forwarded-For`
  docs/docs/CHANGELOG.md
  internal/log/middleware.go
  internal/log/middleware_test.go
Labels: improvement

#329 bug: fix potential race condition in unit test
  internal/urlutil/url.go
  internal/urlutil/url_test.go
Labels: bug
