Repository pomerium/pomerium, pull requests merged in 2020-10, with the labels that each got.

#1481 ci: ensure systemd unit file is in packages
  .github/goreleaser.yaml
Labels: bug, deployment

#1478 examples: fix nginx example
  examples/nginx/httpbin.conf
  examples/nginx/pomerium.conf
  examples/nginx/proxy.conf
Labels: docs

#1482 forward-auth: use envoy's ext_authz check
  authorize/grpc.go
  internal/controlplane/xds_listeners_test.go
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
  internal/urlutil/query_params.go
  internal/urlutil/url.go
  internal/urlutil/url_test.go
  proxy/forward_auth.go
  proxy/forward_auth_test.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
  proxy/proxy_test.go
  proxy/state.go
Labels: improvement

#1512 deployment: run go mod tidy
  go.sum
Labels: dependency

#1521 internal/frontend: resolve authN helper url
  authorize/check_response.go
  internal/frontend/assets/html/error.go.html
  internal/frontend/statik/statik.go
Labels: bug

#1533 authorize: add redirect url to debug page
  authorize/check_response.go
Labels: bug

#1505 fwd-auth: match nginx-ingress config
  .devcontainer/envs/nginx.yaml
  authorize/grpc.go
  authorize/grpc_test.go
  examples/nginx/auth.conf
  examples/nginx/docker-compose.yaml
  examples/nginx/ext_authz.conf
  examples/nginx/httpbin.conf
  examples/nginx/proxy.conf
Labels: bug

#1495 authenticate: remove unused paths, generate cipher at startup, remove qp store
  authenticate/handlers.go
  authenticate/handlers_test.go
  authenticate/state.go
  internal/httputil/errors.go
  internal/httputil/handlers.go
  internal/httputil/handlers_test.go
  internal/urlutil/query_params.go
Labels: improvement

#1519 chore(deps): upgrade envoy to v0.16.0
  scripts/embed-envoy.bash
Labels: dependency

#1556 [Backport 0-10-0] Remove typo on remove_request_headers docs
  docs/reference/readme.md
Labels: docs

#1555 github: fix retrieving team id with graphql API (#1554)
  internal/directory/github/github.go
  internal/directory/github/github_test.go
Labels: backport 0-10-0, bug
