Repository pomerium/pomerium, pull requests merged in 2020-04, with the labels that each got.

#583 deployment: Add testing workflow
  .github/workflows/test.yaml
  .travis.yml
Labels: deployment

#576 deployment: release v0.7.0
  VERSION
  docs/.vuepress/config.js
  docs/.vuepress/theme/components/Home.vue
  docs/configuration/examples/docker/basic.docker-compose.yml
  docs/configuration/examples/docker/nginx.docker-compose.yml
  docs/docs/CHANGELOG.md
  docs/docs/identity-providers/azure.md
  docs/docs/identity-providers/google.md
  docs/docs/identity-providers/okta.md
  docs/docs/identity-providers/one-login.md
  docs/docs/identity-providers/readme.md
  docs/docs/releases.md
  docs/docs/upgrading.md
Labels: deployment

#586 deployment: publish with github actions and goreleaser
  .github/Dockerfile-release
  .github/Dockerfile-release.arm32v6
  .github/Dockerfile-release.arm32v7
  .github/Dockerfile-release.arm64v8
  .github/goreleaser.yaml
  .github/workflows/release.yaml
  .travis.yml
  .travis/docker_build.sh
  Dockerfile
  Dockerfile.arm32v6
  Dockerfile.arm32v7
  Dockerfile.arm64v8
Labels: deployment

#594 Backport fix group impersionation in v0.6 branch
  internal/frontend/assets/html/dashboard.go.html
  internal/frontend/statik/statik.go
Labels: cherry-pick

#593 grpcutil: remove unused pkg
  internal/grpcutil/doc.go
Labels: improvement

#597 site: fix site on mobile
  docs/.vuepress/config.js
  docs/.vuepress/styles/palette.styl
  docs/.vuepress/theme/components/AlgoliaSearchBox.vue
  docs/.vuepress/theme/components/DropdownLink.vue
  docs/.vuepress/theme/components/DropdownTransition.vue
  docs/.vuepress/theme/components/Home.vue
  docs/.vuepress/theme/components/NavLink.vue
  docs/.vuepress/theme/components/NavLinks.vue
  docs/.vuepress/theme/components/Navbar.vue
  docs/.vuepress/theme/components/Page.vue
  docs/.vuepress/theme/components/Sidebar.vue
  docs/.vuepress/theme/components/SidebarButton.vue
  docs/.vuepress/theme/components/SidebarGroup.vue
  docs/.vuepress/theme/components/SidebarLink.vue
  docs/.vuepress/theme/components/SidebarLinks.vue
  docs/.vuepress/theme/global-components/Badge.vue
  docs/.vuepress/theme/index.js
  docs/.vuepress/theme/layouts/404.vue
  docs/.vuepress/theme/layouts/Layout.vue
  docs/.vuepress/theme/noopModule.js
  docs/.vuepress/theme/package.json
  docs/.vuepress/theme/styles/arrow.styl
  docs/.vuepress/theme/styles/code.styl
  docs/.vuepress/theme/styles/config.styl
  docs/.vuepress/theme/styles/custom-blocks.styl
  docs/.vuepress/theme/styles/index.styl
  docs/.vuepress/theme/styles/mobile.styl
  docs/.vuepress/theme/styles/palette.styl
  docs/.vuepress/theme/styles/toc.styl
  docs/.vuepress/theme/styles/wrapper.styl
  docs/.vuepress/theme/util/index.js
Labels: bug, cherry-pick, docs

#596 Add configurable JWT claim headers
  config/options.go
  docs/configuration/readme.md
  docs/docs/upgrading.md
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
Labels: cherry-pick, improvement

#582 internal/identity: implement github provider support
  authenticate/handlers.go
  docs/.vuepress/config.js
  docs/docs/identity-providers/github.md
  docs/docs/identity-providers/img/github/github-oauth-creation.png
  docs/docs/identity-providers/img/github/github-signon-page.png
  docs/docs/identity-providers/img/github/github-user-profile.png
  internal/identity/errors.go
  internal/identity/github.go
  internal/identity/providers.go
Labels: feature

#602 cli: fix confusing comments
  cmd/pomerium-cli/cli.go
Labels: improvement

#598 deployment: Improve docker mutable tag publishing
  .github/goreleaser.yaml
  .github/workflows/docker-master.yaml
  .github/workflows/release.yaml
  Dockerfile
Labels: deployment

#608 docs: improve identity providers documentation
  docs/docs/identity-providers/cognito.md
  docs/docs/identity-providers/github.md
  docs/docs/identity-providers/gitlab.md
Labels: docs

#601 docs: update upgrading / changelog to v0.7.2
  docs/.vuepress/config.js
  docs/.vuepress/styles/palette.styl
  docs/configuration/readme.md
  docs/docs/CHANGELOG.md
  docs/docs/upgrading.md
Labels: cherry-pick, docs

#609 Bump grpc up to 1.27.1
  go.mod
  go.sum
Labels: bug, cherry-pick

#610 docs: update changelog for v0.7.3
  VERSION
  docs/docs/CHANGELOG.md
Labels: cherry-pick, deployment

#613 pomerium-cli: add service account docs
  cmd/pomerium-cli/cli.go
  docs/docs/reference/impersonation.md
  go.mod
  go.sum
Labels: bug, cherry-pick, docs

#617 docs: add release announcement post
  .github/release-drafter.yml
  docs/.vuepress/config.js
  docs/.vuepress/styles/palette.styl
  docs/.vuepress/theme/components/Home.vue
  docs/.vuepress/theme/layouts/IndexPost.vue
  docs/_posts/2020-04-16-release-0-7.md
  docs/docs/CHANGELOG.md
  docs/readme.md
  package.json
Labels: docs

#600 forward-auth: validate using forwarded uri header
  docs/configuration/readme.md
  docs/recipes/kubernetes.md
  proxy/forward_auth.go
  proxy/forward_auth_test.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
Labels: improvement

#624 authorize: fix authorization check for allowed_domains to only match current route
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/statik.go
Labels: bug, cherry-pick

#625 v0.7.5
  VERSION
  docs/docs/CHANGELOG.md
Labels: bug, cherry-pick

#615 implement path-based route matching
  .github/workflows/test.yaml
  Makefile
  authorize/evaluator/opa/opa_test.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/authz_test.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/grpc.go
  authorize/grpc_test.go
  config/options_test.go
  config/policy.go
  config/policy_test.go
  docs/configuration/readme.md
  docs/docs/upgrading.md
  proxy/forward_auth.go
  proxy/proxy.go
  proxy/proxy_test.go
  scripts/build-dev-docker.bash
Labels: feature, improvement

#626 docs: fix favicon
  docs/.vuepress/public/easier-to-manage.svg
  docs/.vuepress/public/favicon.ico
  docs/.vuepress/public/logo-no-text.svg
  docs/.vuepress/public/logo-round.png
  docs/.vuepress/public/logo-stacked.svg
  docs/.vuepress/public/logo.svg
  docs/.vuepress/public/remote.svg
  docs/.vuepress/public/security-in-depth.svg
  docs/.vuepress/styles/palette.styl
Labels: docs

#560 identity: abstract identity providers by type
  .golangci.yml
  authenticate/authenticate.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  internal/identity/errors.go
  internal/identity/gitlab.go
  internal/identity/microsoft.go
  internal/identity/oauth/github/github.go
  internal/identity/oauth/options.go
  internal/identity/oidc.go
  internal/identity/oidc/azure/microsoft.go
  internal/identity/oidc/errors.go
  internal/identity/oidc/gitlab/gitlab.go
  internal/identity/oidc/google/google.go
  internal/identity/oidc/oidc.go
  internal/identity/oidc/okta/okta.go
  internal/identity/oidc/onelogin/onelogin.go
  internal/identity/okta.go
  internal/identity/onelogin.go
  internal/identity/providers.go
Labels: improvement

#630 improvement: update gitlab api scope
  docs/docs/identity-providers/gitlab.md
  internal/identity/oidc/gitlab/gitlab.go
Labels: improvement

#637 github: fix nil pointer error
  authenticate/handlers.go
  internal/identity/oauth/github/github.go
Labels: bug

#638 integration-tests: add integration test suite
  .github/workflows/test.yaml
  Makefile
  go.mod
  go.sum
  integration/README.md
  integration/authorization_test.go
  integration/backends/httpdetails/index.js
  integration/dashboard_test.go
  integration/internal/cluster/certs.go
  integration/internal/cluster/cluster.go
  integration/internal/cluster/cmd.go
  integration/internal/cluster/cmd_linux.go
  integration/internal/cluster/cmd_notlinux.go
  integration/internal/cluster/setup.go
  integration/internal/flows/flows.go
  integration/internal/forms/forms.go
  integration/internal/httputil/httputil.go
  integration/main_test.go
  integration/manifests/lib/httpdetails.libsonnet
  integration/manifests/lib/nginx-ingress-controller.libsonnet
  integration/manifests/lib/pomerium.libsonnet
  integration/manifests/lib/reference-openid-provider.libsonnet
  integration/manifests/lib/tls.libsonnet
  integration/manifests/manifests.jsonnet
Labels: improvement

#639 authorize: add support for .pomerium and unauthenticated routes
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/authz_test.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/grpc.go
  go.sum
  integration/authorization_test.go
  integration/dashboard_test.go
  integration/manifests/lib/pomerium.libsonnet
  proxy/forward_auth.go
  proxy/middleware.go
  proxy/middleware_test.go
Labels: improvement
