Repository pomerium/pomerium, pull requests merged in 2020-01, with the labels that each got.

#447 docs: s/fwdauth/forwardauth/
  docs/configuration/readme.md
  docs/docs/upgrading.md
  docs/recipes/kubernetes.md
  docs/recipes/yml/dashboard-forwardauth.ingress.yaml
  docs/recipes/yml/pomerium.ingress.yaml
Labels: docs

#448 proxy: fix unauthorized redirect loop (fwdauth)
  docs/recipes/kubernetes.md
  go.sum
  proxy/forward_auth.go
  proxy/forward_auth_test.go
  proxy/middleware.go
  proxy/middleware_test.go
Labels: bug

#457 cache : add cache service
  .gitignore
  .golangci.yml
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/handlers.go
  authorize/grpc.go
  authorize/grpc_test.go
  cache/cache.go
  cache/grpc.go
  cmd/pomerium/main.go
  cmd/pomerium/main_test.go
  config/helpers.go
  config/helpers_test.go
  config/options.go
  config/options_test.go
  go.mod
  go.sum
  internal/grpc/authorize/authorize.pb.go
  internal/grpc/authorize/authorize.proto
  internal/grpc/authorize/client/authorize_client.go
  internal/grpc/authorize/client/authorize_client_test.go
  internal/grpc/authorize/client/mock.go
  internal/grpc/authorize/client/mock_authorize/mock_authorize.go
  internal/grpc/cache/cache.pb.go
  internal/grpc/cache/cache.proto
  internal/grpc/cache/client/cache_client.go
  internal/grpc/client.go
  internal/grpc/client_test.go
  internal/grpc/server.go
  internal/grpc/server_test.go
  internal/grpc/testdata/example.crt
  internal/grpcutil/middleware.go
  internal/kv/autocache/autocache.go
  internal/kv/bolt/bolt.go
  internal/kv/redis/redis.go
  internal/kv/store.go
  internal/sessions/cache/cache_store.go
  internal/sessions/cache/cache_store_test.go
  internal/urlutil/query_params.go
  proxy/clients/authorize_client_test.go
  proxy/clients/clients_test.go
  proxy/forward_auth_test.go
  proxy/handlers_test.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
Labels: improvement

#465 chore(deps): update bolt and autocache
  go.mod
  go.sum
Labels: dependency

#463 proxy: add preserve host header
  config/policy.go
  docs/configuration/readme.md
  internal/httputil/proxy.go
  internal/httputil/proxy_test.go
  proxy/proxy.go
  proxy/proxy_test.go
Labels: improvement

#439 deployment: throw away golanglint-ci defaults
  .golangci.yml
  authenticate/authenticate.go
  authorize/authorize.go
  cache/cache.go
  config/doc.go
  config/options.go
  internal/cryptutil/certificates.go
  internal/cryptutil/doc.go
  internal/encoding/econding.go
  internal/encoding/mock/mock_encoder.go
  internal/fileutil/fileutil.go
  internal/frontend/templates.go
  internal/grpc/authorize/client/authorize_client.go
  internal/grpc/cache/client/cache_client.go
  internal/grpc/docs.go
  internal/grpcutil/doc.go
  internal/httputil/docs.go
  internal/kv/autocache/autocache.go
  internal/kv/bolt/bolt.go
  internal/kv/redis/redis.go
  internal/kv/store.go
  internal/middleware/responsewriter/wrap_writer.go
  internal/sessions/cache/cache_store.go
  internal/sessions/cookie/cookie_store.go
  internal/sessions/header/header_store.go
  internal/sessions/mock/mock_store.go
  internal/sessions/queryparam/query_store.go
  internal/sessions/store.go
  internal/telemetry/metrics/doc.go
  internal/telemetry/metrics/info.go
  internal/telemetry/trace/doc.go
  internal/telemetry/trace/trace.go
  internal/tripper/roundtripper.go
  internal/urlutil/url.go
  internal/version/version.go
  proxy/proxy.go
Labels: dependency, docs

#472 docs: fix cookie_domain
  docs/configuration/readme.md
Labels: docs
