Repository pomerium/pomerium, pull requests merged in 2020-09, with the labels that each got.

#1353 internal/controlplane: add telemetry http handler
  internal/controlplane/http.go
  internal/controlplane/server.go
Labels: backport 0-10-0

#1356 deps: go mod tidy
  go.sum
Labels: dependency

#1359 internal/directory/okta: acceept non-json service account
  internal/directory/okta/okta.go
  internal/directory/okta/okta_test.go
Labels: backport 0-10-0, bug

#1357 deps: ensure renovate runs `go mod tidy`
  renovate.json
Labels: dependency

#1365 deployment: fully split release archives and brews
  .github/goreleaser.yaml
  docs/docs/installation.md
Labels: deployment

#1370 internal/directory/okta: remove rate limiter
  docs/reference/readme.md
  go.mod
  go.sum
  internal/directory/okta/okta.go
  internal/directory/provider.go
Labels: backport 0-10-0

#1368 {proxy/controlplane}: make health checks debug level
  .github/ISSUE_TEMPLATE/bug_report.md
  internal/controlplane/grpc_accesslog.go
  internal/controlplane/http.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
Labels: improvement

#1377 docs: update azure docs
  docs/docs/identity-providers/azure.md
  docs/docs/identity-providers/img/azure-add-groups-claim.png
  docs/docs/identity-providers/img/azure-api-settings.png
  docs/docs/identity-providers/img/azure-app-registrations.png
  docs/docs/identity-providers/img/azure-application-dashbaord.png
  docs/docs/identity-providers/img/azure-create-application.png
  docs/docs/identity-providers/img/azure-create-key.png
  docs/docs/identity-providers/img/azure-dashboard.png
  docs/docs/identity-providers/img/azure-endpoints.png
  docs/docs/identity-providers/img/azure-ids.png
  docs/docs/identity-providers/img/azure-redirect-url.png
  docs/docs/identity-providers/img/azure/azure-add-a-platform.png
  docs/docs/identity-providers/img/azure/azure-api-settings.png
  docs/docs/identity-providers/img/azure/azure-app-registrations.png
  docs/docs/identity-providers/img/azure/azure-application-dashboard.png
  docs/docs/identity-providers/img/azure/azure-create-application.png
  docs/docs/identity-providers/img/azure/azure-create-key.png
  docs/docs/identity-providers/img/azure/azure-dashboard.png
  docs/docs/identity-providers/img/azure/azure-endpoints.png
  docs/docs/identity-providers/img/azure/azure-redirect-url.png
Labels: backport 0-10-0, backport latest, docs

#1388 Remove typo on remove_request_headers docs
  docs/reference/readme.md
Labels: backport latest, docs

#1387 internal/envoy: start epoch from 0
  internal/envoy/envoy.go
Labels: bug

#1390 Desimone/authenticate default logout
  authenticate/handlers.go
  internal/frontend/assets/html/dashboard.go.html
  internal/frontend/statik/statik.go
Labels: backport 0-10-0, bug

#1394 proxy: remove impersonate headers for kubernetes
  authorize/check_response.go
  authorize/check_response_test.go
  internal/controlplane/luascripts/remove-impersonate-headers.lua
  internal/controlplane/luascripts/statik.go
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  internal/controlplane/xds_lua.go
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
Labels: backport 0-10-0, bug

#1398 ci: publish cloudrun latest tag
  .github/workflows/release.yaml
  docs/guides/cloud-run.md
  examples/cloudrun/deploy.sh
Labels: backport 0-10-0, backport latest, deployment

#1409 controlplane: support P-384 / P-512 EC curves
  internal/controlplane/xds_cluster_test.go
  internal/controlplane/xds_clusters.go
Labels: backport 0-10-0

#1412 docs: fix grammar
  docs/docs/community/readme.md
Labels: docs

#1419 chore(docs): Fix typo in example policy
  examples/config/policy.example.yaml
Labels: docs

#1422 fix(examples): Use X-Pomerium-Claim headers
  examples/traefik/config.yaml
  examples/traefik/docker-compose.yaml
Labels: docs

#1420 controplane: remove p-521 EC
  internal/controlplane/xds_cluster_test.go
  internal/controlplane/xds_clusters.go
Labels: backport 0-10-0, bug

#1411 docs: Add Traefik + Kubernetes example
  docs/.vuepress/config.js
  docs/guides/traefik-ingress.md
  examples/traefik-ingress/README.md
  examples/traefik-ingress/add_repos.sh
  examples/traefik-ingress/crds/middleware.yaml
  examples/traefik-ingress/install.sh
  examples/traefik-ingress/values/hello.yaml
  examples/traefik-ingress/values/pomerium.yaml
  examples/traefik-ingress/values/traefik.yaml
Labels: backport latest, docs

#1434 deps: go mod tidy
  go.sum
Labels: dependency

#1433 proxy: always use https for application callback
  proxy/forward_auth.go
  proxy/forward_auth_test.go
Labels: backport 0-10-0, bug

#1437 Add v0.10.4 changelog entry
  docs/docs/CHANGELOG.md
Labels: docs

#1439 deployment: bump release go to v1.15.x
  .github/workflows/release.yaml
Labels: deployment

#1438 httputil: remove retry button
  internal/frontend/assets/html/error.go.html
  internal/httputil/errors.go
Labels: backport 0-10-0, bug

#1441 docs: update 0.10.4 changelog
  docs/docs/CHANGELOG.md
Labels: docs

#1444 docs: add architecture diagram for cloudrun
  docs/guides/cloud-run.md
  docs/guides/img/cloud-run/architecture.svg
Labels: backport latest, docs

#1450 redis: use pubsub instead of keyspace events
  internal/databroker/server.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
Labels: backport 0-10-0

#1455 identity manager: fix directory sync timing
  internal/identity/manager/manager.go
Labels: bug

#1458 deployment: Generate deb and rpm packages
  .github/goreleaser.yaml
  docs/docs/installation.md
  ospkg/conf/config.yaml
  ospkg/pomerium.service
  ospkg/postinstall.sh
  ospkg/preinstall.sh
Labels: deployment

#1469 docs: Update changelog for v0.10.5
  docs/docs/CHANGELOG.md
Labels: backport latest, docs

#1475 deps: update envoy arm64 to v1.15.1
  scripts/embed-envoy.bash
Labels: backport 0-10-0, dependency
