Repository pomerium/pomerium, pull requests merged in 2020-12, with the labels that each got.

#1632 deps: update hashstructure v2
  config/options.go
  config/policy.go
  go.mod
  go.sum
  internal/databroker/config_source.go
  internal/hashutil/hashutil.go
  internal/hashutil/hashutil_test.go
Labels: dependency

#1631 authorize: add signature algo support (RSA / EdDSA)
  authenticate/state.go
  authorize/evaluator/evaluator.go
  config/options.go
  docs/docs/topics/getting-users-identity.md
  docs/reference/readme.md
  go.mod
  go.sum
  pkg/cryptutil/jose.go
  pkg/cryptutil/jose_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  scripts/generate_self_signed_signing_key.sh
Labels: improvement

#1635 docs: update build badge
  README.md
Labels: docs

#1637 fix profile image on dashboard
  internal/frontend/assets/html/dashboard.go.html
  internal/frontend/statik/statik.go
  internal/frontend/templates.go
Labels: improvement

#1640 fix ordering of autocert config source
  internal/cmd/pomerium/pomerium.go
Labels: bug

#1643 deployment: enable multi-arch release images
  .github/Dockerfile-release
  .github/Dockerfile-release.arm32v6
  .github/Dockerfile-release.arm32v7
  .github/Dockerfile-release.arm64v8
  .github/goreleaser.yaml
  .github/workflows/release.yaml
  docs/docs/upgrading.md
Labels: deployment

#1645 update docs
  docs/.vuepress/config.js
  docs/docs/FAQ.md
  docs/docs/architecture.md
  docs/docs/community/security.md
  docs/docs/identity-providers/cognito.md
  docs/docs/identity-providers/google.md
  docs/docs/installation.md
  docs/docs/quick-start/binary.md
  docs/docs/quick-start/helm.md
  docs/docs/quick-start/kubernetes.md
  docs/docs/quick-start/synology.md
  docs/docs/readme.md
  docs/docs/releases.md
  docs/docs/upgrading.md
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: docs

#1648 microsoft: add support for common endpoint
  internal/identity/oidc/azure/microsoft.go
Labels: improvement

#1647 use the directory email when provided for the jwt
  authorize/evaluator/evaluator.go
Labels: improvement

#1661 ci: fix pomerium-cli rpm name
  .github/goreleaser.yaml
Labels: backport-0-11-0

#1662 [Backport 0-11-0] ci: fix pomerium-cli rpm name
  .github/goreleaser.yaml
Labels: deployment

#1663 docs: add v0.11 link to version menu
  docs/.vuepress/config.js
Labels: backport 0-11-0, docs

#1665 docs: add allowed_idp_claims docs
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: backport 0-11-0, docs

#1666 improve ca cert error message, use GetCertPool for databroker storage
  cmd/pomerium-cli/kubernetes.go
  go.sum
  internal/databroker/server.go
  pkg/cryptutil/tls.go
Labels: improvement

#1668 remove "see policy" phrase in settings docs
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: backport 0-11-0, docs

#1671 don't create users when updating sessions
  internal/identity/manager/manager.go
Labels: backport 0-11-0, bug

#1675 fix concurrency race
  pkg/storage/inmemory/inmemory.go
  pkg/storage/inmemory/inmemory_test.go
Labels: backport 0-11-0

#1687 deployment: Fix docker and rpm workflows
  .github/goreleaser.yaml
  .github/workflows/release.yaml
Labels: backport 0-11-0, deployment

#1688 [Backport 0-11-0] deployment: Fix docker and rpm workflows
  .github/goreleaser.yaml
  .github/workflows/release.yaml
Labels: deployment

#1691 docs: fix nginx config
  docs/reference/readme.md
  docs/reference/settings.yaml
  examples/config/config.example.yaml
  examples/config/config.minimal.yaml
  examples/config/policy.example.yaml
  examples/kubernetes/kubernetes-config.yaml
  examples/kubernetes/values.yaml
  examples/nginx/config.yaml
  examples/nginx/docker-compose.yaml
  examples/nginx/httpbin.conf
  examples/nginx/proxy.conf
  examples/traefik/config.yaml
Labels: backport 0-11-0, docs

#1698 config: fix ignored yaml fields
  config/options.go
Labels: bug

#1696 TCP client command
  cmd/pomerium-cli/tcp.go
  go.mod
  go.sum
  internal/authclient/authclient.go
  internal/authclient/authclient_test.go
  internal/authclient/config.go
  internal/cliutil/clitutil.go
  internal/cliutil/jwtcache.go
  internal/cliutil/jwtcache_test.go
  internal/tcptunnel/config.go
  internal/tcptunnel/tcptunnel.go
  internal/tcptunnel/tcptunnel_test.go
Labels: improvement

#1702 docs: replace httpbin with verify
  .devcontainer/envs/nginx.yaml
  .devcontainer/envs/traefik.yaml
  docs/docs/community/contributing.md
  docs/docs/quick-start/binary.md
  docs/docs/quick-start/from-source.md
  docs/docs/quick-start/helm.md
  docs/docs/quick-start/readme.md
  docs/docs/topics/programmatic-access.md
  docs/docs/upgrading.md
  docs/guides/cloud-run.md
  docs/guides/local-oidc.md
  docs/guides/mtls.md
  docs/guides/nginx.md
  docs/reference/readme.md
  docs/reference/settings.yaml
  examples/cloudrun/README.md
  examples/cloudrun/policy.template.yaml
  examples/config/config.example.yaml
  examples/config/config.minimal.yaml
  examples/config/policy.example.yaml
  examples/docker/autocert.docker-compose.yml
  examples/docker/basic.docker-compose.yml
  examples/docker/nginx.docker-compose.yml
  examples/kubernetes/kubernetes-config.yaml
  examples/mutual-tls/README.md
  examples/mutual-tls/example.config.yaml
  examples/nginx/README.md
  examples/nginx/config.yaml
  examples/nginx/docker-compose.yaml
  examples/nginx/verify.conf
  examples/traefik/README.md
  examples/traefik/config.yaml
  examples/traefik/docker-compose.yaml
  scripts/programmatic_access.py
Labels: backport 0-11-0, docs

#1712 docs: tcp support
  docs/.vuepress/config.js
  docs/docs/topics/tcp-support.md
  docs/reference/readme.md
  docs/reference/settings.yaml
  scripts/generate-settings-docs.py
Labels: docs

#1716 internal/controlplane: 0s default timeout for tcp routes
  go.sum
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
Labels: improvement

#1714 docs: add TCP guide
  docs/.vuepress/config.js
  docs/guides/tcp.md
  examples/tcp/README.md
  examples/tcp/_wildcard.localhost.pomerium.io-key.pem
  examples/tcp/_wildcard.localhost.pomerium.io.pem
  examples/tcp/config.yaml
  examples/tcp/docker-compose.yaml
  examples/tcp/rootCA-key.pem
  examples/tcp/rootCA.pem
  examples/tcp/ssh_config
Labels: docs

#1586 authenticate: oidc frontchannel-logout endpoint
  authenticate/handlers.go
  authenticate/handlers_test.go
  docs/.vuepress/config.js
  docs/docs/topics/single-sign-out.md
Labels: improvement

#1722 k8s cmd: use authclient package
  cmd/pomerium-cli/kubernetes.go
  cmd/pomerium-cli/main.go
  cmd/pomerium-cli/tcp.go
  go.sum
Labels: improvement

#1723 update azure docs
  docs/docs/identity-providers/azure.md
  docs/docs/identity-providers/img/azure/azure-api-permissions.png
Labels: backport 0-11-0, bug, docs

#1726 cli: add version command
  Makefile
  VERSION
  cmd/pomerium-cli/version.go
  docs/docs/installation.md
Labels: improvement
