Repository pomerium/pomerium, pull requests merged in 2020-03, with the labels that each got.

#521 ci: Consolidate matrix build parameters
  .travis.yml
Labels: deployment

#519 docs: make from source quickstart
  docs/.vuepress/config.js
  docs/configuration/examples/config/config.minimal.yaml
  docs/docs/community/contributing.md
  docs/docs/quick-start/from-source.md
  package.json
Labels: docs

#522 config: Remove superfluous Options.Checksum type conversions
  authorize/authorize.go
  config/options.go
  config/options_test.go
  internal/telemetry/metrics/info.go
  internal/telemetry/metrics/info_test.go
  proxy/proxy.go
Labels: improvement

#528 dependency: use go mod redis
  go.mod
  go.sum
  internal/kv/redis/redis.go
Labels: dependency

#529 identity: support oidc UserInfo Response
  go.mod
  go.sum
  internal/identity/google.go
  internal/identity/microsoft.go
  internal/identity/oidc.go
  internal/identity/okta.go
  internal/identity/onelogin.go
  internal/identity/providers.go
  internal/sessions/state.go
Labels: improvement

#536 Make IDP_PROVIDER env var mandatory
  authenticate/authenticate.go
Labels: improvement

#518 providers: re-enable gitlab support
  docs/.vuepress/config.js
  docs/docs/identity-providers/gitlab.md
  docs/docs/identity-providers/img/gitlab-credentials.png
  docs/docs/identity-providers/img/gitlab/gitlab-create-application.png
  docs/docs/identity-providers/img/gitlab/gitlab-create-applications.png
  docs/docs/identity-providers/img/gitlab/gitlab-credentials.png
  docs/docs/identity-providers/img/gitlab/gitlab-verify-access.png
  go.sum
  internal/identity/gitlab.go
  internal/identity/providers.go
Labels: feature

#544 sessions: signout bug , fixes #530
  internal/sessions/state.go
Labels: bug, cherry-pick

#553 authorization: log audience claim failure
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/statik.go
  cmd/pomerium/main.go
  internal/frontend/statik/statik.go
  internal/sessions/state.go
  internal/sessions/state_test.go
Labels: improvement

#552 cmd: add cli to generate service accounts
  cmd/pomerium-cli/cli.go
  go.mod
  go.sum
Labels: feature, improvement

#561 authenticate: return 401 for some specific error codes
  authenticate/handlers.go
  authenticate/handlers_test.go
Labels: improvement

#562 Consider service port for session audiences
  authenticate/handlers.go
  authenticate/handlers_test.go
  internal/identity/gitlab.go
  internal/identity/providers.go
Labels: bug

#566 fix `the` typo
  docs/docs/quick-start/binary.md
  docs/docs/reference/programmatic-access.md
  internal/kv/autocache/autocache.go
Labels: docs

#569 bug: fix group impersonation
  internal/frontend/assets/html/dashboard.go.html
  internal/frontend/statik/statik.go
Labels: bug, cherry-pick

#571 gitlab/identity: change group unique identifier to ID
  docs/docs/identity-providers/gitlab.md
  internal/identity/gitlab.go
Labels: improvement
