Repository pomerium/pomerium, pull requests merged in 2020-05, with the labels that each got.

#642 Improve JWT header behavior
  proxy/forward_auth.go
  proxy/middleware.go
  proxy/middleware_test.go
  proxy/proxy.go
Labels: improvement

#645 ci: force docker driver
  .github/workflows/test.yaml
Labels: dependency, deployment

#654 Backport fix for panic on reload to 0.7.x
  authorize/authorize.go
  docs/docs/CHANGELOG.md
Labels: bug, cherry-pick

#644 cryptutil: add automatic certificate management
  .gitignore
  cmd/pomerium/main.go
  cmd/pomerium/main_test.go
  config/options.go
  config/options_test.go
  docs/configuration/examples/config/config.example.env
  docs/configuration/examples/config/config.minimal.env
  docs/configuration/examples/config/config.minimal.yaml
  docs/configuration/readme.md
  docs/docs/community/contributing.md
  docs/docs/quick-start/binary.md
  docs/docs/quick-start/from-source.md
  docs/docs/quick-start/helm.md
  docs/docs/quick-start/kubernetes.md
  docs/docs/quick-start/readme.md
  docs/docs/quick-start/synology.md
  docs/docs/reference/certificates.md
  docs/docs/reference/sh/generate_wildcard_cert.sh
  go.mod
  go.sum
  internal/cryptutil/tls.go
  internal/cryptutil/tls_test.go
  internal/grpc/server.go
  internal/grpc/server_test.go
  internal/httputil/options.go
  internal/httputil/server.go
  internal/httputil/server_test.go
  internal/kv/autocache/autocache.go
  proxy/proxy.go
Labels: improvement

#657 deps: go mod tidy
  go.sum
Labels: dependency

#658 deploy: autocert documentation and defaults
  .github/Dockerfile-release
  .github/Dockerfile-release.arm32v6
  .github/Dockerfile-release.arm32v7
  .github/Dockerfile-release.arm64v8
  Dockerfile
  docs/configuration/examples/config/config.minimal.yaml
  docs/configuration/examples/docker/autocert.docker-compose.yml
  docs/configuration/readme.md
  docs/docs/quick-start/readme.md
Labels: deployment, docs

#663 renovate: Update Renovate to run go mod tidy
  renovate.json
Labels: deployment

#686 deployment: release v0.8.0
  VERSION
  docs/.vuepress/config.js
  docs/.vuepress/public/_redirects
  docs/_posts/2020-05-11-release-0-8.md
  docs/configuration/examples/docker/autocert.docker-compose.yml
  docs/configuration/examples/docker/basic.docker-compose.yml
  docs/configuration/examples/docker/nginx.docker-compose.yml
  docs/configuration/examples/kubernetes/values.yaml
  docs/configuration/readme.md
  docs/docs/CHANGELOG.md
  docs/docs/quick-start/binary.md
  docs/docs/quick-start/helm.md
  docs/docs/quick-start/kubernetes.md
  docs/docs/reference/certificates.md
  docs/docs/reference/getting-users-identity.md
  docs/docs/upgrading.md
  docs/recipes/kubernetes.md
  docs/recipes/yml/pomerium.ingress.yaml
  scripts/helm_gke.sh
Labels: deployment

#696 docs: fixes to v0.8.0 docs
  docs/.vuepress/config.js
  docs/configuration/examples.md
  docs/configuration/examples/helm/helm_aws.sh
  docs/configuration/examples/helm/helm_gke.sh
  docs/configuration/readme.md
  docs/docs/quick-start/from-source.md
  docs/docs/quick-start/helm.md
  docs/docs/reference/certificates.md
  docs/jobs/Backend-Engineer.md
  docs/jobs/Frontend-Engineer.md
  docs/jobs/readme.md
Labels: cherry-pick, docs

#701 deployment: Envoy cross platform improvements
  .github/goreleaser.yaml
  internal/envoy/envoy_linux.go
  internal/envoy/envoy_notlinux.go
  scripts/embed-envoy.bash
Labels: deployment

#705 Update jwt_claims_headers docs
  docs/configuration/readme.md
Labels: cherry-pick, docs

#675 Documentation around Pomerium/Istio/Grafana
  docs/configuration/examples.md
  docs/configuration/examples/kubernetes/istio/gateway.yml
  docs/configuration/examples/kubernetes/istio/grafana.ini.yml
  docs/configuration/examples/kubernetes/istio/pomerium-helm-values.yml
  docs/configuration/examples/kubernetes/istio/service-entry.yml
  docs/configuration/examples/kubernetes/istio/virtual-services.yml
Labels: docs

#698 authenticate: save oauth2 tokens to cache
  Makefile
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  authorize/evaluator/evaluator.go
  authorize/grpc.go
  cache/grpc_test.go
  internal/controlplane/xds_listeners.go
  internal/grpc/cache/cache.go
  internal/grpc/cache/cache.pb.go
  internal/grpc/cache/client/cache_client.go
  internal/grpc/cache/mock/mock_cacher.go
  internal/hashutil/hashutil.go
  internal/hashutil/hashutil_test.go
  internal/identity/mock_provider.go
  internal/identity/oauth/github/github.go
  internal/identity/oidc/azure/microsoft.go
  internal/identity/oidc/errors.go
  internal/identity/oidc/gitlab/gitlab.go
  internal/identity/oidc/google/google.go
  internal/identity/oidc/oidc.go
  internal/identity/oidc/okta/okta.go
  internal/identity/oidc/onelogin/onelogin.go
  internal/identity/providers.go
  internal/kv/autocache/autocache.go
  internal/sessions/cache/cache_store.go
  internal/sessions/cache/cache_store_test.go
  internal/sessions/state.go
  internal/sessions/state_test.go
  internal/urlutil/query_params.go
Labels: improvement

#726 envoy: enable TLS verification for internal services
  go.sum
  integration/manifests/lib/pomerium.libsonnet
  internal/controlplane/xds_clusters.go
Labels: improvement

#741 authorize: fix nil reference (#704)
  authorize/grpc.go
  authorize/grpc_test.go
Labels: bug

#748 envoy: support ports in hosts for routing
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_routes.go
Labels: bug

#745 authenticate: add jwks and .well-known endpoint
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/handlers.go
  docs/configuration/readme.md
  docs/docs/reference/getting-users-identity.md
  internal/controlplane/xds_routes.go
  internal/cryptutil/jose.go
  internal/cryptutil/jose_test.go
Labels: feature

#751 authorize: add client mTLS support
  authorize/authorize.go
  authorize/errors.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/opa/functions.go
  authorize/evaluator/opa/functions_test.go
  authorize/evaluator/opa/opa.go
  authorize/evaluator/opa/opa_test.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/grpc.go
  cache/grpc.go
  cache/grpc_test.go
  config/options.go
  docs/configuration/readme.md
  go.mod
  internal/controlplane/luascripts/statik.go
  internal/controlplane/xds_listeners.go
  internal/frontend/statik/statik.go
  internal/grpc/authorize/authorize.pb.go
  internal/grpc/authorize/authorize.proto
  internal/grpc/cache/cache.pb.go
  internal/httputil/httputil.go
  scripts/protoc
  scripts/protoc-gen-go
Labels: feature

#757 authorize: refactor and add additional unit tests
  authorize/check_response.go
  authorize/evaluator/evaluator.go
  authorize/grpc.go
  authorize/grpc_test.go
Labels: improvement

#758 config: add some cert tests
  config/options_test.go
Labels: improvement

#759 authenticate: add tests to signing endpoints
  authenticate/authenticate_test.go
  authenticate/handlers_test.go
Labels: improvement

#762 proxy: fix bug that would allow failed refresh session to continue
  internal/httputil/errors.go
  proxy/middleware.go
Labels: bug

#773 proxy/forward-auth: block expired request prior to 302
  internal/httputil/errors.go
  proxy/forward_auth.go
Labels: bug, cherry-pick

#772 state: infer user (`user`) from subject (`sub`)
  internal/sessions/state.go
  internal/sessions/state_test.go
Labels: cherry-pick, improvement

#760 authenticate: ensure authorize url is set
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/handlers_test.go
Labels: bug

#778 xds: lazy-load root ca bundle to avoid log in version command
  internal/controlplane/xds.go
Labels: bug

#780 forward-auth: support x-forwarded-uri
  proxy/forward_auth.go
Labels: bug

#784 docs: update traefik example and add note about forwarded headers
  docs/configuration/readme.md
Labels: docs

#782 fix: docs regarding claim headers
  docs/docs/reference/getting-users-identity.md
Labels: docs

#783 xds: disable cluster validation to handle out-of-order updates
  go.sum
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
Labels: bug

#789 xds: add catch-all for pomerium routes
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
Labels: bug

#790 authenticate: remove authorize url validate check
  authenticate/authenticate.go
  authenticate/authenticate_test.go
Labels: bug

#800 Fix typo on configuration doc
  docs/configuration/readme.md
Labels: docs

#801 docs: update dockerfiles for v0.9.0
  docs/configuration/examples/docker/autocert.docker-compose.yml
  docs/configuration/examples/docker/basic.docker-compose.yml
  docs/configuration/examples/docker/nginx.docker-compose.yml
Labels: docs

#803 docs: add argo recipe
  docs/recipes/argo.md
  docs/recipes/readme.md
Labels: docs

#802 telemetry: service label updates
  authorize/authorize.go
  config/options.go
  config/trace.go
  config/trace_test.go
  docs/configuration/readme.md
  docs/docs/upgrading.md
  internal/cmd/pomerium/pomerium.go
  internal/envoy/envoy.go
  internal/envoy/envoy_test.go
  internal/telemetry/grpc.go
  internal/telemetry/util.go
  internal/telemetry/util_test.go
  proxy/proxy.go
Labels: improvement

#804 telemetry: Fix missing/incorrect grpc labels
  internal/cmd/pomerium/pomerium.go
  internal/controlplane/server.go
  internal/telemetry/grpc.go
Labels: bug

#807 docs: add mTLS recipe
  docs/.vuepress/config.js
  docs/recipes/img/mtls/01-chrome-settings-certificates.png
  docs/recipes/img/mtls/02-import-client-certificate.png
  docs/recipes/img/mtls/03-enter-certificate-password.png
  docs/recipes/img/mtls/04-certificate-list.png
  docs/recipes/img/mtls/05-select-client-certificate.png
  docs/recipes/mtls.md
  docs/recipes/readme.md
Labels: docs

#806 authenticate: clear session if ctx fails
  authenticate/handlers.go
Labels: bug

#798 deployment: prepare 0.9.0
  VERSION
  docs/.vuepress/config.js
  docs/docs/CHANGELOG.md
  docs/docs/releases.md
  docs/docs/upgrading.md
  docs/recipes/argo.md
  docs/recipes/mtls.md
  docs/recipes/readme.md
Labels: deployment

#810 envoy: Switch to distroless/base for releases
  .github/Dockerfile-release
Labels: bug, deployment
