Repository pomerium/pomerium, pull requests merged in 2020-02, with the labels that each got.

#469 docs: update helm for v3
  scripts/helm_gke.sh
Labels: cherry-pick, docs

#468 cache: add option validations
  cache/cache.go
  cache/cache_test.go
  cache/grpc_test.go
Labels: bug, cherry-pick

#476 internal/cryptutil: standardize leeway to 5 mins
  internal/cryptutil/hmac.go
Labels: improvement

#478 docs: various fixes
  docs/readme.md
  docs/recipes/ad-guard.md
  docs/recipes/readme.md
Labels: cherry-pick, docs

#479 proxy: move set request headers before handle allow public access
  proxy/proxy.go
Labels: bug

#484 Roll back grpc to v1.25.1
  go.mod
  go.sum
Labels: dependency

#493 authenticate: make callback path configurable
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/handlers.go
  config/options.go
  config/options_test.go
  docs/configuration/readme.md
Labels: improvement

#505 docs: update background
  docs/docs/background.md
Labels: docs

#504 docs: fix kubernetes dashboard recipe docs
  docs/recipes/kubernetes.md
Labels: docs

#509 config: Expose and set default GRPC Server Keepalive Parameters
  cmd/pomerium/main.go
  config/options.go
  config/options_test.go
  docs/configuration/readme.md
  internal/grpc/server.go
  internal/grpc/server_test.go
Labels: improvement

#510 Ensure correct service name on GRPC related metrics
  cmd/pomerium/main.go
  go.sum
  internal/grpc/client.go
  internal/grpc/server.go
  internal/telemetry/metrics/grpc.go
  internal/telemetry/metrics/http.go
Labels: bug
