Repository pomerium/pomerium, pull requests merged in 2020-07, with the labels that each got.

#1040 docs/configuration: add doc for trailing slash limitation in "To" field
  docs/configuration/readme.md
Labels: backport 0-9-0, docs

#1045 docs/recipes: add local oidc example
  docs/recipes/local-oidc.md
  docs/recipes/readme.md
Labels: docs

#1074 Backport #1011
  .github/workflows/release.yaml
Labels: deployment

#1075 authorize: Force redirect scheme to https
  authorize/check_response.go
Labels: backport 0-9-0, bug

#1055 #1054 - Change config key parsing to attempt Base64 decoding first.
  config/options.go
  config/options_test.go
Labels: accepted, improvement

#1087 kubernetes docs
  docs/recipes/kubernetes-dashboard.md
  docs/recipes/kubernetes.md
Labels: docs

#1097 ci: Add cloudrun build
  .github/Dockerfile-cloudrun
  .github/goreleaser.yaml
  .github/workflows/release.yaml
Labels: deployment

#1102 docs: Move examples repo into main repo
  examples/mutual-tls/Dockerfile
  examples/mutual-tls/README.md
  examples/mutual-tls/docker-compose.yaml
  examples/mutual-tls/example.config.yaml
  examples/mutual-tls/main.go
  examples/mutual-tls/out/bad-ca.crl
  examples/mutual-tls/out/bad-ca.crt
  examples/mutual-tls/out/bad-ca.key
  examples/mutual-tls/out/bad-curl.crt
  examples/mutual-tls/out/bad-curl.csr
  examples/mutual-tls/out/bad-curl.key
  examples/mutual-tls/out/good-ca.crl
  examples/mutual-tls/out/good-ca.crt
  examples/mutual-tls/out/good-ca.key
  examples/mutual-tls/out/good-curl.crt
  examples/mutual-tls/out/good-curl.csr
  examples/mutual-tls/out/good-curl.key
  examples/mutual-tls/out/pomerium.crt
  examples/mutual-tls/out/pomerium.csr
  examples/mutual-tls/out/pomerium.key
  examples/mutual-tls/out/web-app.crt
  examples/mutual-tls/out/web-app.csr
  examples/mutual-tls/out/web-app.key
  examples/mutual-tls/scripts/curl.sh
  examples/mutual-tls/scripts/generate_certs.sh
  examples/traefik/README.md
  examples/traefik/config.yaml
  examples/traefik/docker-compose.yaml
Labels: docs

#1104 deployment: fix pomerium-cli release
  .github/goreleaser.yaml
Labels: deployment

#1103 authorize,proxy: allow traefik forward auth without uri query
  authorize/grpc.go
  authorize/grpc_test.go
  proxy/forward_auth.go
Labels: backport 0-9-0

#1101 docs: Cloud Run / GCP Serverless
  docs/.vuepress/config.js
  docs/configuration/readme.md
  docs/recipes/cloud-run.md
  docs/recipes/img/cloud-run/cloudrun-domains.png
  docs/recipes/img/cloud-run/cloudrun-overview.png
  docs/recipes/img/cloud-run/headers.png
  docs/recipes/img/cloud-run/hello-direct.png
  docs/recipes/img/cloud-run/hello-signin.png
  docs/recipes/img/cloud-run/hello-success.png
  docs/recipes/readme.md
  examples/cloudrun/README.md
  examples/cloudrun/config.yaml
  examples/cloudrun/deploy.sh
  examples/cloudrun/policy.template.yaml
  examples/cloudrun/zonefile.txt
Labels: docs

#1076 deps: update envoy to 1.14.4
  scripts/embed-envoy.bash
Labels: backport 0-9-0, bug, dependency

#1119 depedency: bump envoy to 1.15.0
  scripts/embed-envoy.bash
Labels: dependency

#1128 docs: Fix incorrect example middleware
  examples/traefik/docker-compose.yaml
Labels: docs

#1132 envoy: Set ExtAuthz Cluster name to URL Host
  internal/controlplane/xds_clusters.go
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
Labels: backport 0-9-0, improvement

#1152 docs: Add kubectl config commands
  docs/recipes/kubernetes.md
Labels: docs

#1153 handle example.com and example.com:443
  go.sum
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  internal/controlplane/xds_routes.go
Labels: backport 0-9-0

#1143 docs: Add recipe for TiddlyWiki on Node.js
  docs/.vuepress/config.js
  docs/recipes/readme.md
  docs/recipes/tiddlywiki.md
  examples/tiddlywiki/REAME.md
  examples/tiddlywiki/config.yaml
  examples/tiddlywiki/docker-compose.yaml
Labels: docs

#1177 deployment: cut separate archive for cli
  .github/goreleaser.yaml
Labels: deployment
