Repository pomerium/pomerium, pull requests merged in 2021-04, with the labels that each got.

#2048 authenticate: validate signature on /.pomerium, /.pomerium/sign_in and /.pomerium/sign_out
  authenticate/handlers.go
  authenticate/handlers_test.go
  authenticate/middleware.go
  internal/frontend/assets/html/userInfo.html
  proxy/handlers.go
  proxy/state.go
Labels: security

#2049 proxy: restrict programmatic URLs to localhost
  config/options.go
  config/options_test.go
  docs/docs/topics/programmatic-access.md
  docs/docs/upgrading.md
  docs/reference/readme.md
  docs/reference/settings.yaml
  integration/internal/flows/flows.go
  internal/urlutil/whitelist.go
  internal/urlutil/whitelist_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/state.go
Labels: security

#2050 authorize: audit logging
  authorize/grpc.go
  authorize/log.go
  authorize/state.go
  config/crypt.go
  config/options.go
  pkg/cryptutil/kek.go
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/audit/audit.proto
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  pkg/grpc/crypt/crypt.go
  pkg/grpc/crypt/crypt.pb.go
  pkg/grpc/crypt/crypt.proto
  pkg/grpc/crypt/crypt_test.go
  pkg/grpc/protoc.bash
  pkg/protoutil/any.go
  pkg/protoutil/crypt.go
  pkg/protoutil/crypt_test.go
Labels: improvement

#2059 authorize: additional tracing, add benchmark for encryptor
  authorize/log.go
  pkg/protoutil/crypt_test.go
Labels: improvement

#2061 authenticate: fix default sign out url
  authenticate/handlers.go
  proxy/handlers.go
Labels: bug

#2063 docs: update community slack link
  docs/docs/community/readme.md
Labels: backport 0-13-0, docs

#2062 databroker: remove unused installation id, close streams when backend is closed
  databroker/databroker.go
  internal/databroker/config.go
  pkg/storage/inmemory/stream.go
  pkg/storage/redis/stream.go
Labels: bug

#2066 cryptutil: always use kek public id, add x509 support
  config/crypt.go
  pkg/cryptutil/kek.go
  pkg/cryptutil/kek_test.go
  pkg/cryptutil/x509.go
  pkg/cryptutil/x509_test.go
Labels: improvement

#2067 cryptutil: use bytes for hmac
  authenticate/handlers.go
  authenticate/handlers_test.go
  authenticate/middleware.go
  authorize/check_response.go
  internal/httputil/reproxy/reproxy.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
  internal/urlutil/signed.go
  internal/urlutil/signed_test.go
  pkg/cryptutil/hmac.go
  pkg/cryptutil/hmac_test.go
  proxy/state.go
Labels: improvement

#2068 directory: remove provider from user id
  internal/directory/auth0/auth0.go
  internal/directory/auth0/auth0_test.go
  internal/directory/azure/azure.go
  internal/directory/azure/azure_test.go
  internal/directory/azure/delta.go
  internal/directory/github/github.go
  internal/directory/github/github_test.go
  internal/directory/gitlab/gitlab.go
  internal/directory/gitlab/gitlab_test.go
  internal/directory/google/google.go
  internal/directory/google/google_test.go
  internal/directory/okta/okta.go
  internal/directory/okta/okta_test.go
  internal/directory/onelogin/onelogin.go
  internal/directory/onelogin/onelogin_test.go
  internal/sessions/state.go
  pkg/grpc/databroker/databroker.go
  pkg/storage/redis/redis.go
Labels: improvement

#2069 deps: switch from renovate to dependabot
  .github/dependabot.yaml
  renovate.json
Labels: dependency

#2075 crypto: use actual bytes of shared secret, not the base64 encoded representation
  authenticate/handlers.go
  authenticate/middleware.go
  authenticate/state.go
  authorize/check_response.go
  authorize/state.go
  internal/middleware/middleware.go
  proxy/state.go
Labels: improvement

#2077 config: use tls_custom_ca from policy when available
  config/http.go
  config/http_test.go
Labels: bug

#2079 propagate changes back from encrypted backend
  pkg/storage/encrypted.go
  pkg/storage/encrypted_test.go
Labels: bug

#2086 envoy: refactor controlplane xds to new envoyconfig package
  config/envoyconfig/builder.go
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/envoyconfig.go
  config/envoyconfig/filemgr/config.go
  config/envoyconfig/filemgr/filemgr.go
  config/envoyconfig/filemgr/filemgr_test.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/lua.go
  config/envoyconfig/lua_test.go
  config/envoyconfig/luascripts/clean-upstream.lua
  config/envoyconfig/luascripts/ext-authz-set-cookie.lua
  config/envoyconfig/luascripts/fix-misdirected.lua
  config/envoyconfig/luascripts/remove-impersonate-headers.lua
  config/envoyconfig/luascripts/rewrite-headers.lua
  config/envoyconfig/protocols.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/envoyconfig/tracing.go
  internal/controlplane/constants.go
  internal/controlplane/server.go
  internal/controlplane/xds.go
Labels: improvement

#2087 metrics_address should be optional parameter
  internal/registry/constants.go
  internal/registry/reporter.go
Labels: bug

#2088 envoyconfig: move most bootstrap config to shared package
  config/envoyconfig/bootstrap.go
  config/envoyconfig/bootstrap_test.go
  config/envoyconfig/envoyconfig.go
  internal/cmd/pomerium/pomerium.go
  internal/controlplane/server.go
  internal/controlplane/xds.go
  internal/envoy/envoy.go
  internal/envoy/envoy_test.go
  internal/testutil/testutil.go
Labels: improvement

#2093 xdsmgr: update resource versions on NACK
  internal/controlplane/xdsmgr/xdsmgr.go
Labels: bug

#2092 config: don't change address value on databroker or authorize
  config/options.go
Labels: bug

#2096 deps: upgrade envoy to 1.16.3
  scripts/embed-envoy.bash
Labels: dependency, security

#2097 docs: add threat model to security page
  docs/docs/community/security.md
Labels: backport 0-13-0, docs

#2102 authorize: support arbitrary jwt claims
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa_test.go
Labels: bug

#2105 deployment: Publish OS packages to cloudsmith
  .github/workflows/release.yaml
  docs/docs/installation.md
Labels: backport 0-14-0, deployment

#2111 deployment: update get-envoy script and release hooks
  .github/goreleaser.yaml
  scripts/get-envoy.bash
Labels: backport 0-14-0, deployment

#2115 Drop tun.cfg.dstHost from jwtCacheKey
  internal/tcptunnel/tcptunnel.go
Labels: improvement

#2109 config: remove validate side effects
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/state.go
  authorize/authorize.go
  authorize/evaluator/evaluator.go
  authorize/state.go
  config/envoyconfig/listeners.go
  config/options.go
  config/options_test.go
  databroker/cache.go
  databroker/databroker.go
  internal/autocert/manager.go
  internal/databroker/config.go
  internal/databroker/config_source.go
  internal/httputil/reproxy/reproxy.go
  internal/registry/reporter.go
  proxy/proxy.go
  proxy/proxy_test.go
  proxy/state.go
Labels: improvement

#2118 authorize: fix unsigned URL
  authorize/check_response.go
Labels: bug

#2119 authorize: fix empty sub policy arrays
  authorize/evaluator/evaluator.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa_test.go
Labels: backport 0-14-0, bug

#2123 envoy: re-implement recommended defaults
  config/envoyconfig/clusters_test.go
  config/envoyconfig/envoyconfig.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/protocols.go
Labels: improvement

#2124 envoyconfig: fix metrics ingress listener name
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  internal/controlplane/xdsmgr/xdsmgr.go
Labels: bug

#2132 use cached envoy
  scripts/get-envoy.bash
Labels: dependency

#2134 httputil: fix SPDY support with reverse proxy
  config/http.go
  config/http_test.go
  internal/httputil/headers.go
  internal/httputil/reproxy/reproxy.go
Labels: bug

#2095 databroker: add options for maximum capacity
  config/options.go
  databroker/databroker.go
  internal/databroker/server.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/databroker/databroker.proto
  pkg/storage/encrypted.go
  pkg/storage/inmemory/backend.go
  pkg/storage/inmemory/backend_test.go
  pkg/storage/inmemory/record_collection.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: improvement

#2133 docs: upgrade notes on `allowed_users` by ID
  docs/docs/upgrading.md
Labels: backport 0-14-0, docs

#2141 authorize: audit log had duplicate "message" key
  authorize/log.go
Labels: backport 0-14-0, bug

#2144 let pass custom dial opts
  pkg/grpc/client.go
Labels: improvement

#2142 databroker: store server version in backend
  internal/databroker/server.go
  internal/databroker/server_test.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/databroker/databroker.proto
  pkg/grpc/databroker/syncer_test.go
  pkg/storage/encrypted.go
  pkg/storage/encrypted_test.go
  pkg/storage/inmemory/backend.go
  pkg/storage/inmemory/backend_test.go
  pkg/storage/inmemory/stream.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
  pkg/storage/redis/stream.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: bug

#2149 control plane: add request id to all error pages
  authorize/check_response.go
  authorize/check_response_test.go
  authorize/grpc.go
  internal/frontend/assets/html/error.go.html
  internal/httputil/errors.go
  internal/httputil/handlers.go
  internal/httputil/httputil.go
Labels: improvement

#2151 authorize: refactor store locking
  authorize/authorize.go
  authorize/evaluator/store.go
  authorize/grpc.go
  authorize/sync.go
  pkg/grpc/databroker/syncer.go
Labels: bug

#2154 deployment: update alpine debug image dependencies
  Dockerfile.debug
Labels: bug, deployment

#2155 docs: mention alternative bearer token header format
  docs/docs/topics/programmatic-access.md
Labels: docs

#2153 controlplane: save configuration events to databroker
  authenticate/state.go
  authorize/state.go
  internal/controlplane/events.go
  internal/controlplane/events_test.go
  internal/controlplane/server.go
  internal/controlplane/xdsmgr/xdsmgr.go
  internal/controlplane/xdsmgr/xdsmgr_test.go
  internal/databroker/config_source.go
  internal/registry/reporter.go
  pkg/grpc/client.go
  pkg/grpc/client_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: improvement

#2160 internal/envoy: always extract envoy
  internal/envoy/embed.go
  internal/envoy/envoy.go
Labels: security

#2161 ci: remove codecov
  .github/workflows/test.yaml
  README.md
Labels: security

#2157 config: add client_crl
  config/config_source.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/options.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  internal/controlplane/xds.go
  pkg/cryptutil/certificates.go
  pkg/cryptutil/certificates_test.go
  pkg/cryptutil/testdata/example-crl.pem
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: improvement

#2162 docs: add info note to set_response_headers
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: docs
