Repository pomerium/pomerium, pull requests merged in 2021-07, with the labels that each got.

#2319 proxy: add idle timeout
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/policy.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  internal/testutil/testutil.go
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  pkg/grpc/crypt/crypt.pb.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/directory/directory.pb.go
  pkg/grpc/events/xds.pb.go
  pkg/grpc/registry/registry.pb.go
  pkg/grpc/session/session.pb.go
  pkg/grpc/user/user.pb.go
  proxy/proxy_test.go
Labels: improvement

#2314 authorize: do not send redirects to gRPC
  authorize/check_response.go
Labels: improvement

#2331 chore(deps): upgrade kind action to v1.2.0
  .github/workflows/test.yaml
Labels: dependency

#2338 authorize: support boolean deny results
  authorize/evaluator/policy_evaluator.go
  authorize/evaluator/policy_evaluator_test.go
  pkg/policy/generator/generator_test.go
Labels: bug

#2337 registry/redis: call publish from within lua function
  internal/registry/redis/lua/registry.lua
  internal/registry/redis/redis.go
Labels: improvement

#2341 fix: timeout in protobuf
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/policy.go
Labels: bug

#2343 envoyconfig: add bootstrap layered runtime configuration
  config/envoyconfig/bootstrap.go
  config/envoyconfig/bootstrap_test.go
  internal/envoy/envoy.go
Labels: improvement

#2340 Update installation source for mkcert
  docs/docs/topics/certificates.md
Labels: docs

#2344 tools: add tools.go to pin go run apps
  .github/workflows/test.yaml
  Makefile
  go.mod
  go.sum
  tools.go
Labels: improvement

#2316 cli: use proxy from environment
  internal/authclient/authclient.go
Labels: enhancement

#2346 Docs sorting
  docs/.vuepress/config.js
  docs/guides/readme.md
Labels: backport 0-14-0, docs

#2351 Docs backporting
  docs/.vuepress/config.js
  docs/docs/topics/certificates.md
  docs/guides/img/transmission-demo.png
  docs/guides/readme.md
  docs/guides/transmission.md
Labels: backport 0-14-0, docs

#2354 authorize: log service account and impersonation details
  authorize/grpc.go
  authorize/log.go
  authorize/sync.go
Labels: improvement

#2355 envoy: only check for pid with monitor
  internal/envoy/envoy.go
Labels: bug

#2359 envoyconfig: default zipkin path to / when empty
  config/envoyconfig/tracing.go
Labels: improvement

#2357 authorize: decode CheckRequest path for redirect
  authorize/grpc.go
Labels: bug

#2361 authorize: allow redirects on deny
  authorize/grpc.go
Labels: bug

#2365 authorize: remove service account impersonate user id, email and groups
  authorize/evaluator/evaluator_test.go
  authorize/log.go
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/crypt/crypt.pb.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/directory/directory.pb.go
  pkg/grpc/events/xds.pb.go
  pkg/grpc/registry/registry.pb.go
  pkg/grpc/session/session.pb.go
  pkg/grpc/user/user.pb.go
  pkg/grpc/user/user.proto
Labels: improvement

#2370 ci: use revive instead of golint
  .golangci.yml
  internal/directory/azure/delta.go
Labels: improvement

#2371 ci: convert to FOSSA scan
  .fossa.yml
  .github/workflows/test.yaml
  lichen.yaml
Labels: dependencies, deployment

#2376 telemetry: support b3 headers on gRPC server calls
  internal/envoy/envoy.go
  internal/telemetry/grpc.go
  internal/telemetry/grpc_test.go
Labels: bug

#2379 k8s: add flush-credentials command
  cmd/pomerium-cli/cache.go
  cmd/pomerium-cli/kubernetes.go
Labels: improvement

#2380 Helm Quickstart Update
  docs/docs/quick-start/helm.md
  examples/helm/helm_gke.sh
  examples/kubernetes/values.yaml
Labels: docs

#2381 authorize: add additional tracing for rego evaluation
  authorize/evaluator/evaluator.go
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/policy_evaluator.go
Labels: improvement

#2384 evaluator: use `cryptutil.Hash` for script spans
  authorize/evaluator/policy_evaluator.go
Labels: backend, improvement

#2385 directory: add logging http client to help with debugging outbound http requests
  internal/databroker/server.go
  internal/directory/azure/azure.go
  internal/directory/github/github.go
  internal/directory/gitlab/gitlab.go
  internal/directory/google/google.go
  internal/directory/okta/okta.go
  internal/directory/onelogin/onelogin.go
  internal/directory/ping/config.go
  internal/httputil/client.go
  internal/httputil/client_test.go
  internal/identity/oauth/github/github.go
  internal/identity/oidc/oidc.go
  pkg/grpc/databroker/leaser.go
Labels: improvement

#2391 google: remove WithHTTPClient
  internal/directory/google/google.go
Labels: bug

#2393 ci: update gcloud action
  .github/workflows/release.yaml
Labels: bug

#2396 symlink security policy to root of project
  SECURITY.md
  docs/docs/community/security.md
Labels: docs

#2397 Enterprise settings docs
  docs/.vuepress/config.js
  docs/enterprise/console-settings.yaml
  docs/enterprise/img/example-policy-editor.png
  docs/enterprise/img/example-policy-single-user.png
  docs/enterprise/reference.md
  scripts/generate-console-settings-docs.py
Labels: docs

#2399 disable http/2 for websockets
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/protocols.go
Labels: bug

#2400 ppl: remove support for aliases
  config/policy_ppl.go
  pkg/policy/criteria/accept.go
  pkg/policy/criteria/authenticated_user.go
  pkg/policy/criteria/claims.go
  pkg/policy/criteria/cors_preflight.go
  pkg/policy/criteria/domains.go
  pkg/policy/criteria/emails.go
  pkg/policy/criteria/groups.go
  pkg/policy/criteria/invalid_client_certificate.go
  pkg/policy/criteria/pomerium_routes.go
  pkg/policy/criteria/reject.go
  pkg/policy/criteria/users.go
  pkg/policy/generator/criterion.go
  pkg/policy/generator/generator.go
  pkg/policy/generator/generator_test.go
Labels: improvement

#2401 config: add support for embedded PPL policy
  config/constants.go
  config/custom.go
  config/custom_test.go
  config/options.go
  config/policy.go
  config/policy_ppl.go
  config/policy_ppl_test.go
  internal/httputil/reproxy/reproxy.go
Labels: improvement

#2402 envoyconfig: improvements
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/protocols.go
Labels: improvement

#2406 Installation Docs Restructuring
  docs/.vuepress/config.js
  docs/.vuepress/public/_redirects
  docs/docs/CHANGELOG.md
  docs/docs/install/binary.md
  docs/docs/install/from-source.md
  docs/docs/install/helm.md
  docs/docs/install/img/kubernetes-gke.png
  docs/docs/install/img/logged-in-as.png
  docs/docs/install/readme.md
  docs/docs/releases.md
  docs/docs/topics/production-deployment.md
  docs/guides/ad-guard.md
  docs/guides/code-server.md
  docs/guides/img/synology-certifciate-assignment.png
  docs/guides/img/synology-docker-httpbin.png
  docs/guides/img/synology-docker-package-center.png
  docs/guides/img/synology-docker-pomerium-alias.png
  docs/guides/img/synology-docker-pomerium-create-container.png
  docs/guides/img/synology-docker-pomerium-done.png
  docs/guides/img/synology-docker-pomerium-package.png
  docs/guides/img/synology-docker-port-settings.png
  docs/guides/img/synology-firewall-rules.png
  docs/guides/img/synology-httpbin.png
  docs/guides/img/synology-reverse-proxy-rules.png
  docs/guides/img/synology-reverse-proxy.png
  docs/guides/img/synology-step-1-redirect.png
  docs/guides/img/synology-step-2-mfa.png
  docs/guides/img/synology-step-3-validate-header.png
  docs/guides/img/synology-step-4-unauthorized.png
  docs/guides/img/synology-step-4-unauthorized.png2
  docs/guides/readme.md
  docs/guides/synology.md
Labels: docs

#2405 docs: concepts (suggestions on #2390)
  docs/.vuepress/config.js
  docs/enterprise/about.md
  docs/enterprise/concepts.md
  docs/enterprise/img/console-route-traffic.png
  docs/enterprise/img/console-session-landing.png
  docs/enterprise/img/console-session-list.png
  docs/enterprise/img/example-policy-editor.png
  docs/enterprise/img/example-policy-single-user.png
  scripts/generate-console-pages.js
  scripts/generate-console-settings-docs.py
Labels: docs

#2392 envoy: bump to 1.19
  scripts/get-envoy.bash
Labels: dependency

#2408 docs: only secure schemes are supported
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: backport 0-14-0, docs

#2407 sessions: add impersonate_session_id, remove legacy impersonation
  authenticate/handlers.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
  authorize/log.go
  config/policy_ppl_test.go
  internal/frontend/assets/html/userInfo.html
  pkg/grpc/session/session.pb.go
  pkg/grpc/session/session.proto
  pkg/policy/criteria/domains_test.go
  pkg/policy/criteria/emails_test.go
  pkg/policy/rules/rules.go
Labels: improvement
