Repository pomerium/pomerium, pull requests merged in 2021-06, with the labels that each got.

#2256 config: warn about unrecognized keys
  config/options.go
  docs/docs/topics/load-balancing.md
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: bug

#2247 authorize: preserve original context
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  config/envoyconfig/routes.go
  internal/httputil/headers.go
Labels: enhancement

#2259 envoy: disable hot-reload for macos
  internal/envoy/envoy.go
  internal/envoy/envoy_darwin.go
  internal/envoy/envoy_linux.go
  internal/envoy/envoy_other.go
  internal/envoy/misc.go
Labels: bug

#2258 authorize: round timestamp
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
Labels: bug

#2262 tracing: support dynamic reloading, more aggressive envoy restart
  config/trace.go
  internal/envoy/envoy_linux.go
  internal/telemetry/trace/datadog.go
  internal/telemetry/trace/jaeger.go
  internal/telemetry/trace/trace.go
  internal/telemetry/trace/trace_test.go
  internal/telemetry/trace/zipkin.go
Labels: bug

#2264 authorize: only redirect for HTML pages
  authorize/check_response.go
  authorize/check_response_test.go
  authorize/grpc.go
  go.mod
  go.sum
Labels: bug

#2265 envoyconfig: use zipkin tracer
  config/envoyconfig/bootstrap.go
  config/envoyconfig/bootstrap_test.go
  config/envoyconfig/clusters.go
  config/envoyconfig/listeners.go
  config/envoyconfig/tracing.go
  config/envoyconfig/tracing_test.go
  internal/envoy/envoy.go
Labels: improvement

#2266 xds: retry storing configuration events
  internal/controlplane/events.go
Labels: improvement

#2267 redis: enforce capacity via ZREVRANGE to avoid race
  pkg/storage/redis/redis.go
Labels: bug

#2268 authorize: handle grpc-web content types like json
  authorize/check_response.go
Labels: improvement

#2261 envoy: always set jwt claim headers even if no value is available
  authorize/evaluator/opa/policy/headers.rego
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
Labels: bug

#2269 databroker: only tag contexts used for UpdateRecords
  internal/contextkeys/contextkeys.go
  internal/controlplane/xdsmgr/xdsmgr.go
  pkg/grpc/databroker/syncer.go
Labels: bug

#2277 envoy: fix usage of codec_type with alpn
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
Labels: backport 0-14-0, bug

#2272 docs: google gcp / workspace instructions
  docs/docs/identity-providers/google.md
  docs/docs/identity-providers/img/google-consent-banner.png
  docs/docs/identity-providers/img/google-create-client-id-config.png
  docs/docs/identity-providers/img/google-create-new-credentials.png
  docs/docs/identity-providers/img/google-create-sa.png
  docs/docs/identity-providers/img/google-credentials.png
  docs/docs/identity-providers/img/google-gsuite-add-scopes.png
  docs/docs/identity-providers/img/google-oauth-client-info.png
  docs/docs/identity-providers/img/google-oauth-consent.png
  docs/docs/identity-providers/img/google/google-create-client-id-config.png
  docs/docs/identity-providers/img/google/google-credentials.png
  docs/docs/identity-providers/img/google/google-gsuite-add-scopes.png
Labels: docs

#2284 deps: upgrade to go-jose v3
  authenticate/handlers.go
  authenticate/handlers_test.go
  authenticate/state.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/policy_evaluator_test.go
  authorize/evaluator/store.go
  cmd/pomerium-cli/kubernetes.go
  go.mod
  go.sum
  internal/cliutil/jwtcache.go
  internal/cliutil/jwtcache_test.go
  internal/encoding/jws/jws.go
  internal/identity/oauth/github/github.go
  internal/sessions/cookie/middleware_test.go
  internal/sessions/header/middleware_test.go
  internal/sessions/middleware_test.go
  internal/sessions/queryparam/middleware_test.go
  internal/sessions/state.go
  internal/sessions/state_test.go
  pkg/cryptutil/jose.go
  pkg/cryptutil/jose_test.go
  pkg/grpcutil/options.go
  proxy/forward_auth_test.go
  proxy/handlers_test.go
Labels: dependencies

#2286 ocsp: reload on response changes
  internal/autocert/manager.go
  internal/autocert/manager_test.go
  internal/autocert/ocsp.go
  internal/autocert/ocsp_test.go
Labels: bug

#2281 Transmission BitTorrent Client Guide
  docs/.vuepress/config.js
  docs/guides/img/transmission-demo.png
  docs/guides/readme.md
  docs/guides/transmission.md
Labels: docs

#2285 Update kubernetes-dashboard.md
  docs/guides/kubernetes-dashboard.md
Labels: docs

#2287 envoy: add full version
  .gitignore
  Makefile
  cmd/pomerium-cli/version.go
  cmd/pomerium/main.go
  databroker/cache.go
  internal/cmd/pomerium/pomerium.go
  internal/controlplane/server.go
  internal/envoy/embed.go
  internal/envoy/envoy.go
  internal/envoy/files/files.go
  internal/telemetry/metrics/info_test.go
  internal/telemetry/metrics/registry.go
  pkg/grpcutil/version.go
  pkg/metrics/constants.go
  scripts/get-envoy.bash
Labels: improvement

#2296 envoy: refactor envoy embedding
  .github/goreleaser.yaml
  Makefile
  config/envoyconfig/filemgr/filemgr.go
  go.mod
  go.sum
  internal/cmd/pomerium/pomerium_test.go
  internal/envoy/embed.go
  internal/envoy/envoy.go
  internal/envoy/envoy_linux.go
  internal/envoy/files/files.go
  internal/envoy/files/files_darwin.go
  internal/envoy/files/files_linux_amd64.go
  internal/envoy/files/files_linux_arm64.go
  scripts/embed-envoy.bash
  scripts/get-envoy.bash
Labels: improvement

#2311 directory/azure: add paging support to user group members call
  internal/directory/azure/api.go
  internal/directory/azure/azure.go
  internal/directory/azure/azure_test.go
  internal/directory/azure/delta.go
Labels: backport 0-14-0, bug

#2309 certs: reject certs from databroker if they conflict with local
  config/certs.go
  config/certs_test.go
  config/options.go
  internal/databroker/config_source.go
  pkg/cryptutil/certificates.go
Labels: improvement

#2313 ppl: fix not/nor rules
  pkg/policy/generator/conditionals.go
  pkg/policy/generator/generator.go
  pkg/policy/generator/generator_test.go
Labels: bug
