Repository pomerium/pomerium, pull requests merged in 2021-05, with the labels that each got.

#2164 docs: add inline instructions to generate signing-key
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: backport 0-13-0, backport 0-14-0, docs

#2158 xds extended event
  internal/contextkeys/contextkeys.go
  internal/controlplane/events.go
  internal/controlplane/events_test.go
  internal/controlplane/server.go
  internal/controlplane/xdsmgr/xdsmgr.go
  internal/controlplane/xdsmgr/xdsmgr_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  pkg/grpc/databroker/syncer.go
  pkg/grpc/events/xds.pb.go
  pkg/grpc/events/xds.proto
  pkg/grpc/protoc.bash
Labels: improvement

#2171 config: add support for set_response_headers in a policy
  config/envoyconfig/routes.go
  config/policy.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: improvement

#2173 databroker: store issued at timestamp with session
  authenticate/handlers.go
  internal/identity/manager/misc.go
  pkg/grpc/session/session.go
  pkg/grpc/session/session.pb.go
  pkg/grpc/session/session.proto
Labels: improvement

#2174 docs: v0.14.0
  docs/.vuepress/config.js
  docs/docs/CHANGELOG.md
Labels: docs

#2175 report instance hostname in xds events
  internal/controlplane/xdsmgr/xdsmgr.go
Labels: improvement

#2177 docs: update slack link to vanity url
  docs/docs/community/readme.md
Labels: backport 0-14-0, docs

#2183 docs: add v0.14 feature highlights
  docs/docs/topics/data-storage.md
  docs/docs/upgrading.md
Labels: backport 0-14-0, docs

#2172 databroker: implement leases
  databroker/databroker.go
  internal/databroker/server.go
  internal/identity/manager/manager.go
  pkg/grpc/databroker/databroker.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/databroker/databroker.proto
  pkg/grpc/databroker/leaser.go
  pkg/grpc/databroker/leaser_test.go
  pkg/grpc/databroker/mock_databroker/databroker.pb.go
  pkg/grpc/databroker/mock_databroker/leaser.go
  pkg/storage/encrypted.go
  pkg/storage/inmemory/backend.go
  pkg/storage/inmemory/backend_test.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
  pkg/storage/storage.go
Labels: improvement

#2189 envoy: disable timeouts for kubernetes
  config/envoyconfig/routes.go
Labels: improvement

#2193 deployment: fix empty version on master builds
  Makefile
Labels: bug, deployment

#2196 proxy / controplane: use old upstream cipher suite
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  docs/docs/community/security.md
Labels: backport 0-14-0, bug

#2198 deps: bump envoy to v1.17.3
  scripts/get-envoy.bash
Labels: backport 0-14-0, dependency, security

#2200 authorize: grpc health check
  config/envoyconfig/clusters.go
  internal/controlplane/server.go
  pkg/grpc/health.go
Labels: bug

#2203 Revert "authenticate,proxy: add same site lax to cookies"
  authenticate/state.go
  internal/sessions/cookie/cookie_store.go
  proxy/state.go
Labels: backport 0-14-0, bug

#2190 Update programmatic-access.md
  docs/docs/topics/programmatic-access.md
Labels: backport 0-14-0, docs

#2202 Pomerium Policy Language
  pkg/policy/criteria/accept.go
  pkg/policy/criteria/accept_test.go
  pkg/policy/criteria/authenticated_user.go
  pkg/policy/criteria/authenticated_user_test.go
  pkg/policy/criteria/claims.go
  pkg/policy/criteria/claims_test.go
  pkg/policy/criteria/cors_preflight.go
  pkg/policy/criteria/cors_preflight_test.go
  pkg/policy/criteria/criteria.go
  pkg/policy/criteria/criteria_test.go
  pkg/policy/criteria/domains.go
  pkg/policy/criteria/domains_test.go
  pkg/policy/criteria/emails.go
  pkg/policy/criteria/emails_test.go
  pkg/policy/criteria/groups.go
  pkg/policy/criteria/groups_test.go
  pkg/policy/criteria/invalid_client_certificate.go
  pkg/policy/criteria/pomerium_routes.go
  pkg/policy/criteria/reject.go
  pkg/policy/criteria/reject_test.go
  pkg/policy/criteria/users.go
  pkg/policy/generator/conditionals.go
  pkg/policy/generator/criterion.go
  pkg/policy/generator/generator.go
  pkg/policy/generator/generator_test.go
  pkg/policy/parser/grammar.go
  pkg/policy/parser/json.go
  pkg/policy/parser/json_test.go
  pkg/policy/parser/parser.go
  pkg/policy/parser/parser_test.go
  pkg/policy/parser/schema.json
  pkg/policy/policy.go
  pkg/policy/rules/rules.go
Labels: improvement

#2213 PPL: bubble up values, bug fixes
  pkg/policy/criteria/domains.go
  pkg/policy/criteria/emails.go
  pkg/policy/criteria/groups.go
  pkg/policy/criteria/users.go
  pkg/policy/generator/conditionals.go
  pkg/policy/generator/generator.go
  pkg/policy/generator/generator_test.go
  pkg/policy/parser/json.go
  pkg/policy/policy.go
  pkg/policy/rules/rules.go
Labels: bug

#2218 ppl: convert config policy to ppl
  config/policy.go
  config/policy_ppl.go
  config/policy_ppl_test.go
Labels: improvement

#2217 envoy: add global response headers to local replies
  config/envoyconfig/http_connection_manager.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
Labels: backport 0-14-0, bug

#2227 depedency: update /x/net
  go.mod
  go.sum
Labels: backport 0-14-0, dependencies

#2223 fix(docs): use correct name for code-server
  docs/.vuepress/config.js
  docs/.vuepress/public/_redirects
  docs/guides/code-server.md
Labels: docs

#2215 docs: rm broken link
  docs/docs/architecture.md
Labels: docs

#2226 authorize: fix custom rego panic
  authorize/evaluator/custom.go
  authorize/evaluator/custom_test.go
  authorize/evaluator/evaluator.go
Labels: bug

#2224 ppl: refactor authorize to evaluate PPL
  Makefile
  authorize/authorize.go
  authorize/check_response.go
  authorize/check_response_test.go
  authorize/evaluator/config.go
  authorize/evaluator/custom.go
  authorize/evaluator/custom_test.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/functions.go
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/opa.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/authz_test.rego
  authorize/evaluator/opa/policy/headers.rego
  authorize/evaluator/opa_test.go
  authorize/evaluator/policy_evaluator.go
  authorize/evaluator/policy_evaluator_test.go
  authorize/evaluator/request.go
  authorize/evaluator/result.go
  authorize/evaluator/store.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/log.go
  go.sum
Labels: improvement

#2229 add support for latest version of code-server
  docs/guides/code-server.md
  docs/guides/img/vscode-pomerium.png
Labels: docs

#2228 ppl: add data type, implement string and list matchers
  config/policy_ppl.go
  config/policy_ppl_test.go
  pkg/policy/criteria/accept.go
  pkg/policy/criteria/authenticated_user.go
  pkg/policy/criteria/claims.go
  pkg/policy/criteria/cors_preflight.go
  pkg/policy/criteria/criteria.go
  pkg/policy/criteria/domains.go
  pkg/policy/criteria/domains_test.go
  pkg/policy/criteria/emails.go
  pkg/policy/criteria/emails_test.go
  pkg/policy/criteria/groups.go
  pkg/policy/criteria/groups_test.go
  pkg/policy/criteria/invalid_client_certificate.go
  pkg/policy/criteria/matchers.go
  pkg/policy/criteria/matchers_test.go
  pkg/policy/criteria/pomerium_routes.go
  pkg/policy/criteria/reject.go
  pkg/policy/criteria/users.go
  pkg/policy/generator/criterion.go
  pkg/policy/generator/generator_test.go
Labels: improvement

#2236 authorize: add rego functions to custom evaluator
  authorize/evaluator/custom.go
Labels: bug

#2237 docs: update _redirects
  docs/.vuepress/public/_redirects
Labels: backport 0-14-0, docs

#2240 envoy: exit if envoy exits
  go.mod
  go.sum
  internal/envoy/envoy.go
  internal/envoy/envoy_darwin.go
  internal/envoy/envoy_linux.go
  internal/envoy/envoy_notlinux.go
  internal/envoy/envoy_other.go
Labels: bug

#2243 policy: fix allowed idp claims PPL generation
  config/policy_ppl.go
  config/policy_ppl_test.go
Labels: bug

#2242 docs: update helm values for chart v20.0.0
  examples/helm/helm_gke.sh
  examples/kubernetes/values.yaml
Labels: backport 0-14-0, docs

#2235 envoyconfig: fallback to global custom ca when no policy ca is defined
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/envoyconfig.go
Labels: bug

#2245 darwin: use gopsutil v3 to fix arm issue
  Makefile
  go.mod
  go.sum
  internal/envoy/envoy.go
Labels: bug

#2216 forward auth: don't strip query parameters
  internal/urlutil/url.go
  internal/urlutil/url_test.go
  proxy/forward_auth.go
Labels: bug

#2246 darwin: use x86 envoy build for arm64
  .github/goreleaser.yaml
  internal/envoy/envoy.go
  scripts/get-envoy.bash
Labels: dependencies

#2257 options: s/shared-key/shared secret
  config/options.go
Labels: bug, docs
