Repository pomerium/pomerium, pull requests merged in 2021-03, with the labels that each got.

#1958 cmd/pomerium: exit 0 for normal shutdown
  cmd/pomerium/main.go
Labels: bug

#1957 config: multiple endpoints for authorize and databroker
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/state.go
  authorize/authorize.go
  authorize/authorize_test.go
  authorize/grpc_test.go
  authorize/state.go
  config/options.go
  config/options_test.go
  databroker/cache.go
  databroker/cache_test.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  internal/controlplane/constants.go
  internal/controlplane/xds_clusters.go
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  internal/databroker/config_source.go
  internal/databroker/config_source_test.go
  internal/registry/reporter.go
  pkg/grpc/client.go
  pkg/grpc/client_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: improvement

#1959 config: log config source changes
  authenticate/authenticate.go
  authorize/authorize.go
  config/config.go
  config/config_source.go
  config/options.go
  internal/databroker/config_source.go
  internal/telemetry/metrics/info.go
  internal/telemetry/metrics/info_test.go
  internal/telemetry/metrics/registry.go
  pkg/metrics/constants.go
  proxy/proxy.go
Labels: improvement

#1948 telemetry: add process collector for envoy
  go.mod
  internal/envoy/envoy.go
  internal/telemetry/metrics/processes.go
  internal/telemetry/metrics/processes_test.go
Labels: improvement

#1960 assets: use embed instead of statik
  .gitattributes
  .github/workflows/test.yaml
  Makefile
  authorize/evaluator/evaluator.go
  authorize/evaluator/functions.go
  authorize/evaluator/opa/opa.go
  authorize/evaluator/opa/policy/statik.go
  authorize/evaluator/opa_test.go
  go.mod
  go.sum
  internal/controlplane/luascripts/statik.go
  internal/controlplane/xds_lua.go
  internal/frontend/statik/statik.go
  internal/frontend/templates.go
  internal/frontend/templates_test.go
Labels: improvement

#1961 config: add rewrite_response_headers option
  config/policy.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  go.mod
  go.sum
  internal/controlplane/luascripts/rewrite-headers.lua
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  internal/controlplane/xds_lua.go
  internal/controlplane/xds_lua_test.go
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
Labels: improvement

#1962 config: add rewrite_response_headers to protobuf
  config/policy.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: improvement

#1974 docs: add JWT Verification w/Envoy guide
  docs/.vuepress/config.js
  docs/guides/jwt-verification.md
  docs/guides/readme.md
Labels: docs

#1975 ping: identity and directory providers
  internal/directory/ping/api.go
  internal/directory/ping/config.go
  internal/directory/ping/provider.go
  internal/directory/ping/provider_test.go
  internal/directory/provider.go
  internal/identity/oidc/ping/ping.go
  internal/identity/providers.go
Labels: improvement

#1977 identity: infer email from mail claim
  internal/identity/oidc/userinfo.go
  internal/identity/oidc/userinfo_test.go
Labels: backport 0-13-0, improvement

#1976 ping: add documentation
  docs/.vuepress/config.js
  docs/docs/identity-providers/img/ping-add-application.png
  docs/docs/identity-providers/img/ping-add-worker.png
  docs/docs/identity-providers/img/ping-configuration.png
  docs/docs/identity-providers/img/ping-worker-configuration.png
  docs/docs/identity-providers/ping.md
Labels: docs

#1980 authorize: set JWT to expire after 5 minutes
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa_test.go
Labels: improvement

#1979 Fix process cpu usage metric
  internal/telemetry/metrics/processes.go
Labels: bug

#1991 redis: add support for redis-sentinel
  go.sum
  internal/testutil/redis.go
  pkg/storage/redis/client.go
  pkg/storage/redis/client_test.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
Labels: improvement

#1992 redis: add redis cluster support
  docs/reference/readme.md
  docs/reference/settings.yaml
  go.mod
  go.sum
  internal/testutil/redis.go
  pkg/storage/redis/client.go
  pkg/storage/redis/client_test.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
Labels: improvement

#1993 envoy: upgrade to v1.17.1
  authorize/check_response.go
  authorize/check_response_test.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/session_test.go
  go.mod
  go.sum
  internal/cmd/pomerium/pomerium.go
  internal/controlplane/grpc_accesslog.go
  internal/controlplane/xds.go
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  internal/controlplane/xds_tracing.go
  internal/envoy/envoy.go
  internal/envoy/envoy_test.go
  scripts/get-envoy.bash
Labels: improvement

#1996 config: add headers to config proto
  config/options.go
  internal/controlplane/xds_protocols.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: bug

#2000 config: use getters for authenticate, signout and forward auth urls
  authenticate/authenticate.go
  authenticate/authenticate_test.go
  authenticate/handlers.go
  authenticate/handlers_test.go
  authenticate/state.go
  authorize/authorize.go
  authorize/authorize_test.go
  authorize/check_response_test.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/grpc.go
  authorize/grpc_test.go
  config/options.go
  config/options_test.go
  internal/autocert/manager.go
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
  proxy/handlers.go
  proxy/proxy.go
  proxy/proxy_test.go
  proxy/state.go
Labels: improvement

#1970 oidc: use groups claim from ID token if present
  authorize/evaluator/opa/policy/authz.rego
Labels: NeedsDiscussion

#1994 Update local-oidc.md
  docs/guides/local-oidc.md
Labels: docs

#2017 telemetry: add installation id
  authenticate/state.go
  authorize/state.go
  config/metrics.go
  config/options.go
  databroker/databroker.go
  go.mod
  internal/controlplane/http.go
  internal/databroker/config.go
  internal/httputil/client.go
  internal/registry/reporter.go
  internal/telemetry/http.go
  internal/telemetry/metrics/grpc.go
  internal/telemetry/metrics/http.go
  internal/telemetry/metrics/http_test.go
  internal/telemetry/metrics/info.go
  internal/telemetry/metrics/info_test.go
  internal/telemetry/metrics/providers.go
  internal/telemetry/metrics/providers_test.go
  internal/telemetry/metrics/registry.go
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/client.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/directory/directory.pb.go
  pkg/grpc/grpc.go
  pkg/grpc/protoc.bash
  pkg/grpc/registry/registry.pb.go
  pkg/grpc/registry/registry.proto
  pkg/grpc/session/session.pb.go
  pkg/grpc/user/user.pb.go
  pkg/metrics/constants.go
Labels: improvement

#2016 deps: bundle all patch upgrades in a single group
  renovate.json
Labels: dependency

#2019 autocert: add metrics for renewal count, total and next expiration
  internal/autocert/manager.go
  internal/telemetry/metrics/autocert.go
  internal/telemetry/metrics/registry.go
  pkg/metrics/constants.go
Labels: improvement

#2020 cryptutil: add envelope encryption w/key encryption key and data encryption key
  pkg/cryptutil/dek.go
  pkg/cryptutil/dek_test.go
  pkg/cryptutil/kek.go
  pkg/cryptutil/kek_test.go
Labels: improvement

#2023 protoutil: add generic transformer
  pkg/protoutil/transform.go
  pkg/protoutil/transform_test.go
Labels: improvement

#2039 databroker: return server version in Get
  internal/databroker/server.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/databroker/databroker.proto
Labels: improvement

#2042 support host:port in metrics_address
  config/options.go
  config/validate.go
  internal/controlplane/xds_listeners.go
  internal/registry/constants.go
  internal/registry/reporter.go
  internal/registry/reporter_test.go
Labels: improvement

#2045 skip REDIS cluster test if GOOS != linux
  pkg/storage/redis/redis_test.go
Labels: dependency

#2024 authorize: add databroker server and record version to result, force sync via polling
  authorize/check_response_test.go
  authorize/evaluator/custom_test.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa_test.go
  authorize/evaluator/result.go
  authorize/evaluator/store.go
  authorize/evaluator/store_test.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/sync.go
  authorize/sync_test.go
  internal/databroker/config_source.go
  internal/identity/manager/sync.go
  pkg/grpc/databroker/syncer.go
  pkg/grpc/databroker/syncer_test.go
Labels: improvement
