Repository pomerium/pomerium, pull requests merged in 2021-02, with the labels that each got.

#1835 policy: add new certificate-authority option for downstream mTLS client certificates
  authorize/evaluator/evaluator.go
  authorize/evaluator/request.go
  authorize/grpc.go
  authorize/grpc_test.go
  config/options.go
  config/policy.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  internal/httputil/headers.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  proxy/handlers.go
  proxy/handlers_test.go
Labels: improvement

#1844 xds: fix always requiring client certificates
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
Labels: bug

#1833 authorize: remove admin
  authenticate/authenticate_test.go
  authenticate/handlers.go
  authenticate/state.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/authz_test.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/evaluator/store.go
  authorize/evaluator/store_test.go
  config/options.go
  docs/docs/upgrading.md
  integration/control_plane_test.go
  internal/controlplane/xds_listeners_test.go
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: improvement

#1845 opa: format rego files
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/authz_test.rego
  authorize/evaluator/opa/policy/statik.go
Labels: improvement

#1591 Update GitLab provider docs
  docs/docs/identity-providers/gitlab.md
Labels: docs

#1848 deployment: set maintainer field in packages
  .github/goreleaser.yaml
Labels: backport 0-12-0, bug, deployment

#1847 authorize: remove DataBrokerData input
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/authz_test.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/evaluator/opa_test.go
Labels: improvement

#1851 config: fix data race
  config/config_source.go
Labels: bug

#1853 rego: handle null
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/evaluator/opa_test.go
Labels: bug

#1850 authorize: allow access by user id
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/evaluator/opa_test.go
  config/policy.go
  pkg/grpc/config/config.go
Labels: improvement

#1854 ci: enable backporting from forks
  .github/workflows/backport.yaml
Labels: backport 0-12-0

#1856 authorize: move headers and jwt signing to rego
  authorize/check_response.go
  authorize/check_response_test.go
  authorize/evaluator/custom.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/google_cloud_serverless.go
  authorize/evaluator/google_cloud_serverless_test.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/authz_test.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/evaluator/opa_test.go
  authorize/evaluator/request.go
  authorize/evaluator/store.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/session.go
  authorize/session_test.go
Labels: improvement

#1858 unique envoy cluster ids
  internal/controlplane/xds_cluster_test.go
  internal/controlplane/xds_clusters.go
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
Labels: backport 0-12-0, bug

#1862 options: header only applies to routes and authN
  docs/reference/readme.md
  docs/reference/settings.yaml
  go.sum
  internal/autocert/manager.go
  internal/autocert/manager_test.go
Labels: backport 0-12-0, bug

#1861 controlplane: add global headers to virtualhost
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
Labels: backport 0-12-0, bug

#1871 redis: fix deletion versioning
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
Labels: bug

#1872 config: allow customization of envoy boostrap admin options
  config/options.go
  config/options_test.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  internal/envoy/envoy.go
  internal/envoy/misc.go
Labels: improvement

#1870 proxy: implement pass-through for authenticate backend
  internal/controlplane/xds_routes.go
  internal/controlplane/xds_routes_test.go
Labels: improvement

#1878 config: add CertificateFiles to FileWatcherSource list
  config/config_source.go
Labels: backport 0-13-0, improvement

#1876 authenticate: validate origin of signout
  authenticate/handlers.go
  authenticate/handlers_test.go
  docs/docs/topics/single-sign-out.md
  docs/docs/upgrading.md
  go.mod
  go.sum
  internal/frontend/assets/html/userInfo.html
  internal/frontend/assets/style/main.css
  internal/frontend/statik/statik.go
  proxy/handlers.go
  proxy/handlers_test.go
Labels: backport 0-13-0, bug

#1875 docs: additional load balancing documentation
  docs/docs/topics/load-balancing.md
  docs/docs/upgrading.md
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: backport 0-13-0, docs

#1893 Remove internal/protoutil.
  internal/protoutil/protoutil.go
Labels: improvement

#1896 onelogin: fix default scopes for v2
  internal/identity/oidc/onelogin/onelogin.go
Labels: bug

#1897 docs: update security policy
  docs/docs/community/security.md
Labels: backport 0-13-0, docs

#1884 docs: misc upgrade notes and changelog
  docs/docs/CHANGELOG.md
  docs/docs/upgrading.md
Labels: backport 0-13-0, docs

#1883 docs: add load balancing weight documentation
  docs/docs/topics/load-balancing.md
  docs/docs/upgrading.md
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: backport 0-13-0, docs

#1906 config: support map of jwt claim headers
  authorize/check_response_test.go
  authorize/evaluator/opa/policy/authz.rego
  authorize/evaluator/opa/policy/statik.go
  authorize/evaluator/opa_test.go
  authorize/evaluator/store.go
  config/constants.go
  config/custom.go
  config/custom_test.go
  config/options.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  proxy/state.go
Labels: improvement

#1909 docs: update changelog for v0.13.0
  docs/docs/upgrading.md
Labels: backport 0-13-0, docs

#1911 fix registry test
  internal/registry/server_test.go
Labels: bug

#1913 docs: add v0.13 to docs site menu
  docs/.vuepress/config.js
Labels: backport 0-13-0, docs

#1908 envoy: validate binary checksum
  Makefile
  go.mod
  go.sum
  internal/envoy/envoy.go
  scripts/embed-envoy.bash
  scripts/get-envoy.bash
Labels: improvement

#1916 ci: deploy latest release to test environment
  .github/workflows/docker-master.yaml
  .github/workflows/release.yaml
Labels: backport 0-13-0

#1919 docs: add breaking sa changes in v0.13
  docs/docs/upgrading.md
Labels: backport 0-13-0, docs

#1920 docs: fix query param name
  docs/docs/topics/programmatic-access.md
Labels: backport 0-12-0, backport 0-13-0, docs

#1927 chore(deps): update yaml v2 to v3
  config/custom.go
  config/custom_test.go
  go.mod
  go.sum
Labels: dependency

#1928 google: fix default provider URL
  internal/directory/google/google.go
Labels: backport 0-13-0, bug

#1930 config: fix redirect routes from protobuf
  config/policy.go
  config/policy_test.go
Labels: backport 0-13-0, bug

#1934 middleware: basic auth equalize lengths of input
  config/metrics.go
  internal/httputil/handlers.go
  internal/middleware/middleware.go
  internal/middleware/middleware_test.go
Labels: improvement

#1932 autocert: remove non-determinism
  Makefile
  internal/autocert/manager_test.go
Labels: improvement

#1936 identity: record metric for last refresh
  internal/identity/manager/manager.go
  internal/telemetry/metrics/info.go
Labels: improvement

#1937 ci: go 1.16.x, cached tests
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Makefile
  internal/middleware/middleware_test.go
Labels: deployment

#1941 Update data-storage.md
  docs/docs/topics/data-storage.md
Labels: backport 0-13-0, docs

#1939 metrics: add TLS options
  config/config_source.go
  config/metrics.go
  config/metrics_test.go
  config/options.go
  config/validate.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  internal/cmd/pomerium/pomerium.go
  internal/controlplane/http.go
  internal/controlplane/server.go
  internal/controlplane/xds_cluster_test.go
  internal/controlplane/xds_listeners.go
  internal/controlplane/xds_listeners_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: improvement

#1938 ci: cache build and test binaries
  .github/workflows/test.yaml
Labels: deployment

#1944 proxy: redirect to dashboard for logout
  proxy/handlers.go
  proxy/proxy.go
  proxy/state.go
Labels: backport 0-13-0, bug
