Repository pomerium/pomerium, pull requests merged in 2022-08, with the labels that each got.

#3520 docker: fix debug images
  .github/Dockerfile-release-debug
  .github/Dockerfile-release-debug-nonroot
  .github/Dockerfile-release-nonroot
Labels: dependencies, ci

#3542 authorize: add policy error details for custom error messages
  authorize/check_response.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/policy_evaluator.go
  authorize/evaluator/policy_evaluator_test.go
  authorize/grpc.go
  config/policy.go
  internal/httputil/errors.go
  internal/httputil/errors_test.go
  internal/httputil/handlers.go
  pkg/contextutil/policy.go
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/cli/api.pb.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  pkg/grpc/crypt/crypt.pb.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/device/device.pb.go
  pkg/grpc/directory/directory.pb.go
  pkg/grpc/events/last_error.pb.go
  pkg/grpc/events/xds.pb.go
  pkg/grpc/identity/identity.pb.go
  pkg/grpc/registry/registry.pb.go
  pkg/grpc/session/session.pb.go
  pkg/grpc/user/user.pb.go
Labels: improvement

#3555 controlplane: add well-known endpoint to the controlplane http handler
  authenticate/handlers.go
  authenticate/handlers_test.go
  internal/controlplane/http.go
  internal/controlplane/server.go
  internal/controlplane/server_test.go
Labels: improvement

#3503 deployment: update RELEASING.md
  RELEASING.md
Labels: deployment, dependencies

#3558 config: add branding settings
  authenticate/handlers.go
  authenticate/handlers/userinfo.go
  authorize/check_response.go
  config/options.go
  internal/httputil/branding.go
  internal/httputil/errors.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: improvement

#3570 publish to any-distro
  .github/workflows/release.yaml
Labels: backport 0-18-0

#3560 envoy: upgrade to 1.23.0
  config/envoyconfig/clusters_test.go
  config/envoyconfig/envoyconfig.go
  config/envoyconfig/filters.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/outbound.go
  go.mod
  go.sum
  scripts/get-envoy.bash
Labels: improvement

#3545 envoyconfig: add authority header to outbound gRPC requests
  config/envoyconfig/outbound.go
  config/envoyconfig/outbound_test.go
Labels: bug, blocked

#3574 authenticate: add CORS headers to jwks endpoint
  authenticate/handlers.go
Labels: bug, backport 0-18-0

#3591 autocert: fix flaky test
  internal/autocert/manager_test.go
Labels: ci

#3594 postgres: remove not null constraint on data column of record changes table
  pkg/storage/postgres/migrate.go
Labels: bug, backport 0-18-0

#3593 envoyconfig: add virtual host domains for certificates in addition to routes
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  pkg/cryptutil/certificates.go
  pkg/cryptutil/certificates_test.go
  pkg/cryptutil/tls.go
  pkg/cryptutil/tls_test.go
Labels: improvement
