Repository pomerium/pomerium, pull requests merged in 2022-04, with the labels that each got.

#3226 Docs: Grafana JWT & jwt_claims_headers updates
  docs/guides/grafana.md
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: docs, backport 0-17-0

#3237 remove dev ownership of docs.
  .github/CODEOWNERS
Labels: docs

#3228 DOCS: Define stateless
  docs/docs/glossary.md
  docs/docs/production-deployment.md
Labels: docs, backport 0-17-0

#3238 authorize: add name claim
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
Labels: enhancement

#3241 DOCS: Reference Hotfix
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: docs, backport 0-17-0

#3243 config: add support for downstream TLS server name
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/listeners.go
  config/http.go
  config/options.go
  config/options_test.go
  config/policy.go
  docs/reference/readme.md
  docs/reference/settings.yaml
  internal/sets/sorted.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: docs, enhancement

#3240 DOCS: Guide for Cockpit web gui
  docs/.vuepress/config.js
  docs/guides/cockpit.md
  docs/guides/img/cockpit-login-screen.png
  docs/guides/readme.md
Labels: docs, backport 0-17-0

#3249 DOCS: hotfix cockpit config
  docs/guides/cockpit.md
Labels: docs, backport 0-17-0

#3251 docs: Add UUID to docs yaml blocks
  Makefile
  docs/enterprise/console-settings.yaml
  docs/enterprise/reference/configure.md
  docs/reference/settings.yaml
  scripts/generate-settings-docs.py
Labels: docs, backport 0-17-0

#3252 DOCS: add twitter meta tags
  docs/.vuepress/config.js
  package.json
  yarn.lock
Labels: docs, backport 0-17-0

#3257 config: fix DefaultTransport so it is still a *http.Transport
  config/http.go
Labels: bug, backport 0-17-0

#3255 add databroker multi lease handlers
  pkg/grpc/databroker/leaser.go
  pkg/grpc/databroker/leaser_test.go
Labels: backport latest, enhancement

#3261 DOCS: Update logo for Twitter cards
  docs/.vuepress/config.js
  docs/.vuepress/public/img/pomerium-icon-1.png
Labels: docs, backport 0-17-0

#3263 ppl: support . in object_get paths
  config/policy_ppl_test.go
  pkg/policy/rules/rules.go
Labels: docs, improvement

#3268 envoy: use typed extension protocol options for static bootstrap cluster
  config/envoyconfig/bootstrap.go
  config/envoyconfig/bootstrap_test.go
  config/envoyconfig/clusters.go
  config/envoyconfig/protocols.go
Labels: improvement

#3277 authorize: add support for cidr lookups
  authorize/authorize.go
  authorize/check_response_test.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/policy_evaluator.go
  authorize/evaluator/policy_evaluator_test.go
  authorize/internal/store/index.go
  authorize/internal/store/index_test.go
  authorize/internal/store/store.go
  authorize/internal/store/store_test.go
  authorize/state.go
  go.mod
  go.sum
Labels: docs, enhancement

#3282 authorize: pass idp id for webauthn url, allow unauthenticated access to static files
  authorize/check_response.go
  internal/httputil/router.go
Labels: bug

#3281 DOCS: update helm values file
  examples/kubernetes/pomerium-values.yaml
Labels: docs, backport 0-17-0

#3283 DOCS: use https to download python api lib
  docs/enterprise/api.md
Labels: docs, backport 0-17-0

#3291 databroker: add support for putting multiple records
  authorize/access_tracker_test.go
  databroker/databroker_test.go
  databroker/directory.go
  internal/controlplane/events.go
  internal/databroker/config_source_test.go
  internal/databroker/server.go
  internal/databroker/server_test.go
  internal/envoy/envoy.go
  internal/identity/manager/manager.go
  internal/tests/xdserr/cmd/main.go
  pkg/grpc/databroker/databroker.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/databroker/databroker.proto
  pkg/grpc/databroker/databroker_test.go
  pkg/grpc/device/device.go
  pkg/grpc/session/session.go
  pkg/storage/encrypted.go
  pkg/storage/encrypted_test.go
  pkg/storage/inmemory/backend.go
  pkg/storage/inmemory/backend_test.go
  pkg/storage/inmemory/stream.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
  pkg/storage/redis/stream.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/stream.go
  pkg/webauthnutil/credential_storage_test.go
Labels: improvement

#3300 databroker: fix in-memory backend deadlock
  pkg/storage/inmemory/backend.go
  pkg/storage/inmemory/backend_test.go
Labels: bug

#3305 authenticate: fix internal service URL dashboard redirect
  authenticate/handlers.go
  authenticate/handlers_test.go
Labels: bug, backport 0-17-0

#3304 DOCS: Add device identity video
  docs/docs/topics/device-identity.md
  docs/guides/admin-enroll-device.md
  docs/guides/enroll-device.md
Labels: docs, backport 0-17-0
