Repository pomerium/pomerium, pull requests merged in 2022-07, with the labels that each got.

#3460 userinfo: embed assets as data URLs for forward auth
  internal/urlutil/data.go
  ui/embed.go
Labels: bug, backport 0-17-0

#3476 autocert: continue on error
  internal/autocert/manager.go
Labels: bug

#3454 postgres: registry support
  internal/databroker/registry.go
  internal/sets/hash.go
  pkg/storage/postgres/backend.go
  pkg/storage/postgres/migrate.go
  pkg/storage/postgres/option.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/registry.go
  pkg/storage/postgres/registry_test.go
  pkg/storage/postgres/stream.go
Labels: improvement

#3479 authorize: fix x-forwarded-uri
  authorize/grpc.go
  internal/urlutil/forward.go
  internal/urlutil/forward_test.go
Labels: bug, backport 0-17-0

#3482 authorize: fix device synchronization
  authorize/databroker.go
  authorize/grpc.go
  pkg/storage/querier.go
Labels: bug

#3492 options: fix overlapping certificate test
  config/options.go
  config/options_test.go
  pkg/cryptutil/certificates.go
Labels: bug, backport 0-17-0

#3498 add lease name to the log
  pkg/grpc/databroker/leaser.go
Labels: improvement

#3497 authorize: add request id to context
  authorize/grpc.go
  integration/policy_test.go
  internal/telemetry/requestid/requestid.go
  pkg/storage/querier.go
Labels: bug, backport 0-17-0

#3507 depndabot: add docker support
  .github/dependabot.yaml
Labels: ci

#3517 atomicutil: use atomicutil.Value wherever possible
  authenticate/authenticate.go
  authenticate/handlers_test.go
  authenticate/state.go
  authorize/authorize.go
  authorize/check_response_test.go
  authorize/grpc_test.go
  authorize/state.go
  config/options.go
  databroker/databroker.go
  databroker/databroker_test.go
  internal/atomicutil/value.go
  internal/atomicutil/value_test.go
  internal/autocert/manager.go
  internal/controlplane/events_test.go
  internal/controlplane/server.go
  internal/identity/manager/config.go
  internal/identity/manager/manager.go
  internal/identity/manager/sync.go
  internal/identity/providers.go
  internal/log/log.go
  proxy/handlers_test.go
  proxy/proxy.go
  proxy/state.go
Labels: backend, debt

#3519 sets: convert set types to generics
  authorize/access_tracker.go
  config/envoyconfig/listeners.go
  config/options.go
  go.mod
  go.sum
  internal/redisutil/client.go
  internal/sets/hash.go
  internal/sets/size_limited.go
  internal/sets/sorted.go
Labels: backend, debt
