Repository pomerium/pomerium, pull requests merged in 2022-11, with the labels that each got.

#3723 authorize: performance improvements
  authorize/databroker.go
  authorize/evaluator/evaluator.go
  authorize/grpc.go
  authorize/internal/store/store.go
Labels: enhancement

#3734 authorize: fix user caching
  authorize/databroker.go
  authorize/databroker_test.go
  authorize/grpc.go
Labels: enhancement, performance

#3738 controlplane: fix /.well-known/pomerium missing CORS headers
  internal/httputil/handlers.go
  internal/httputil/handlers_test.go
Labels: bug

#3739 bump Envoy to 1.23.2
  scripts/get-envoy.bash
Labels: dependencies

#3743 config: disable Strict-Transport-Security when using a self-signed certificate
  config/envoyconfig/http_connection_manager.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/options.go
  config/options_test.go
  pkg/cryptutil/tls.go
Labels: enhancement

#3742 config: generate cookie secret if not set in all-in-one mode
  authenticate/authenticate_test.go
  config/envoyconfig/protocols.go
  config/options.go
  config/options_test.go
  internal/log/warnings.go
  internal/syncutil/syncutil.go
  pkg/cryptutil/tls.go
  proxy/proxy_test.go
Labels: enhancement

#3754 ci: fix google
  .github/workflows/release.yaml
Labels: ci

#3755 proxy: add userinfo and webauthn endpoints
  authenticate/authenticate.go
  authenticate/handlers.go
  authenticate/handlers/handlers.go
  authenticate/handlers_test.go
  authenticate/state.go
  go.mod
  go.sum
  internal/controlplane/http.go
  internal/handlers/device-enrolled.go
  internal/handlers/handlers.go
  internal/handlers/health_check.go
  internal/handlers/health_check_test.go
  internal/handlers/jwks.go
  internal/handlers/jwks_test.go
  internal/handlers/signout.go
  internal/handlers/userinfo.go
  internal/handlers/webauthn/webauthn.go
  internal/handlers/well_known_pomerium.go
  internal/handlers/well_known_pomerium_test.go
  internal/httputil/handlers.go
  internal/httputil/handlers_test.go
  pkg/webauthnutil/options.go
  pkg/webauthnutil/options_test.go
  pkg/webauthnutil/webauthnutil.go
  pkg/webauthnutil/webauthnutil_test.go
  proxy/data.go
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/proxy.go
  proxy/state.go
  ui/src/components/WebAuthnAuthenticateButton.tsx
  ui/src/components/WebAuthnRegisterButton.tsx
  ui/src/types/index.ts
Labels: breaking, enhancement

#3761 hpke: add hpke package
  go.mod
  go.sum
  pkg/hpke/hpke.go
  pkg/hpke/hpke_test.go
  pkg/hpke/url.go
  pkg/hpke/url_test.go
Labels: enhancement

#3762 hpke: add HPKE key to JWKS endpoint
  config/options.go
  go.mod
  go.sum
  internal/controlplane/http.go
  internal/controlplane/server_test.go
  internal/handlers/jwks.go
  internal/handlers/jwks_test.go
  pkg/hpke/hpke.go
  pkg/hpke/jwks.go
  pkg/hpke/jwks_test.go
  pkg/hpke/url.go
Labels: enhancement

#3768 storage: ignore removed fields when deserializing the data
  pkg/protoutil/any.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/registry_test.go
Labels: bug, backend, backport 0-20-0

#3767 bump envoy to v1.24.0
  authorize/check_response.go
  authorize/check_response_test.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  scripts/get-envoy.bash
Labels: dependency

#3773 config: add option for tls renegotiation
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/policy.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement
