Repository pomerium/pomerium, pull requests merged in 2022-06, with the labels that each got.

#3377 authorize: use query instead of sync for databroker data
  authorize/authorize.go
  authorize/check_response_test.go
  authorize/databroker.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/policy_evaluator_test.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/internal/store/index.go
  authorize/internal/store/index_test.go
  authorize/internal/store/store.go
  authorize/internal/store/store_test.go
  authorize/log.go
  authorize/sync.go
  authorize/sync_test.go
  go.mod
  go.sum
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/audit/audit.proto
  pkg/grpc/databroker/databroker.go
  pkg/storage/cache.go
  pkg/storage/cache_test.go
  pkg/storage/querier.go
Labels: enhancement

#3389 postgres: fix CIDR query
  pkg/storage/postgres/filter.go
  pkg/storage/postgres/filter_test.go
Labels: bug

#3391 fix: The built binary file is missing "ui/dist/index.js" and "ui/dist…
  Makefile
Labels: bug, backport 0-17-0

#3405 github-actions: remove mysql bump
  .github/workflows/docker-main.yaml
Labels: ci

#3409 integration: update readme with instructions for how to run the tests locally
  README.md
Labels: docs, improvement, ci

#3410 authorize: fix not found check
  authorize/databroker.go
  pkg/storage/storage.go
Labels: bug

#3411 identity: batch directory updates
  internal/identity/manager/manager.go
  internal/identity/manager/manager_test.go
Labels: improvement, performance

#3408 postgres: use CTE and GENERATED version number instead of serialized transaction
  pkg/grpc/databroker/syncer.go
  pkg/grpc/databroker/syncer_test.go
  pkg/storage/postgres/backend.go
  pkg/storage/postgres/migrate.go
  pkg/storage/postgres/postgres.go
Labels: ci

#3413 bump envoy to 1.21.3
  scripts/get-envoy.bash
Labels: dependencies, backport 0-17-0

#3412 databroker: add support for syncing by type
  internal/databroker/server.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/databroker/databroker.proto
  pkg/grpc/databroker/fast_forward.go
  pkg/grpc/databroker/syncer.go
  pkg/storage/encrypted.go
  pkg/storage/inmemory/backend.go
  pkg/storage/inmemory/backend_test.go
  pkg/storage/inmemory/stream.go
  pkg/storage/postgres/backend.go
  pkg/storage/postgres/backend_test.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/stream.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
  pkg/storage/redis/stream.go
  pkg/storage/storage.go
Labels: improvement

#3421 authorize: allow missing user for authorization
  authorize/grpc.go
Labels: bug

#3423 github-actions: faster docker publish
  .github/workflows/docker.yaml
Labels: ci

#3425 goreleaser: remove ignore
  .github/goreleaser.yaml
Labels: ci

#3429 revert docker changes
  .github/workflows/docker-main.yaml
Labels: ci

#3415 allow pomerium to be embedded as a library
  .gitignore
  Makefile
  cmd/pomerium/main.go
  config/config.go
  config/config_source.go
  databroker/cache.go
  internal/controlplane/server.go
  internal/envoy/embed.go
  pkg/cmd/pomerium/pomerium.go
  pkg/cmd/pomerium/pomerium_test.go
  pkg/envoy/envoy.go
  pkg/envoy/envoy_darwin.go
  pkg/envoy/envoy_linux.go
  pkg/envoy/envoy_other.go
  pkg/envoy/envoy_test.go
  pkg/envoy/extract.go
  pkg/envoy/files/files.go
  pkg/envoy/files/files_darwin_amd64.go
  pkg/envoy/files/files_darwin_arm64.go
  pkg/envoy/files/files_external.go
  pkg/envoy/files/files_linux_amd64.go
  pkg/envoy/files/files_linux_arm64.go
  pkg/envoy/misc.go
  scripts/get-envoy.bash
  ui/embed.go
  ui/embed_ext.go
  ui/embed_local.go
Labels: improvement

#3430 device enrollment: fix ip address
  authenticate/handlers/webauthn/webauthn.go
  internal/httputil/httputil.go
  internal/httputil/httputil_test.go
Labels: bug

#3403 Expand PR template
  .github/PULL_REQUEST_TEMPLATE
Labels: discuss, improvement, nit

#3433 add benchmark
  .github/workflows/benchmark.yaml
  integration/benchmark_test.go
Labels: ci

#3442 cmd: remove test
  pkg/cmd/pomerium/pomerium_test.go
Labels: NeedsDiscussion, ci

#3446 postgres: fix record deletion
  pkg/storage/postgres/backend_test.go
  pkg/storage/postgres/postgres.go
Labels: bug

#3453 config: support files for shared_secret, client_secret, cookie_secret and signing_key
  authenticate/authenticate.go
  authenticate/identity.go
  authenticate/state.go
  authorize/authorize.go
  authorize/check_response.go
  config/config_source.go
  config/identity.go
  config/options.go
  databroker/cache.go
  proxy/proxy.go
  proxy/state.go
Labels: docs, improvement

#3452 add metrics aggregation
  config/config.go
  config/config_source.go
  config/metrics.go
  internal/telemetry/metrics/providers.go
  internal/telemetry/metrics/providers_test.go
  pkg/cmd/pomerium/pomerium.go
  pkg/netutil/netutil.go
Labels: improvement
