Repository pomerium/pomerium, pull requests merged in 2022-05, with the labels that each got.

#3322 httputil/reproxy: fix policy transport
  config/http.go
  config/http_test.go
Labels: bug, backport 0-17-0

#3290 fixing pomerium traefik example
  examples/traefik-ingress/values/pomerium.yaml
Labels: docs

#3269 DOCS: Add Rego Example
  docs/enterprise/console-settings.yaml
  docs/enterprise/reference/manage.md
Labels: blocked, docs, backport 0-17-0

#3326 DOCS: Crosslink Helm to Ingress Controller
  docs/docs/k8s/helm.md
Labels: docs, backport 0-17-0

#3345 envoyconfig: prevent nil reproxy handler
  config/envoyconfig/builder.go
Labels: bug, backport 0-17-0

#3340 DOCS: Update Annotations Table
  docs/docs/k8s/ingress.md
Labels: docs, backport 0-17-0

#3348 ci: use labels to alert of recently updated issues
  .github/workflows/needs-data.yaml
Labels: ci

#3341 Docs: Document TCP routes in Kubernetes
  docs/docs/k8s/ingress.md
Labels: docs, backport 0-17-0

#3366 add x-request-id in responses
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
Labels: improvement, backport 0-17-0

#3365 storage: add filter expressions, upgrade go to 1.18.1
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Dockerfile
  Dockerfile.debug
  go.mod
  go.sum
  pkg/storage/filter.go
  pkg/storage/filter_test.go
  pkg/storage/index.go
  pkg/storage/index_test.go
  pkg/storage/stream_filter.go
  pkg/storage/stream_filter_test.go
Labels: improvement

#3368 storage: add filtering to SyncLatest
  internal/databroker/server.go
  pkg/storage/encrypted.go
  pkg/storage/inmemory/backend.go
  pkg/storage/inmemory/backend_test.go
  pkg/storage/inmemory/stream.go
  pkg/storage/redis/redis.go
  pkg/storage/redis/redis_test.go
  pkg/storage/redis/stream.go
  pkg/storage/storage.go
Labels: improvement

#3370 postgres: databroker storage backend
  Makefile
  config/helpers.go
  config/options.go
  go.mod
  go.sum
  internal/databroker/registry.go
  internal/databroker/server.go
  internal/identity/oauth/github/github.go
  internal/testutil/postgres.go
  pkg/contextutil/contextutil.go
  pkg/contextutil/contextutil_test.go
  pkg/cryptutil/helpers.go
  pkg/storage/postgres/backend.go
  pkg/storage/postgres/backend_test.go
  pkg/storage/postgres/filter.go
  pkg/storage/postgres/filter_test.go
  pkg/storage/postgres/migrate.go
  pkg/storage/postgres/option.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/stream.go
  pkg/storage/stream.go
Labels: enhancement

#3386 do not require idp set in the bootstrap config, as it may be later configured via the databroker
  databroker/cache.go
  internal/directory/provider.go
  internal/identity/providers.go
Labels: backend, enhancement
