Repository pomerium/pomerium, pull requests merged in 2022-01, with the labels that each got.

#2888 DOCS: Fix ToC
  docs/docs/topics/mutual-auth.md
Labels: bug, docs, backport 0-15-0, backport 0-16-0

#2800 DOCS: GitLab Integration guide
  docs/.vuepress/config.js
  docs/guides/gitlab.md
  docs/guides/img/gitlab/gitlab-desktop-connection.png
  docs/guides/img/gitlab/gitlab-login.webm
  docs/guides/readme.md
Labels: docs, backport 0-15-0, backport 0-16-0

#2895 integration: fix default port for verify service
  integration/clusters/auth0-kubernetes/compose.yml
  integration/clusters/auth0-multi/compose.yml
  integration/clusters/auth0-nginx/compose.yml
  integration/clusters/auth0-single/compose.yml
  integration/clusters/auth0-traefik/compose.yml
  integration/clusters/azure-kubernetes/compose.yml
  integration/clusters/azure-multi/compose.yml
  integration/clusters/azure-nginx/compose.yml
  integration/clusters/azure-single/compose.yml
  integration/clusters/azure-traefik/compose.yml
  integration/clusters/github-kubernetes/compose.yml
  integration/clusters/github-multi/compose.yml
  integration/clusters/github-nginx/compose.yml
  integration/clusters/github-single/compose.yml
  integration/clusters/github-traefik/compose.yml
  integration/clusters/gitlab-kubernetes/compose.yml
  integration/clusters/gitlab-multi/compose.yml
  integration/clusters/gitlab-nginx/compose.yml
  integration/clusters/gitlab-single/compose.yml
  integration/clusters/gitlab-traefik/compose.yml
  integration/clusters/google-kubernetes/compose.yml
  integration/clusters/google-multi/compose.yml
  integration/clusters/google-nginx/compose.yml
  integration/clusters/google-single/compose.yml
  integration/clusters/google-traefik/compose.yml
  integration/clusters/oidc-kubernetes/compose.yml
  integration/clusters/oidc-multi/compose.yml
  integration/clusters/oidc-nginx/compose.yml
  integration/clusters/oidc-single/compose.yml
  integration/clusters/oidc-traefik/compose.yml
  integration/clusters/okta-kubernetes/compose.yml
  integration/clusters/okta-multi/compose.yml
  integration/clusters/okta-nginx/compose.yml
  integration/clusters/okta-single/compose.yml
  integration/clusters/okta-traefik/compose.yml
  integration/clusters/onelogin-kubernetes/compose.yml
  integration/clusters/onelogin-multi/compose.yml
  integration/clusters/onelogin-nginx/compose.yml
  integration/clusters/onelogin-single/compose.yml
  integration/clusters/onelogin-traefik/compose.yml
  integration/clusters/ping-kubernetes/compose.yml
  integration/clusters/ping-multi/compose.yml
  integration/clusters/ping-nginx/compose.yml
  integration/clusters/ping-single/compose.yml
  integration/clusters/ping-traefik/compose.yml
  integration/tpl/backends/verify.libsonnet
Labels: bug

#2892 authenticate: add device-enrolled page
  authenticate/authenticate.go
  authenticate/handlers.go
  authenticate/handlers/device-enrolled.go
  authenticate/handlers/handlers.go
  authenticate/handlers/webauthn/webauthn.go
  internal/frontend/assets/html/device-enrolled.go.html
  internal/urlutil/proxy.go
Labels: feature

#2902 envoy: upgrade to 1.20.1
  scripts/get-envoy.bash
Labels: improvement, dependencies

#2882 Remove references to idp_provider_url for Google.
  docs/docs/identity-providers/google.md
  docs/reference/readme.md
  docs/reference/settings.yaml
  examples/config/config.example.env
  examples/config/config.example.yaml
  examples/docker/nginx.docker-compose.yml
Labels: docs, backport 0-16-0

#2906 Docs: Mutual Auth Hotfix
  docs/docs/topics/mutual-auth.md
Labels: docs, backport 0-16-0

#2905 Docs: Update and align reference settings
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: docs, backport 0-16-0

#2909 envoy: check certificates for must-staple flag and drop them if they are missing the response
  config/envoyconfig/listeners.go
  config/envoyconfig/tls.go
  config/envoyconfig/tls_test.go
  pkg/cryptutil/certificates.go
Labels: bug, backport 0-16-0

#2914 Docs: Manual Backport: update and align reference settings (#2905)
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: docs

#2918 docs: fix argo link
  docs/guides/argo.md
Labels: docs, backport 0-16-0

#2922 DOCS: keyword tag updates
  docs/docs/architecture.md
  docs/docs/background.md
  docs/docs/community/code-of-conduct.md
  docs/docs/community/contributing.md
  docs/docs/community/readme.md
  docs/docs/community/security.md
  docs/docs/identity-providers/auth0.md
  docs/docs/identity-providers/azure.md
  docs/docs/identity-providers/cognito.md
  docs/docs/identity-providers/github.md
  docs/docs/identity-providers/gitlab.md
  docs/docs/identity-providers/google.md
  docs/docs/identity-providers/okta.md
  docs/docs/identity-providers/ping.md
  docs/docs/install/binary.md
  docs/docs/install/from-source.md
  docs/docs/install/readme.md
  docs/docs/k8s/helm.md
  docs/docs/k8s/ingress.md
  docs/docs/readme.md
  docs/docs/tcp/readme.md
  docs/docs/topics/certificates.md
  docs/docs/topics/device-identity.md
  docs/docs/topics/mutual-auth.md
  docs/docs/troubleshooting.md
  docs/enterprise/api.md
  docs/enterprise/concepts.md
  docs/enterprise/install/readme.md
  docs/enterprise/reference/config.md
  docs/enterprise/reference/configure.md
  docs/enterprise/reference/manage.md
  docs/enterprise/reference/reports.md
  docs/guides/ad-guard.md
  docs/guides/argo.md
  docs/guides/cloud-run.md
  docs/guides/code-server.md
  docs/guides/enroll-device.md
  docs/guides/gitlab.md
  docs/guides/grafana.md
  docs/guides/jwt-verification.md
  docs/guides/kubernetes-dashboard.md
  docs/guides/kubernetes.md
  docs/guides/local-oidc.md
  docs/guides/mtls.md
  docs/guides/nginx.md
  docs/guides/synology.md
  docs/guides/tcp.md
  docs/guides/tiddlywiki.md
  docs/guides/traefik-ingress.md
  docs/guides/transmission.md
  docs/guides/upstream-mtls.md
  docs/reference/readme.md
  docs/reference/settings.yaml
  scripts/generate-console-pages.js
Labels: docs, backport 0-16-0

#2919 handle device states in deny block, fix default device type
  authorize/check_response.go
  authorize/grpc.go
  pkg/policy/criteria/device.go
  pkg/policy/criteria/device_test.go
Labels: bug, backport 0-16-0

#2925 deployment: fix distroless base arch
  .github/Dockerfile-release
  .github/goreleaser.yaml
  Dockerfile
Labels: bug

#2927 devices: treat undefined device types as any
  authenticate/handlers/webauthn/webauthn.go
  pkg/webauthnutil/device_type.go
  pkg/webauthnutil/device_type_test.go
Labels: bug

#2931 authenticate: add callback endpoint
  authenticate/handlers.go
Labels: bug, backport 0-16-0

#2932 Docs: Update Cache to Databroker
  docs/docs/img/pomerium-auth-flow.svg
  docs/docs/img/pomerium-container-context.svg
Labels: docs, backport 0-16-0

#2947 Docs: Crosslinks on Upstream mTLS
  docs/guides/upstream-mtls.md
Labels: docs, backport 0-16-0

#2949 return explicit error when directory sync is disabled
  internal/directory/provider.go
Labels: improvement

#2936 authenticate: support webauthn redirects to non-pomerium domains
  authenticate/handlers.go
  authenticate/handlers/webauthn/webauthn.go
  config/envoyconfig/listeners.go
  config/options.go
  config/options_test.go
Labels: bug

#2951 devices: shrink credentials by removing unnecessary data
  pkg/grpc/device/device.go
  pkg/grpc/device/device_test.go
Labels: bug

#2950 google: support groups for users outside of the organization
  databroker/directory.go
  internal/directory/directoryerrors/errors.go
  internal/directory/google/google.go
  internal/directory/google/google_test.go
  internal/directory/provider.go
Labels: improvement

#2958 deployment: remove DST cert workaround from debug image
  Dockerfile.debug
Labels: deployment

#2959 Update security.md
  docs/docs/community/security.md
Labels: docs, backport 0-16-0

#2933 Docs: code-server guide refresh
  docs/guides/code-server.md
Labels: docs, backport 0-16-0

#2956 DOCS: Clarify base path for idp_provider_url
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: docs, backport 0-16-0

#2968 deployment: enable goreleaser buildx
  .github/goreleaser.yaml
Labels: bug, deployment

#2966 config: fix policy matching for regular expressions
  config/options_test.go
  config/policy.go
  config/policy_test.go
  internal/urlutil/url.go
Labels: bug

#2897 DOCS: New page: Glossary
  docs/.vuepress/config.js
  docs/docs/glossary.md
Labels: docs, backport 0-16-0

#2943 Docs: Rewrite Istio Guide for Ingress Controller
  docs/docs/glossary.md
  docs/guides/istio.md
  examples/kubernetes/istio/grafana.ini.yml
Labels: docs, backport 0-16-0

#2976 authenticate: fix expiring user info endpoint
  authenticate/authenticate.go
  authenticate/handlers.go
  authenticate/url.go
  authenticate/url_test.go
Labels: enhancement

#2965 Docs - Backport of: clarify base path for idp_provider_url (#2956)
  docs/reference/readme.md
  docs/reference/settings.yaml
Labels: docs

#2957 directory: save IDP errors to databroker, put event handling in dedicated package
  internal/controlplane/events.go
  internal/controlplane/events_test.go
  internal/controlplane/server.go
  internal/controlplane/xdsmgr/xdsmgr.go
  internal/controlplane/xdsmgr/xdsmgr_test.go
  internal/events/events.go
  internal/events/manager.go
  internal/events/manager_test.go
  internal/identity/manager/manager.go
  pkg/grpc/events/idp.pb.go
  pkg/grpc/events/idp.proto
  pkg/grpc/protoc.bash
  pkg/grpc/registry/registry.pb.validate.go
Labels: improvement

#2977 Update enterprise changelog for v0.16.0
  docs/enterprise/changelog.md
  docs/enterprise/upgrading.md
Labels: docs, backport 0-16-0

#2974 last known metric error
  internal/controlplane/events.go
  internal/events/events.go
  internal/events/manager_test.go
  internal/identity/manager/manager.go
  internal/telemetry/metrics/info.go
  pkg/grpc/events/last_error.pb.go
  pkg/grpc/events/last_error.proto
  pkg/grpc/protoc.bash
Labels: enhancement
