Repository pomerium/pomerium, pull requests merged in 2023-05, with the labels that each got.

#4144 Update SECURITY.md
  SECURITY.md
Labels: backport 0-22-0

#4147 hpke: compress query string
  authenticate/handlers.go
  go.mod
  internal/urlutil/known.go
  internal/urlutil/known_test.go
  pkg/hpke/url.go
  pkg/hpke/url_test.go
Labels: enhancement

#4148 config: add cookie_same_site option
  authenticate/handlers.go
  authenticate/identity_profile.go
  authenticate/state.go
  config/options.go
  config/options_test.go
  config/session.go
  config/validate.go
  internal/sessions/cookie/cookie_store.go
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/cli/api.pb.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  pkg/grpc/crypt/crypt.pb.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/device/device.pb.go
  pkg/grpc/events/last_error.pb.go
  pkg/grpc/identity/identity.pb.go
  pkg/grpc/registry/registry.pb.go
  pkg/grpc/registry/registry.pb.validate.go
  pkg/grpc/session/session.pb.go
  pkg/grpc/user/user.pb.go
  proxy/state.go
Labels: enhancement

#4167 fix WillHaveCertificateForServerName check to be strict match for derived cert name
  config/config.go
  config/config_test.go
  config/envoyconfig/listeners_test.go
  config/options.go
Labels: bug, backport 0-22-0

#4137 authenticate: add aws cognito
  authenticate/handlers.go
  internal/identity/oidc/cognito/cognito.go
  internal/identity/providers.go
Labels: enhancement

#4186 improve certificate matching performance
  config/config.go
  config/config_test.go
  config/envoyconfig/listeners.go
  config/envoyconfig/route_configurations.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
Labels: performance, backport 0-22-0

#4196 config: simplify default set response headers
  config/envoyconfig/http_connection_manager.go
  config/envoyconfig/listeners.go
  config/envoyconfig/route_configurations.go
  config/envoyconfig/route_configurations_test.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/options.go
  config/options_test.go
Labels: performance, backport 0-22-0

#4211 authorize: populate issuer even when policy is nil
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_test.go
Labels: bug, docs, backport 0-21-0, backport 0-22-0
