Repository pomerium/pomerium, pull requests merged in 2023-06, with the labels that each got.

#4218 dependencies: pin node to lts
  Dockerfile
  Dockerfile.debug
Labels: dependencies

#4229 ci: fix lint workflow
  .github/workflows/lint.yaml
Labels: ci

#4270 add JWT timestamp formatting workaround
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
Labels: backport 0-22-0

#4315 Allow clearing default Azure and Google auth code options
  config/options_test.go
  internal/identity/oidc/azure/microsoft.go
  internal/identity/oidc/azure/microsoft_test.go
  internal/identity/oidc/google/google.go
  internal/identity/oidc/google/google_test.go
Labels: docs
