Repository pomerium/pomerium, pull requests merged in 2023-03, with the labels that each got.

#4044 hpke: move published public keys to a new endpoint
  authorize/check_response_test.go
  config/config.go
  internal/controlplane/http.go
  internal/controlplane/server_test.go
  internal/handlers/hpke_public_key.go
  internal/handlers/hpke_public_key_test.go
  internal/handlers/jwks.go
  internal/handlers/jwks_test.go
  internal/urlutil/known.go
  pkg/hpke/hpke.go
  pkg/hpke/http.go
  pkg/hpke/http_test.go
  proxy/proxy_test.go
Labels: bug, backport 0-21-0

#4045 Update grafana.ini.yml
  examples/kubernetes/istio/grafana.ini.yml
Labels: docs

#4046 authorize: move sign out and jwks urls to route, update issuer for JWT
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
  authorize/evaluator/policy_evaluator_test.go
  authorize/internal/store/store.go
  internal/controlplane/server_test.go
  internal/handlers/well_known_pomerium.go
  internal/handlers/well_known_pomerium_test.go
Labels: bug, backport 0-21-0

#4064 store authenticate state on creation
  authenticate/authenticate.go
Labels: bug

#4090 authenticate: have an option to trim the contents of the callback
  authenticate/config.go
  authenticate/handlers.go
Labels: enhancement
