Repository pomerium/pomerium, pull requests merged in 2023-12, with the labels that each got.

#4774 metrics: explicitly set Accept header
  internal/telemetry/metrics/providers.go
  internal/telemetry/metrics/providers_test.go
Labels: bug, backport 0-24-0

#4806 core/storage: hijack connections for notification listeners
  pkg/storage/postgres/backend.go
  pkg/storage/postgres/backend_test.go
Labels: bug, backport 0-24-0

#4766 core/go: use max procs
  cmd/pomerium/main.go
  go.mod
  go.sum
  internal/errgrouputil/builder.go
  pkg/storage/storagetest/storagetest.go
Labels: performance

#4838 storage/inmemory: fix Patch() error handling
  pkg/storage/inmemory/backend.go
  pkg/storage/storagetest/storagetest.go
Labels: bug, backport 0-24-0

#4817 integration: test with both authentication flows
  .github/workflows/benchmark.yaml
  .github/workflows/test.yaml
  config/options.go
  config/options_test.go
  integration/clusters/multi-stateful/compose.yml
  integration/clusters/multi-stateless/compose.yml
  integration/clusters/single-stateful/compose.yml
  integration/clusters/single-stateless/compose.yml
  integration/main_test.go
  integration/tpl/backends/pomerium.libsonnet
  integration/tpl/clusters/multi-stateful/compose.yml.jsonnet
  integration/tpl/clusters/multi-stateless/compose.yml.jsonnet
  integration/tpl/clusters/multi/compose.yml.jsonnet
  integration/tpl/clusters/single-stateful/compose.yml.jsonnet
  integration/tpl/clusters/single-stateless/compose.yml.jsonnet
  integration/tpl/clusters/single/compose.yml.jsonnet
  integration/tpl/deployments/kubernetes.libsonnet
  integration/tpl/deployments/multi.libsonnet
  integration/tpl/deployments/single.libsonnet
Labels: ci

#4851 zero/openapi: pin v1.0.0 of a runtime
  go.mod
  go.sum
  pkg/zero/cluster/generate.go
Labels: dependencies

#4854 zero: only leave public packages in pkg/zero
  internal/zero/api/api.go
  internal/zero/api/config.go
  internal/zero/api/download.go
  internal/zero/apierror/request_id.go
  internal/zero/apierror/response.go
  internal/zero/apierror/response_test.go
  internal/zero/apierror/terminal.go
  internal/zero/bootstrap/bootstrap.go
  internal/zero/bootstrap/new.go
  internal/zero/connect-mux/config.go
  internal/zero/connect-mux/messages.go
  internal/zero/connect-mux/service.go
  internal/zero/controller/controller.go
  internal/zero/controller/mux_log.go
  internal/zero/reconciler/config.go
  internal/zero/reconciler/download_cache.go
  internal/zero/reconciler/download_cache_test.go
  internal/zero/reconciler/service.go
  internal/zero/token/cache.go
  internal/zero/token/cache_test.go
  pkg/zero/cluster/client_errors.go
  pkg/zero/cluster/client_test.go
  pkg/zero/cluster/token_fetcher.go
  pkg/zero/connect/client_test.go
Labels: debt, ignore-changelog

#4844 core/ci: update linting
  .github/workflows/lint.yaml
  .golangci.yml
  authorize/evaluator/evaluator_test.go
  config/autocert.go
  config/envoyconfig/acmetlsalpn_test.go
  config/envoyconfig/clusters.go
  config/layered.go
  config/mtls_test.go
  config/options.go
  config/policy.go
  integration/policy_test.go
  internal/authenticateflow/stateful_test.go
  internal/deterministicecdsa/ecdsa.go
  internal/fileutil/fileutil_test.go
  internal/httputil/router_test.go
  internal/httputil/server_test.go
  internal/identity/manager/manager_test.go
  internal/retry/error.go
  internal/telemetry/metrics/grpc.go
  internal/zero/bootstrap/file.go
  internal/zero/bootstrap/source.go
  internal/zero/reconciler/bundles_format_test.go
  internal/zero/reconciler/bundles_queue_test.go
  internal/zero/reconciler/download_cache.go
  pkg/encoding/base58/base58.go
  pkg/grpc/databroker/leaser.go
  pkg/grpc/health.go
  pkg/policy/criteria/client_certificate_test.go
  pkg/protoutil/fieldmask_test.go
  ui/embed_local.go
Labels: debt, ci

#4856 core/ci: fix linting issues
  internal/zero/analytics/sessions.go
  internal/zero/apierror/request_id.go
  internal/zero/apierror/terminal.go
Labels: ci

#4857 core/config: remove debug option, always use json logs
  authorize/grpc_test.go
  config/log.go
  config/options.go
  config/options_test.go
  examples/config/config.example.yaml
  go.mod
  internal/log/log.go
  internal/log/log_test.go
  internal/testutil/log.go
  internal/zero/cmd/command.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: docs, breaking, enhancement

#4859 core/ci: tag docker images with vMAJOR.MINOR
  .github/goreleaser.yaml
Labels: ci

#4858 core/authenticate: refactor identity authenticators to initiate redirect
  authenticate/handlers.go
  authenticate/handlers_test.go
  internal/handlers/signedout.go
  internal/handlers/signedout_test.go
  internal/httputil/signedout.go
  internal/identity/mock_provider.go
  internal/identity/oauth/apple/apple.go
  internal/identity/oauth/github/github.go
  internal/identity/oidc/auth0/auth0.go
  internal/identity/oidc/auth0/auth0_test.go
  internal/identity/oidc/cognito/cognito.go
  internal/identity/oidc/cognito/cognito_test.go
  internal/identity/oidc/oidc.go
  internal/identity/providers.go
Labels: docs, enhancement

#4862 zero: group funcs that need run within a lease
  internal/zero/controller/controller.go
  internal/zero/leaser/leaser.go
  internal/zero/leaser/monitor.go
  internal/zero/leaser/restart.go
  internal/zero/leaser/restart_test.go
  internal/zero/reconciler/service.go
Labels: bug

#4865 core: fix graceful stop
  databroker/cache.go
  internal/controlplane/server.go
  pkg/contextutil/contextutil.go
  pkg/grpcutil/serve.go
  pkg/grpcutil/serve_test.go
  pkg/httputil/serve.go
  pkg/httputil/serve_test.go
Labels: bug, backport 0-24-0
