Repository pomerium/pomerium, pull requests merged in 2023-01, with the labels that each got.

#3855 identity: fix expired session deletion
  internal/identity/manager/manager.go
  internal/identity/manager/manager_test.go
Labels: bug, backport 0-20-0

#3860 config: generate derived certificates instead of self-signed certificates
  config/config.go
  config/config_test.go
  config/envoyconfig/listeners.go
  pkg/cryptutil/tls.go
  pkg/cryptutil/tls_test.go
Labels: bug

#3876 postgres: return unknown records instead of skipping them
  pkg/storage/postgres/backend_test.go
  pkg/storage/postgres/postgres.go
Labels: bug, backport 0-20-0

#3878 authenticate: add additional error details for hmac errors
  authenticate/handlers.go
  internal/httputil/errors.go
  ui/src/components/ErrorPage.tsx
  ui/src/types/index.ts
Labels: enhancement

#3861 config: use insecure skip verify if derived certificates are not used
  authorize/state.go
  config/config.go
  internal/httputil/transport.go
  proxy/state.go
Labels: bug

#3882 config: add missing options
  config/options.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: bug, backport 0-20-0

#3886 scripts: update get-envoy script to download all binaries
  scripts/get-envoy.bash
Labels: enhancement

#3906 add google cloud creds to ignore
  .gitignore
Labels: backport 0-21-0

#3918 bump goreleaser to v4.1.1
  .github/workflows/release.yaml
Labels: ci, backport 0-21-0

#3917 authenticate: always trust the passed in idp
  authenticate/handlers.go
  authenticate/identity_profile.go
Labels: bug, backport 0-21-0

#3930 identity: fix nil reference error when there is no authenticator
  internal/identity/manager/manager.go
  internal/identity/manager/manager_test.go
Labels: bug, backport 0-20-0, backport 0-21-0
