Repository pomerium/pomerium, pull requests merged in 2023-10, with the labels that each got.

#4616 Docs: remove tcp example
  README.md
  examples/tcp/README.md
  examples/tcp/_wildcard.localhost.pomerium.io-key.pem
  examples/tcp/_wildcard.localhost.pomerium.io.pem
  examples/tcp/config.yaml
  examples/tcp/docker-compose.yaml
  examples/tcp/pomerium-tunnel.sh
  examples/tcp/rootCA-key.pem
  examples/tcp/rootCA.pem
  examples/tcp/ssh_config
Labels: docs, backport 0-23-0

#4632 identity: override TokenSource expiry behavior
  internal/identity/oauth/apple/apple.go
  internal/identity/oidc/oidc.go
  internal/identity/oidc/refresh.go
  internal/identity/oidc/refresh_test.go
Labels: backport 0-23-0

#4633 identity: preserve session refresh schedule
  internal/identity/manager/data.go
  internal/identity/manager/manager.go
  internal/identity/manager/manager_test.go
Labels: backport 0-23-0

#4638 identity: rework session refresh error handling
  internal/identity/manager/manager.go
  internal/identity/manager/manager_test.go
Labels: backport 0-23-0

#4643 core/grpc: fix deprecated protobuf package, remove tools
  .tool-versions
  Makefile
  config/envoyconfig/envoyconfig.go
  config/envoyconfig/listeners.go
  config/envoyconfig/per_filter_config.go
  config/envoyconfig/routes.go
  go.mod
  go.sum
  internal/testutil/testutil.go
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/cli/api.pb.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/crypt/crypt.pb.go
  pkg/grpc/databroker/databroker.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/databroker/mock_databroker/databroker.pb.go
  pkg/grpc/device/device.pb.go
  pkg/grpc/events/last_error.pb.go
  pkg/grpc/identity/identity.pb.go
  pkg/grpc/registry/registry.pb.go
  pkg/grpc/session/session.pb.go
  pkg/grpc/user/user.pb.go
  pkg/storage/postgres/registry.go
  scripts/protoc-gen-go
  scripts/protoc-gen-validate
  tools.go
Labels: debt, ci

#4644 core/go: upgrade go
  .github/workflows/benchmark.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .tool-versions
  Dockerfile
  Dockerfile.debug
Labels: debt, ci

#4645 core/config: add config version, additional telemetry
  config/config.go
  config/config_source.go
  config/envoyconfig/bootstrap.go
  config/envoyconfig/clusters.go
  config/envoyconfig/listeners.go
  config/envoyconfig/route_configurations.go
  internal/controlplane/server.go
  internal/controlplane/xds.go
  internal/controlplane/xdsmgr/xdsmgr.go
  internal/controlplane/xdsmgr/xdsmgr_test.go
  internal/databroker/config_source.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: backport 0-23-0

#4650 core/hpke: reduce memory usage from zstd
  pkg/hpke/url.go
  pkg/hpke/url_test.go
Labels: performance

#4649 core/controlplane: apply configuration changes in a background thread
  internal/controlplane/events_test.go
  internal/controlplane/grpc_accesslog.go
  internal/controlplane/server.go
  internal/controlplane/xds.go
Labels: performance
