Repository pomerium/pomerium, pull requests merged in 2023-02, with the labels that each got.

#3929 maybe fix flaky test
  internal/handlers/jwks_test.go
Labels: debt

#3938 docker: switch to debian
  Dockerfile.debug
Labels: bug, ci, backport 0-20-0, backport 0-21-0

#3956 envoyconfig: preserve case of HTTP headers when using HTTP/1
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/protocols.go
  config/envoyconfig/protocols_test.go
Labels: enhancement

#3957 config: add additional dns lookup families, default to V4_PREFERRED
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/envoyconfig.go
  config/options.go
  config/validate.go
Labels: docs, enhancement

#3980 lua: fix rewrite response headers to handle dashes in URLs
  config/envoyconfig/lua_test.go
  config/envoyconfig/luascripts/rewrite-headers.lua
  config/envoyconfig/testdata/main_http_connection_manager_filter.json
Labels: bug, backport 0-21-0

#3978 authenticate: save the session cookie with a different name
  authenticate/state.go
Labels: bug, backport 0-21-0

#3979 authenticate: only use csrf none for apple
  authenticate/handlers.go
Labels: enhancement

#3981 webauthn: only return known device credentials that match the given type
  pkg/webauthnutil/options.go
  pkg/webauthnutil/options_test.go
Labels: backport 0-21-0

#3983 fix webauthn url
  authorize/check_response.go
Labels: bug, backport 0-21-0

#3989 derivecert: fix ecdsa code to be deterministic
  internal/deterministicecdsa/ecdsa.go
  pkg/derivecert/ca.go
  pkg/derivecert/ca_test.go
  pkg/derivecert/notrand.go
  pkg/derivecert/pem.go
Labels: bug, backport 0-21-0

#4003 authenticate: fix authenticate_internal_service_url for all in one
  authorize/state.go
  config/config.go
  config/envoyconfig/routes.go
  internal/controlplane/server.go
  proxy/state.go
Labels: enhancement, backport 0-21-0

#4007 authenticate: don't require a session for sign_out
  authenticate/handlers.go
Labels: bug, backport 0-21-0

#4008 authenticate: fix callback handler for split mode
  config/envoyconfig/routes.go
Labels: backport 0-21-0

#4006 authenticate: fix identity provider id in encrypted query string
  authenticate/handlers.go
Labels: bug, backport 0-21-0

#3992 cryptutil: generate certificates from deriveca
  config/config.go
  config/config_test.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/tls_test.go
  config/options_test.go
  pkg/cryptutil/certificates.go
  pkg/cryptutil/tls_test.go
  pkg/derivecert/ca.go
Labels: enhancement

#4012 use deterministicecdsa to fix test
  internal/handlers/jwks_test.go
Labels: ci

#4015 authorize: allow access to /.pomerium/webauthn when policy denies access
  authorize/check_response.go
  authorize/check_response_test.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  internal/urlutil/known.go
  pkg/policy/criteria/pomerium_routes.go
Labels: bug, backport 0-21-0

#4028 urlutil: add version to query string
  authenticate/handlers.go
  authorize/check_response.go
  internal/handlers/sign_in.go
  internal/urlutil/known.go
  internal/urlutil/known_test.go
  internal/urlutil/query_params.go
  proxy/handlers.go
Labels: enhancement
