Repository pomerium/pomerium, pull requests merged in 2023-08, with the labels that each got.

#4434 github-actions: remove license check
  .github/workflows/test.yaml
Labels: ci

#4442 config: move mTLS settings to new struct
  authorize/authorize.go
  config/config_source.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/mtls.go
  config/mtls_test.go
  config/options.go
  config/options_test.go
  integration/clusters/kubernetes/compose.yml
  integration/clusters/multi/compose.yml
  integration/clusters/single/compose.yml
  integration/tpl/backends/pomerium.libsonnet
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: docs

#4391 logs: add ip address to access logs
  internal/controlplane/grpc_accesslog.go
  internal/controlplane/grpc_accesslog_test.go
  internal/log/access.go
Labels: blocked

#4443 config: add new mTLS enforcement setting
  authorize/authorize.go
  authorize/evaluator/config.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/policy_evaluator.go
  authorize/evaluator/policy_evaluator_test.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/mtls.go
  config/mtls_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: docs

#4447 authorize: client cert fingerprint in set_request_headers
  authorize/evaluator/evaluator.go
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
Labels: docs

#4448 ppl: add new client certificate criterion
  pkg/policy/criteria/client_certificate.go
  pkg/policy/criteria/client_certificate_test.go
  pkg/policy/criteria/criteria.go
  pkg/policy/criteria/criteria_test.go
  pkg/policy/criteria/reasons.go
Labels: docs

#4455 config: extra CA and CRL validation
  config/mtls.go
  config/mtls_test.go
  config/options_test.go
Labels: docs

#4472 add integration test for Pomerium JWT
  integration/policy_test.go
Labels: backport 0-22-0

#4479 storage: add indexes for postgres
  pkg/storage/postgres/migrate.go
Labels: performance

#4489 config: remove set_authorization_header option
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
  config/options_check.go
  config/policy.go
  pkg/grpc/config/config.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: docs
