Repository pomerium/pomerium, pull requests merged in 2024-07, with the labels that each got.

#5166 core/ui: add request id to upstream error page
  ui/src/components/UpstreamErrorPage.tsx
Labels: enhancement

#5168 core/ui: fix cycle in profile data
  internal/handlers/userinfo.go
  internal/handlers/userinfo_test.go
Labels: bug, backport 0-26-0

#5165 core/authorize: require new login when authenticate url changes
  config/identity.go
  config/session_test.go
  go.mod
  go.sum
  pkg/grpc/identity/identity.go
  pkg/grpc/identity/identity.pb.go
  pkg/grpc/identity/identity.proto
  pkg/grpc/identity/identity_test.go
  pkg/telemetry/requestid/requestid.go
Labels: bug, backport 0-26-0

#5182 session: do not invalidate based on ID token
  pkg/grpc/session/session.go
  pkg/grpc/session/session_test.go
Labels: bug

#5177 add mTLS UserPrincipalName SAN match
  authorize/evaluator/functions.go
  authorize/evaluator/functions_test.go
  authorize/evaluator/gen-test-certs.go
  authorize/evaluator/headers_evaluator_test.go
  config/envoyconfig/listeners_test.go
  config/mtls.go
  config/mtls_test.go
  go.mod
  go.sum
Labels: enhancement
