Repository pomerium/pomerium, pull requests merged in 2024-01, with the labels that each got.

#4897 core/envoy: upgrade to v1.25.10
  scripts/get-envoy.bash
Labels: security

#4899 core/autocert: fix flaky test
  internal/autocert/manager_test.go
Labels: ci

#4769 core/proxy: handle missing session for user info endpoint
  proxy/data.go
  ui/src/components/SessionDetails.tsx
Labels: enhancement

#4896 changelog for v0.25
  changelogs/changelog.md
  changelogs/v0.25.0.md
Labels: ignore-changelog

#4906 core/ci: check docker base images
  .github/workflows/test.yaml
  Dockerfile.debug
  scripts/check-docker-images
Labels: ci

#4907 core/config: remove cookie secure option
  authenticate/handlers.go
  authenticate/state.go
  config/options.go
  config/options_test.go
  config/session.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  proxy/proxy_test.go
  proxy/state.go
Labels: debt

#4898 core/zero: update oapi-codegen
  go.mod
  go.sum
  pkg/zero/cluster/client.gen.go
  pkg/zero/cluster/generate.go
  pkg/zero/cluster/models.gen.go
  pkg/zero/cluster/server.gen.go
Labels: debt

#4905 core/databroker: disable identity manager user refresh when hosted authenticate is used
  config/options.go
  databroker/cache.go
Labels: enhancement

#4895 core/opa: update for rego 1.0
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/opa/policy/headers.rego
  config/policy_ppl_test.go
  pkg/policy/criteria/criteria.go
  pkg/policy/criteria/criteria_test.go
  pkg/policy/criteria/invalid_client_certificate.go
  pkg/policy/generator/generator.go
  pkg/policy/generator/generator_test.go
  pkg/policy/rules/rules.go
Labels: debt

#4904 core/authorize: return non-html errors on denied
  authorize/check_response.go
  authorize/check_response_test.go
Labels: enhancement

#4914 core/envoy: clean up temporary directory on start
  pkg/envoy/extract.go
  pkg/envoy/extract_test.go
Labels: enhancement

#4913 policy: add client cert SAN match criteria
  pkg/policy/criteria/client_certificate.go
  pkg/policy/criteria/client_certificate_test.go
Labels: enhancement

#4916 core/ppl: add groups criterion
  pkg/policy/criteria/accept_test.go
  pkg/policy/criteria/authenticated_user_test.go
  pkg/policy/criteria/claims_test.go
  pkg/policy/criteria/cors_preflight_test.go
  pkg/policy/criteria/criteria_test.go
  pkg/policy/criteria/device_test.go
  pkg/policy/criteria/domain_test.go
  pkg/policy/criteria/email_test.go
  pkg/policy/criteria/groups.go
  pkg/policy/criteria/groups_test.go
  pkg/policy/criteria/http_method_test.go
  pkg/policy/criteria/http_path_test.go
  pkg/policy/criteria/invalid_client_certificate_test.go
  pkg/policy/criteria/reasons.go
  pkg/policy/criteria/reject_test.go
  pkg/policy/criteria/user_test.go
Labels: enhancement

#4918 config: remove deprecated client_ca option
  config/config_source.go
  config/options.go
  config/options_check.go
  config/options_test.go
Labels: breaking
