Repository pomerium/pomerium, pull requests merged in 2024-05, with the labels that each got.

#5093 health-checks: add route reachability
  internal/zero/controller/controller.go
  internal/zero/healthcheck/check_routes.go
  internal/zero/healthcheck/checks.go
  pkg/health/check.go
  pkg/zero/ping/ping.go
Labels: enhancement

#5104 health-check: building config from databroker source
  internal/databroker/config_source.go
  pkg/health/check.go
Labels: enhancement

#5108 core/envoy: exclude unauthorized access from local replies
  config/envoyconfig/http_connection_manager.go
  config/envoyconfig/testdata/main_http_connection_manager_filter.json
Labels: bug

#5113 adds upstream error page
  ui/src/App.tsx
  ui/src/components/UpstreamErrorPage.tsx
  ui/src/types/index.ts
Labels: frontend, javascript

#5106 Envoy resource monitoring & overload manager configuration
  config/runtime_flags.go
  go.mod
  go.sum
  internal/telemetry/metrics/const.go
  internal/telemetry/metrics/envoy.go
  pkg/envoy/envoy.go
  pkg/envoy/resource_monitor.go
  pkg/envoy/resource_monitor_linux.go
  pkg/envoy/resource_monitor_other.go
  pkg/envoy/resource_monitor_test.go
  pkg/metrics/constants.go
Labels: enhancement
