Repository pomerium/pomerium, pull requests merged in 2024-06, with the labels that each got.

#5125 update the pomerium/webauthn dependency
  go.mod
  go.sum
Labels: dependencies, go

#5127 core/ui: add policy id
  ui/src/components/ErrorPage.tsx
Labels: enhancement

#5128 core/ui: user info dashboard improvements
  ui/src/components/ClaimRow.tsx
  ui/src/components/ClaimValue.tsx
  ui/src/components/SessionDetails.tsx
Labels: enhancement

#5112 Add runtime flag to allow disabling config hot-reload (#5079)
  config/config_source.go
  config/config_source_test.go
  config/runtime_flags.go
Labels: enhancement

#5140 envoy: upgrade to v1.30.2
  scripts/get-envoy.bash
Labels: backport 0-26-0

#5133 core/envoy: add command to download envoy binaries
  .github/goreleaser.yaml
  Makefile
  pkg/envoy/get-envoy/main.go
  scripts/get-envoy.bash
Labels: enhancement

#5147 core/authorize: use uuid for jti, current time for iat and exp
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
  integration/policy_test.go
Labels: enhancement

#5137 core/userinfo: remove excess userinfo data
  internal/handlers/userinfo.go
  ui/src/types/index.ts
Labels: bug, backport 0-26-0

#5150 core/autocert: fix filter chain, handshake
  config/envoyconfig/listeners.go
  internal/autocert/manager.go
  internal/autocert/manager_test.go
Labels: bug, backport 0-26-0

#5158 core/ui: add user info link
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_test.go
  ui/src/components/Header.tsx
Labels: enhancement
