Repository pomerium/pomerium, pull requests merged in 2024-04, with the labels that each got.

#5044 authenticate: apply branding to sign out pages
  authenticate/handlers.go
  authenticate/handlers_test.go
  internal/handlers/signedout.go
  internal/handlers/signout.go
Labels: docs, enhancement

#5049 core/authorize: add support for rego print statements
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/log.go
  authorize/evaluator/log_test.go
  authorize/evaluator/policy_evaluator.go
Labels: enhancement

#5050 config: add runtime flags
  config/custom_test.go
  config/envoyconfig/bootstrap.go
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/protocols.go
  config/envoyconfig/protocols_test.go
  config/options.go
  config/options_test.go
  config/runtime_flags.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement

#5054 chore(deps): bump @trivago/prettier-plugin-sort-imports from 2.0.4 to 4.3.0
  ui/package.json
  ui/yarn.lock
Labels: dependencies, javascript

#5056 envoy: upgrade to v1.29.3
  scripts/get-envoy.bash
Labels: dependencies

#5057 envoy: upgrade to v1.28.2
  scripts/get-envoy.bash
Labels: dependencies

#5060 core/authenticate: redirect to /.pomerium/signed_out when no signout redirect url is defined
  authenticate/handlers.go
  authenticate/handlers_test.go
Labels: bug, backport 0-25-0

#5058 core/config: disable gRPC ingress when address is the empty string
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  internal/databroker/config_source.go
Labels: enhancement

#5065 core/zero: lower log level
  internal/zero/connect-mux/service.go
  internal/zero/grpcconn/client.go
  internal/zero/reconciler/sync.go
Labels: enhancement

#5066 core/envoy: only enable port reuse on linux
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/outbound.go
  config/envoyconfig/testdata/metrics_http_connection_manager.json
Labels: enhancement

#5072 update README: link to Contributing page
  README.md
Labels: ignore-changelog

#5067 core/envoy: format envoy local replies
  config/envoyconfig/http_connection_manager.go
  config/envoyconfig/listeners.go
  config/envoyconfig/testdata/main_http_connection_manager_filter.json
  ui/embed.go
Labels: enhancement

#5074 health-check: add storage health check
  pkg/health/check.go
  pkg/storage/inmemory/backend.go
  pkg/storage/postgres/backend.go
Labels: enhancement

#5053 config: add support for TCP proxy chaining
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/policy.go
  config/policy_test.go
Labels: docs, enhancement

#5088 chore(deps): update UI dependencies
  ui/yarn.lock
Labels: dependencies, javascript

#5084 core/identity: add enabler
  internal/enabler/enabler.go
  internal/enabler/enabler_test.go
  internal/identity/manager/config.go
  internal/identity/manager/manager.go
Labels: enhancement

#5090 core/kubernetes: fix impersonate group header
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/policy/headers.rego
Labels: bug, backport 0-25-0
