Repository pomerium/pomerium, pull requests merged in 2024-12, with the labels that each got.

#5387 envoy: enable extended connect
  config/envoyconfig/listeners_main.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/protocols.go
  config/envoyconfig/testdata/main_http_connection_manager_filter.json
Labels: backend

#5390 UDP support
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/policy.go
  config/policy_test.go
  internal/urlutil/url.go
Labels: enhancement

#5394 authorize: change handling of empty groups claim
  authorize/evaluator/headers_evaluator_evaluation.go
  authorize/evaluator/headers_evaluator_test.go
Labels: bug, backport 0-28-0

#5371 ci: run all benchmarks
  .github/workflows/benchmark.yaml
Labels: ci

#5398 metrics: make sure to flush buffered writer
  internal/telemetry/metrics/providers.go
Labels: bug

#5400 authorize: handle gRPC requests
  authorize/check_response.go
  authorize/check_response_grpc.go
  authorize/check_response_test.go
Labels: enhancement

#5401 config: fix lost branding settings when there are multiple configuration sources
  config/options.go
  config/options_test.go
  pkg/grpc/config/config.go
Labels: bug, backend, backport 0-28-0

#5250 config: generate fallback cert only as last resort
  config/envoyconfig/tls.go
  config/envoyconfig/tls_test.go
Labels: enhancement

#5405 fix redirect server proxy protocol
  go.mod
  go.sum
  internal/autocert/manager.go
Labels: bug, backend, backport 0-28-0
