Repository pomerium/pomerium, pull requests merged in 2024-09, with the labels that each got.

#5254 proxy: deprecate the /.pomerium/jwt endpoint
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  config/runtime_flags.go
  integration/clusters/kubernetes/compose.yml
  integration/clusters/multi-stateful/compose.yml
  integration/clusters/multi-stateless/compose.yml
  integration/clusters/single-stateful/compose.yml
  integration/clusters/single-stateless/compose.yml
  integration/tpl/backends/pomerium.libsonnet
  proxy/handlers.go
  proxy/handlers_test.go
  proxy/proxy.go
Labels: docs

#5263 core/envoy: allow TLS 1.3
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/testdata/metrics_http_connection_manager.json
  config/envoyconfig/tls.go
Labels: enhancement

#5264 core/ui: no-cache html, force back
  ui/embed.go
  ui/src/components/SignOutConfirmPage.tsx
Labels: bug, backport 0-26-0

#5275 core/zero: add organization id and cluster id to bootstrap config
  config/config.go
  internal/zero/bootstrap/source.go
  internal/zero/bootstrap/writers/k8s/secret_test.go
  pkg/zero/cluster/models.gen.go
  pkg/zero/cluster/openapi.yaml
Labels: enhancement

#5276 core/zero: add report-usage API
  pkg/zero/cluster/client.gen.go
  pkg/zero/cluster/models.gen.go
  pkg/zero/cluster/openapi.yaml
  pkg/zero/cluster/server.gen.go
Labels: enhancement

#5283 ci: address Dockerfile warnings
  .github/Dockerfile-cloudrun
  .github/Dockerfile-release
  .github/Dockerfile-release-debug
  .github/Dockerfile-release-debug-nonroot
  .github/Dockerfile-release-nonroot
  Dockerfile
  Dockerfile.debug
  examples/mutual-tls/Dockerfile
Labels: ci

#5281 core/zero: add usage reporter
  go.mod
  go.sum
  internal/testutil/grpc.go
  internal/zero/api/api.go
  internal/zero/controller/controller.go
  internal/zero/controller/usagereporter/usagereporter.go
  internal/zero/controller/usagereporter/usagereporter_test.go
  pkg/cryptutil/pseudonymize.go
  pkg/grpc/databroker/sync.go
  pkg/grpc/databroker/sync_test.go
  pkg/zero/cluster/client.gen.go
  pkg/zero/cluster/openapi.yaml
  pkg/zero/cluster/server.gen.go
Labels: enhancement

#5287 core/authorize: remove default header logging in debug
  config/options.go
  internal/log/authorize.go
Labels: enhancement

#5289 ppl: fix empty/no-op allow block added in some cases to converted PPL policies
  config/policy_ppl.go
  config/policy_ppl_test.go
Labels: backend, nit

#5295 core/proxy: fix is-enterprise check
  pkg/grpc/config/config.go
  proxy/data.go
  proxy/data_test.go
Labels: bug, backport 0-27-0

#5290 core/zero: add pseudonymization key
  config/config.go
  internal/zero/bootstrap/source.go
  internal/zero/bootstrap/writers/k8s/secret_test.go
  internal/zero/controller/controller.go
  internal/zero/controller/usagereporter/usagereporter.go
  internal/zero/controller/usagereporter/usagereporter_test.go
  pkg/cryptutil/pseudonymize.go
  pkg/zero/cluster/models.gen.go
  pkg/zero/cluster/openapi.yaml
Labels: enhancement

#5303 grpcutil: additional JWT validation
  pkg/grpcutil/options.go
  pkg/grpcutil/options_test.go
Labels: backport 0-27-0
