Repository pomerium/pomerium, pull requests merged in 2024-08, with the labels that each got.

#5198 ci: fix url typo in goreleaser
  .github/goreleaser.yaml
Labels: ci

#5194 config: allow overriding port numbers using environment variables
  config/config.go
Labels: enhancement

#5206 ci: switch to docker compose v2
  .github/workflows/benchmark.yaml
  .github/workflows/test.yaml
Labels: ci

#5208 databroker/leaser: set timeout on ReleaseLease
  pkg/grpc/databroker/leaser.go
Labels: bug

#5210 envoy: log mtls failures
  config/envoyconfig/listeners.go
  internal/controlplane/grpc_accesslog.go
  internal/log/access.go
Labels: docs, enhancement

#5205 envoy: support http2 prior knowledge for insecure upstream targets
  config/envoyconfig/protocols.go
  config/envoyconfig/protocols_int_test.go
  config/envoyconfig/protocols_test.go
Labels: docs, enhancement

#5218 core/proto: update protoc dependencies
  Makefile
  go.mod
  pkg/grpc/audit/audit.pb.go
  pkg/grpc/cli/api.pb.go
  pkg/grpc/cli/api_grpc.pb.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/crypt/crypt.pb.go
  pkg/grpc/databroker/databroker.go
  pkg/grpc/databroker/databroker.pb.go
  pkg/grpc/databroker/databroker_grpc.pb.go
  pkg/grpc/databroker/mock_databroker/databroker.pb.go
  pkg/grpc/device/device.pb.go
  pkg/grpc/events/last_error.pb.go
  pkg/grpc/identity/identity.pb.go
  pkg/grpc/protoc.bash
  pkg/grpc/registry/registry.pb.go
  pkg/grpc/registry/registry_grpc.pb.go
  pkg/grpc/session/session.pb.go
  pkg/grpc/user/user.pb.go
  pkg/storage/postgres/registry.go
  pkg/zero/connect/buf.gen.yaml
  pkg/zero/connect/buf.yaml
  pkg/zero/connect/connect.pb.go
  pkg/zero/connect/connect_grpc.pb.go
  pkg/zero/connect/generate.go
  scripts/protoc
  scripts/protoc-gen-go
  scripts/protoc-gen-go-grpc
Labels: debt

#5223 connect/client: ignore unknown message types
  internal/zero/connect-mux/messages.go
Labels: bug, backport 0-26-0

#5226 zero/api: switch to github.com/oapi-codegen/oapi-codegen
  pkg/zero/cluster/client.gen.go
  pkg/zero/cluster/generate.go
  pkg/zero/cluster/models.gen.go
  pkg/zero/cluster/server.gen.go
Labels: debt

#5184 Optimize policy iterators
  authorize/authorize.go
  authorize/evaluator/config.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/grpc.go
  authorize/internal/store/store.go
  config/envoyconfig/clusters.go
  config/envoyconfig/listeners.go
  config/envoyconfig/routes.go
  config/identity.go
  config/options.go
  config/policy.go
  internal/autocert/manager.go
  internal/databroker/config_source.go
  internal/httputil/reproxy/reproxy.go
  proxy/proxy.go
Labels: performance

#5230 ci: allow to override VERSION in Makefile via env
  Makefile
Labels: ci

#5219 zero/connect: add re-run health checks command
  internal/zero/connect-mux/config.go
  internal/zero/connect-mux/messages.go
  internal/zero/controller/controller.go
  internal/zero/controller/mux_log.go
  internal/zero/healthcheck/check_routes.go
  internal/zero/healthcheck/checks.go
  internal/zero/healthcheck/scheduler.go
  internal/zero/healthcheck/syncer.go
  pkg/zero/connect/connect.pb.go
  pkg/zero/connect/connect.proto
Labels: enhancement

#5243 core/grpc: add mock for registry service
  pkg/grpc/registry/mock_registry/registry.pb.go
  pkg/grpc/registry/registry.go
Labels: debt

#5235 core/logs: remove warnings
  authenticate/handlers.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/log.go
  config/envoyconfig/envoyconfig.go
  config/options.go
  config/policy.go
  internal/authenticateflow/stateful.go
  internal/authenticateflow/stateless.go
  internal/autocert/manager.go
  internal/databroker/config_source.go
  internal/events/manager.go
  internal/httputil/reproxy/reproxy.go
  internal/log/log_test.go
  internal/log/warnings.go
  internal/registry/reporter.go
  internal/retry/backoff.go
  internal/retry/retry.go
  internal/telemetry/metrics/envoy.go
  internal/telemetry/metrics/grpc.go
  internal/telemetry/metrics/http.go
  internal/telemetry/metrics/info.go
  internal/telemetry/metrics/storage.go
  internal/zero/telemetry/reporter/healthcheck.go
  internal/zero/telemetry/telemetry.go
  pkg/envoy/envoy_linux.go
  pkg/envoy/extract.go
  pkg/grpc/databroker/leaser.go
  pkg/identity/legacymanager/manager.go
  pkg/identity/manager/manager.go
  pkg/identity/manager/sync.go
  proxy/proxy.go
Labels: debt

#5242 core/config: add databroker_storage_connection_string_file
  config/config_source.go
  config/options.go
  config/options_test.go
  databroker/cache.go
  databroker/databroker.go
Labels: docs, enhancement
