Repository pomerium/pomerium, pull requests merged in 2024-11, with the labels that each got.

#5346 config: fix redirect response code
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/policy.go
  config/policy_test.go
Labels: bug

#5334 authorize: serialize errors in metav1.Status format when kubernetes user-agent is detected
  authorize/check_response.go
  authorize/check_response_test.go
Labels: backend, enhancement

#5359 Optimize Policy RouteID
  config/envoyconfig/route_configurations_test.go
  config/envoyconfig/routes_test.go
  config/policy.go
  config/policy_test.go
  internal/benchmarks/latency_bench_test.go
  internal/hashutil/hashutil.go
Labels: performance

#5363 authorize: additional header evaluator tests
  authorize/evaluator/headers_evaluator_test.go
  pkg/storage/querier.go
Labels: debt

#5362 authorize: rewrite header evaluator to use go instead of rego
  authorize/evaluator/evaluator.go
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_evaluation.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/evaluator/opa/opa.go
  authorize/evaluator/opa/policy/headers.rego
  authorize/internal/store/store.go
Labels: enhancement

#5350 envoyconfig: cleanup
  config/envoyconfig/envoyconfig.go
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_envoy_admin.go
  config/envoyconfig/listeners_grpc.go
  config/envoyconfig/listeners_main.go
  config/envoyconfig/listeners_main_test.go
  config/envoyconfig/listeners_metrics.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/outbound.go
  config/envoyconfig/route_configurations.go
  config/envoyconfig/route_configurations_test.go
  config/envoyconfig/tls.go
  config/envoyconfig/tls_test.go
Labels: debt

#5376 authorize: remove wait for ready
  authorize/authorize.go
  internal/controlplane/events.go
  internal/databroker/config_source.go
  pkg/grpc/client.go
  pkg/grpc/client_test.go
Labels: debt
