Repository pomerium/pomerium, pull requests merged in 2024-03, with the labels that each got.

#5009 chore(deps): bump google.golang.org/protobuf from 1.32.0 to 1.33.0
  go.mod
  go.sum
Labels: dependencies, go

#4969 core/zero: fix ticker usage
  internal/retry/retry.go
  internal/zero/connect-mux/service.go
Labels: bug, backport 0-25-0

#5029 changelog: v0.25.1
  changelogs/v0.25.1.md
Labels: ignore-changelog

#5018 envoy: set explicit hostname on cluster endpoints
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/testdata/clusters.json
Labels: breaking

#5031 zero: add service accounts support
  internal/zero/bootstrap/new.go
  internal/zero/bootstrap/source.go
  internal/zero/controller/controller.go
  internal/zero/controller/databroker.go
  internal/zero/leaser/leaser.go
  internal/zero/leaser/monitor.go
  internal/zero/leaser/runner.go
Labels: enhancement

#5035 zero: fix bootstrap config path
  internal/zero/bootstrap/bootstrap.go
  internal/zero/bootstrap/new.go
  internal/zero/bootstrap/new_test.go
  internal/zero/bootstrap/source_test.go
  internal/zero/cmd/command.go
  internal/zero/controller/config.go
  internal/zero/controller/controller.go
Labels: bug

#5042 envoy: set to v1.29.2
  scripts/get-envoy.bash
Labels: dependencies

#5040 core/logging: less verbose logs
  authorize/evaluator/evaluator.go
  cmd/pomerium/main.go
  internal/autocert/certmagic_logger.go
  internal/controlplane/server.go
  internal/controlplane/xds.go
  internal/controlplane/xdsmgr/xdsmgr.go
  internal/databroker/config_source.go
  internal/databroker/server.go
  internal/identity/manager/manager.go
  internal/zero/connect-mux/service.go
  internal/zero/controller/controller.go
  internal/zero/controller/mux_log.go
  internal/zero/grpcconn/client.go
  internal/zero/reconciler/sync.go
  pkg/cmd/pomerium/pomerium.go
  pkg/envoy/envoy.go
  pkg/grpc/client.go
  pkg/grpc/databroker/syncer.go
Labels: enhancement
