Repository pomerium/pomerium, pull requests merged in 2024-02, with the labels that each got.

#4953 core/zero: upgrade oapi-codegen
  pkg/zero/cluster/client.gen.go
  pkg/zero/cluster/generate.go
  pkg/zero/cluster/models.gen.go
  pkg/zero/cluster/server.gen.go
Labels: enhancement

#4958 ci: switch to regular runners
  .github/workflows/docker-version-branches.yaml
Labels: ci

#4957 core/ui: fix page title
  internal/handlers/device-enrolled.go
  internal/handlers/signedout.go
  internal/handlers/signout.go
  internal/handlers/userinfo.go
  internal/handlers/webauthn/webauthn.go
  internal/httputil/errors.go
  ui/dist/index.gohtml
  ui/embed.go
  ui/embed_ext.go
Labels: enhancement

#4961 connect: add gRPC keep-alive
  internal/zero/api/api.go
  internal/zero/grpcconn/client.go
  internal/zero/grpcconn/config.go
Labels: bug

#4960 core/config: implement direct response
  config/constants.go
  config/envoyconfig/route_configurations_test.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/policy.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement

#4964 authorize: log service account user ID
  authorize/log.go
  authorize/log_test.go
Labels: docs, enhancement

#4967 ci: upgrade to Go 1.22
  .github/workflows/benchmark.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .tool-versions
  Dockerfile
  Dockerfile.debug
  go.mod
Labels: dependencies
