Repository pomerium/pomerium, pull requests merged in 2025-07, with the labels that each got.

#5680 ssh: add basic end-to-end test
  go.mod
  pkg/ssh/ssh_int_test.go
Labels: ci

#5690 config: migrate deprecated cluster DNS settings
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/envoyconfig.go
  config/envoyconfig/testdata/clusters.json
  config/validate.go
Labels: debt

#5691 ci: update build job
  .github/workflows/test.yaml
Labels: ci

#5704 changelog for v0.30.0
  changelogs/v0.30.0.md
Labels: ignore-changelog

#5708 ci: remove 'brews' configuration from GoReleaser
  .github/goreleaser-mac.yaml
  .github/goreleaser.yaml
Labels: ci, backport 0-30-0

#5712 tracing: fix incorrect proto conversion logic for otel timeouts
  config/envoyconfig/listeners_test.go
  config/envoyconfig/testdata/main_http_connection_manager_filter.json
  config/envoyconfig/tracing.go
Labels: bug

#5719 mcp: fix authorization header removal
  authorize/check_response.go
  authorize/check_response_test.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/headers_evaluator.go
  authorize/evaluator/headers_evaluator_evaluation.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/grpc.go
Labels: bug

#5721 envoy: set concurrency to GOMAXPROCS
  config/runtime_flags.go
  pkg/envoy/envoy.go
Labels: backport 0-29-0, backport 0-30-0

#5728 databroker: update identity manager to use route credentials
  config/identity.go
  config/options.go
  config/session.go
  config/session_test.go
  databroker/cache.go
  internal/authenticateflow/stateful.go
  internal/authenticateflow/stateless.go
  pkg/grpc/session/session.go
  pkg/grpc/session/session.pb.go
  pkg/grpc/session/session.proto
  pkg/identity/manager/config.go
  pkg/identity/manager/manager.go
  pkg/ssh/auth.go
  proxy/data.go
Labels: bug, backport 0-29-0, backport 0-30-0

#5656 config: support multiple running services in addition to all-in-one mode
  config/envoyconfig/clusters.go
  config/helpers.go
  config/helpers_test.go
  config/options.go
  internal/telemetry/util.go
  internal/telemetry/util_test.go
Labels: enhancement

#5738 mcp: if upstream oauth does not return a refresh token, keep previous
  internal/mcp/token.go
Labels: bug

#5734 core: test improvements
  go.mod
  go.sum
  internal/autocert/manager.go
  internal/controlplane/server.go
  pkg/netutil/netutil.go
  pkg/netutil/netutil_test.go
  pkg/storage/inmemory/backend_test.go
  pkg/storage/postgres/backend_test.go
  pkg/storage/postgres/registry_test.go
  pkg/storage/storagetest/storagetest.go
Labels: debt

#5745 postgres: fix delete deadlock
  pkg/storage/postgres/option.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/postgres_test.go
Labels: bug, backport 0-30-0

#5749 metrics: don't add units and scope tags to prometheus metrics
  go.mod
  go.sum
  internal/telemetry/metrics/otel.go
Labels: backport 0-30-0

#5752 ci: restore coverage step in test workflow
  .github/workflows/test.yaml
Labels: ci

#5744 envoyconfig: make source_address independent of freebind
  config/envoyconfig/clusters.go
  config/envoyconfig/clusters_test.go
Labels: bug, backport 0-30-0

#5754 metrics: add stats prefix to the listeners
  config/envoyconfig/listeners.go
  config/envoyconfig/listeners_envoy_admin.go
  config/envoyconfig/listeners_grpc.go
  config/envoyconfig/listeners_main.go
  config/envoyconfig/listeners_metrics.go
  config/envoyconfig/outbound.go
  config/envoyconfig/testdata/metrics_http_connection_manager.json
Labels: backport 0-30-0
