Repository pomerium/pomerium, pull requests merged in 2025-09, with the labels that each got.

#5813 config: add databroker_cluster_leader_id
  config/options_databroker.go
  config/options_databroker_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement

#5818 feat: handle signals to better gracefully drain/terminate envoy
  cmd/pomerium/main.go
  internal/zero/cmd/run.go
  pkg/cmd/pomerium/pomerium.go
  pkg/contextutil/signals.go
  pkg/envoy/envoy.go
Labels: enhancement

#5815 databroker: add clustered follower server
  internal/databroker/server_clustered_follower.go
  internal/databroker/server_clustered_follower_test.go
  internal/databroker/server_forwarding.go
  internal/databroker/server_forwarding_test.go
  pkg/grpc/databroker/errors.go
  pkg/grpc/databroker/metadata.go
  pkg/grpcutil/errors.go
  pkg/grpcutil/errors_test.go
  pkg/grpcutil/forward.go
  pkg/grpcutil/forward_test.go
  pkg/grpcutil/serve_test.go
Labels: enhancement

#5816 databroker: add clustered leader server
  internal/databroker/server_clustered_leader.go
  internal/databroker/server_clustered_leader_test.go
Labels: enhancement

#5823 feat: health check CLI
  cmd/pomerium/main.go
  integration/clusters/multi-stateful/compose.yml
  integration/clusters/multi-stateless/compose.yml
  integration/clusters/single-stateful/compose.yml
  integration/clusters/single-stateless/compose.yml
  integration/tpl/backends/pomerium.libsonnet
  internal/controlplane/server.go
  pkg/health/cli.go
  pkg/health/cli_test.go
  pkg/health/http.go
  pkg/health/http_test.go
Labels: enhancement

#5841 fix: race condition with mcp server handler loading
  proxy/handlers.go
  proxy/proxy.go
Labels: bug

#5835 feat: report pomerium health to systemd
  config/options.go
  internal/controlplane/health_linux.go
  internal/controlplane/health_other.go
  internal/controlplane/server.go
  pkg/health/deduplicate_test.go
  pkg/health/manager.go
  pkg/health/manager_test.go
  pkg/health/systemd.go
  pkg/health/systemd_test.go
Labels: enhancement

#5852 remove the deterministicecdsa package
  config/config_test.go
  go.mod
  go.sum
  internal/deterministicecdsa/ecdsa.go
  internal/handlers/jwks_test.go
  internal/zero/bootstrap/new.go
  pkg/derivecert/ca.go
  pkg/derivecert/notrand.go
Labels: debt
