Repository pomerium/pomerium, pull requests merged in 2025-01, with the labels that each got.

#5417 authorize: add filter options for JWT groups
  authorize/authorize.go
  authorize/evaluator/config.go
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/headers_evaluator_evaluation.go
  authorize/evaluator/headers_evaluator_test.go
  authorize/internal/store/store.go
  config/custom.go
  config/options.go
  config/options_test.go
  config/policy.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement

#5419 config: add source ppl field
  config/policy.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement

#5427 importutil: refactor GenerateRouteNames to allow for protobuf or config routes
  config/policy.go
  pkg/zero/importutil/namegen.go
  pkg/zero/importutil/namegen_test.go
Labels: enhancement

#5424 config: add route name, description and logo
  config/policy.go
  config/policy_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement

#5429 config: fix JWT groups filter option
  config/options.go
  config/options_test.go
Labels: backport 0-28-0

#5439 authorize: cache warming
  authorize/authorize.go
  authorize/cache_warmer.go
  authorize/cache_warmer_test.go
  authorize/databroker_test.go
  authorize/grpc.go
  internal/testenv/selftests/tracing_test.go
  pkg/storage/cache.go
  pkg/storage/cache_test.go
  pkg/storage/querier.go
Labels: enhancement, backport 0-28-0

#5443 proxy: add routes HTML page
  authorize/evaluator/evaluator.go
  proxy/handlers.go
  proxy/handlers_portal.go
  ui/src/App.tsx
  ui/src/components/Header.tsx
  ui/src/components/RoutesPage.tsx
  ui/src/components/SidebarPage.tsx
  ui/src/components/UserInfoPage.tsx
  ui/src/components/UserSidebarContent.tsx
  ui/src/context/Subpage.tsx
  ui/src/types/index.ts
Labels: enhancement

#5449 ci: more flex version branch regex
  .github/workflows/docker-version-branches.yaml
Labels: backport 0-28-0

#5451 wasaga/ci version branch 28
  .github/workflows/docker-version-branches.yaml
Labels: ci

#5456 roll back to using ubuntu-22.04 images
  .github/workflows/backport.yaml
  .github/workflows/benchmark.yaml
  .github/workflows/codeql.yaml
  .github/workflows/docker-main.yaml
  .github/workflows/docker-version-branches.yaml
  .github/workflows/lint.yaml
  .github/workflows/needs-data.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: ci

#5448 proxy: add logo discovery
  proxy/handlers_portal.go
  proxy/portal/logo_provider.go
  proxy/portal/logo_provider_test.go
  proxy/proxy.go
Labels: enhancement

#5453 proxy: well known service icons
  proxy/portal/logo_provider.go
  proxy/portal/logo_provider_favicon.go
  proxy/portal/logo_provider_well_known.go
  proxy/portal/logos/activemq.svg
  proxy/portal/logos/aerospike.svg
  proxy/portal/logos/cassandra.svg
  proxy/portal/logos/clickhouse.svg
  proxy/portal/logos/cloudera.svg
  proxy/portal/logos/cockroachdb.svg
  proxy/portal/logos/consul.svg
  proxy/portal/logos/couchbase.svg
  proxy/portal/logos/couchdb.svg
  proxy/portal/logos/cratedb.svg
  proxy/portal/logos/elasticsearch.svg
  proxy/portal/logos/etcd.svg
  proxy/portal/logos/ftp.svg
  proxy/portal/logos/hadoop.svg
  proxy/portal/logos/hbase.svg
  proxy/portal/logos/ibmmq.svg
  proxy/portal/logos/influxdb.svg
  proxy/portal/logos/kafka.svg
  proxy/portal/logos/machbase.png
  proxy/portal/logos/mariadb.svg
  proxy/portal/logos/meilisearch.svg
  proxy/portal/logos/memcached.svg
  proxy/portal/logos/mongodb.svg
  proxy/portal/logos/mqtt.svg
  proxy/portal/logos/neo4j.svg
  proxy/portal/logos/nfs.svg
  proxy/portal/logos/opentext.svg
  proxy/portal/logos/oracle.svg
  proxy/portal/logos/postgres.svg
  proxy/portal/logos/rabbitmq.svg
  proxy/portal/logos/redis.svg
  proxy/portal/logos/riak.svg
  proxy/portal/logos/sphinx.png
  proxy/portal/logos/ssh.svg
  proxy/portal/logos/typesense.svg
  proxy/portal/logos/zookeeper.svg
  ui/src/components/RoutesPage.tsx
Labels: enhancement

#5447 Refactor trace config to match supported otel options
  cmd/pomerium/main.go
  config/constants.go
  config/envoyconfig/bootstrap.go
  config/envoyconfig/bootstrap_test.go
  config/envoyconfig/listeners_main.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/tracing.go
  config/options.go
  config/options_check.go
  config/options_test.go
  config/otelconfig/otelconfig.go
  config/trace_client.go
  internal/telemetry/trace/client.go
  internal/telemetry/trace/client_test.go
  internal/telemetry/trace/server.go
  internal/telemetry/trace/trace.go
  internal/testenv/environment.go
  internal/testenv/scenarios/trace_receiver.go
  internal/testenv/selftests/tracing_test.go
  pkg/cmd/pomerium/pomerium.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: breaking

#5457 replace xxhash with xxh3
  .golangci.yml
  config/config_source.go
  config/envoyconfig/clusters_test.go
  config/envoyconfig/filemgr/filemgr_test.go
  config/envoyconfig/filemgr/name.go
  config/envoyconfig/listeners_test.go
  config/envoyconfig/route_configurations_test.go
  config/envoyconfig/routes_test.go
  config/envoyconfig/testdata/metrics_http_connection_manager.json
  config/envoyconfig/tls_test.go
  config/policy.go
  go.mod
  internal/hashutil/hashutil.go
  internal/hashutil/hashutil_test.go
  internal/testutil/tracetest/buffer.go
  pkg/zero/importutil/namegen.go
  proxy/handlers_portal_test.go
  proxy/portal/portal_test.go
Labels: performance, debt
