Repository pomerium/pomerium, pull requests merged in 2025-06, with the labels that each got.

#5640 mcp: implement connect
  authorize/grpc.go
  config/policy.go
  internal/mcp/handler.go
  internal/mcp/handler_authorization.go
  internal/mcp/handler_connect.go
  internal/mcp/handler_list_routes.go
  internal/mcp/handler_oauth_callback.go
  internal/mcp/host_info.go
  internal/mcp/host_info_test.go
  internal/mcp/storage_test.go
  internal/mcp/token.go
  internal/oauth21/gen/token.pb.go
  internal/oauth21/proto/token.proto
Labels: enhancement

#5653 pgxpool: enable metrics
  pkg/storage/postgres/backend.go
Labels: backport 0-29-0

#5651 ppl: add in string matcher
  pkg/policy/criteria/matchers.go
  pkg/policy/criteria/matchers_test.go
Labels: enhancement

#5662 mcp: add mcp_tool to ppl
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/policy_evaluator.go
  authorize/grpc.go
  pkg/policy/criteria/criteria_test.go
  pkg/policy/criteria/mcp_tool.go
  pkg/policy/criteria/mcp_tool_test.go
  pkg/policy/criteria/reasons.go
Labels: enhancement

#5664 config: add ssh settings
  config/options.go
  config/options_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement

#5666 mcp: split mcp into server and client for better option grouping
  authorize/check_response_test.go
  authorize/evaluator/headers_evaluator_evaluation.go
  config/custom.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/options_test.go
  config/policy.go
  internal/mcp/host_info.go
  internal/mcp/host_info_test.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: breaking

#5668 mcp: add mcp method and tool logging to authorize
  authorize/evaluator/evaluator.go
  authorize/evaluator/evaluator_test.go
  authorize/evaluator/mcp.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/log.go
  authorize/log_test.go
  config/envoyconfig/clusters.go
  go.mod
  go.sum
  internal/log/authorize.go
  pkg/policy/criteria/criteria_test.go
  pkg/policy/criteria/mcp_tool.go
  pkg/policy/criteria/mcp_tool_test.go
Labels: enhancement

#5658 policy: add ssh PPL criteria
  authorize/evaluator/evaluator.go
  authorize/evaluator/policy_evaluator.go
  pkg/policy/criteria/criteria_test.go
  pkg/policy/criteria/reasons.go
  pkg/policy/criteria/ssh_publickey.go
  pkg/policy/criteria/ssh_publickey_test.go
  pkg/policy/criteria/ssh_username.go
  pkg/policy/criteria/ssh_username_test.go
Labels: enhancement

#5678 refactor testenv mock IdP to also work standalone
  internal/testenv/scenarios/mock_idp.go
  internal/testenv/upstreams/http.go
  internal/testutil/mockidp/mockidp.go
Labels: ci
