Repository pomerium/pomerium, pull requests merged in 2025-05, with the labels that each got.

#5594 mcp: redirect to upstream oauth2 for authentication
  internal/mcp/handler.go
  internal/mcp/handler_authorization.go
  internal/mcp/oauth_config.go
  internal/mcp/oauth_config_test.go
Labels: enhancement

#5598 add additional authorization check logs
  internal/log/middleware.go
Labels: backport 0-29-0

#5610 authenticate: add support for apple identity tokens
  pkg/identity/oauth/apple/apple.go
  pkg/identity/oauth/apple/apple_test.go
Labels: enhancement

#5614 identity: add IdP access and identity token verification for OIDC
  pkg/identity/oidc/azure/microsoft_test.go
  pkg/identity/oidc/oidc.go
  pkg/identity/oidc/oidc_test.go
Labels: enhancement

#5615 identity: add access token support for github
  pkg/identity/oauth/github/github.go
  pkg/identity/oauth/github/github_test.go
Labels: enhancement

#5616 authorize: move IdP token session creator initialization
  authorize/authorize_int_test.go
  authorize/grpc.go
  authorize/state.go
Labels: bug, backport 0-29-0

#5621 Fix comment grammar
  config/envoyconfig/routes.go
Labels: codex

#5620 Fix typo in Seal comment
  pkg/hpke/hpke.go
Labels: codex

#5618 config: use stable route ids for authorize matching and order xds responses
  authorize/evaluator/evaluator.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/log.go
  authorize/log_test.go
  config/envoyconfig/per_filter_config.go
  config/envoyconfig/route_configurations_test.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/policy.go
  config/policy_test.go
  internal/controlplane/xdsmgr/xdsmgr.go
  internal/controlplane/xdsmgr/xdsmgr_test.go
  internal/databroker/config_source.go
  internal/httputil/reproxy/reproxy.go
  internal/log/authorize.go
  proxy/portal/portal.go
Labels: enhancement

#5624 config: support weighted URLs in To field
  config/policy.go
  config/policy_test.go
Labels: backport 0-29-0
