Repository pomerium/pomerium, pull requests merged in 2025-02, with the labels that each got.

#5459 config: handle SIGHUP
  config/config_source.go
  config/config_source_test.go
Labels: enhancement

#5466 config: add support for http3 advertise port
  config/envoyconfig/quic.go
  config/envoyconfig/quic_test.go
  config/options.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  pkg/grpc/databroker/mock_databroker/databroker.pb.go
  pkg/grpc/databroker/mock_databroker/leaser.go
  pkg/grpc/registry/mock_registry/registry.pb.go
  pkg/health/provider_mock_test.go
Labels: enhancement, backport 0-28-exp

#5484 authorize: support authenticating with idp tokens
  .github/workflows/benchmark.yaml
  authenticate/handlers.go
  authenticate/handlers_verify.go
  authenticate/handlers_verify_test.go
  authenticate/identity.go
  authorize/authorize.go
  authorize/check_response.go
  authorize/check_response_test.go
  authorize/databroker.go
  authorize/grpc.go
  authorize/grpc_test.go
  authorize/log.go
  config/bearer_token_format.go
  config/constants.go
  config/identity.go
  config/options.go
  config/policy.go
  config/session.go
  config/session_test.go
  internal/httputil/headers.go
  internal/jwtutil/jwtutil.go
  pkg/authenticateapi/authenticateapi.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
  pkg/grpc/identity/identity.pb.go
  pkg/grpc/identity/identity.proto
  pkg/identity/errors.go
  pkg/identity/identity/errors.go
  pkg/identity/mock_provider.go
  pkg/identity/oauth/apple/apple.go
  pkg/identity/oauth/github/github.go
  pkg/identity/oauth/options.go
  pkg/identity/oidc/azure/microsoft.go
  pkg/identity/oidc/azure/microsoft_test.go
  pkg/identity/oidc/oidc.go
  pkg/identity/providers.go
Labels: enhancement, backport 0-28-exp

#5477 fileutil: add directory helpers, atomic file writing
  config/envoyconfig/filemgr/config.go
  config/envoyconfig/filemgr/filemgr.go
  config/options.go
  internal/fileutil/atomic.go
  internal/fileutil/atomic_test.go
  internal/fileutil/directories.go
  internal/zero/cmd/env.go
Labels: enhancement

#5488 support loading idp token sessions in the proxy service
  proxy/data.go
  proxy/data_test.go
  proxy/handlers.go
  proxy/handlers_portal.go
  proxy/proxy.go
  proxy/proxy_test.go
  proxy/state.go
Labels: backend, enhancement

#5493 upgrade x/oauth2 from v0.24.0 to v0.27.0
  go.mod
  go.sum
Labels: dependencies, go
