Repository pomerium/pomerium, pull requests merged in 2025-04, with the labels that each got.

#5560 remove debug log message for directories
  internal/fileutil/directories.go
Labels: bug, backport 0-29-0

#5564 multi-domain login redirects
  authorize/check_response.go
  authorize/state.go
  config/policy.go
  config/policy_test.go
  internal/authenticateflow/authenticateflow_int_test.go
  internal/authenticateflow/stateful.go
  internal/authenticateflow/stateful_test.go
  internal/authenticateflow/stateless.go
  internal/urlutil/proxy.go
  internal/urlutil/query_params.go
  proxy/handlers.go
  proxy/state.go
Labels: docs, enhancement

#5568 storage: support ip address indexing for the in-memory store
  go.mod
  go.sum
  pkg/storage/inmemory/backend.go
  pkg/storage/inmemory/record_collection.go
  pkg/storage/inmemory/stream.go
  pkg/storage/querier.go
  pkg/storage/record_collection.go
  pkg/storage/record_collection_test.go
Labels: enhancement

#5578 mcp: add to route config, 401 when unauthenticated
  authorize/check_response.go
  authorize/check_response_test.go
  config/custom.go
  config/policy.go
  pkg/grpc/config/config.pb.go
  pkg/grpc/config/config.proto
Labels: enhancement

#5570 storage: add sync querier
  authorize/authorize.go
  authorize/cache_warmer.go
  authorize/cache_warmer_test.go
  authorize/grpc.go
  authorize/state.go
  config/runtime_flags.go
  internal/testenv/selftests/tracing_test.go
  pkg/storage/postgres/tracing_test.go
  pkg/storage/querier.go
  pkg/storage/querier_caching.go
  pkg/storage/querier_client.go
  pkg/storage/querier_fallback.go
  pkg/storage/querier_fallback_test.go
  pkg/storage/querier_static.go
  pkg/storage/querier_sync.go
  pkg/storage/querier_sync_test.go
  pkg/storage/querier_typed.go
  pkg/storage/querier_typed_test.go
  pkg/telemetry/trace/client_test.go
Labels: enhancement

#5579 mcp: add oauth metadata endpoint
  config/envoyconfig/http_connection_manager.go
  config/envoyconfig/route_configurations.go
  config/envoyconfig/route_configurations_test.go
  config/envoyconfig/routes.go
  config/envoyconfig/routes_test.go
  config/options.go
  config/options_test.go
  internal/controlplane/http.go
  internal/mcp/handler.go
  internal/mcp/handler_metadata.go
Labels: enhancement

#5580 mcp: scaffolding of /.pomerium/mcp routes
  internal/mcp/handler.go
  internal/mcp/handler_authorization.go
  internal/mcp/handler_oauth_callback.go
  internal/mcp/handler_register_client.go
  internal/mcp/handler_token.go
  proxy/handlers.go
  proxy/proxy.go
Labels: enhancement

#5583 mcp: add rfc7591 types
  go.mod
  go.sum
  internal/rfc7591/buf.gen.yaml
  internal/rfc7591/buf.lock
  internal/rfc7591/buf.yaml
  internal/rfc7591/generate.go
  internal/rfc7591/types.pb.go
  internal/rfc7591/types.proto
  internal/rfc7591/types_test.go
Labels: enhancement

#5586 mcp: authorize request (pt2)
  internal/mcp/cipher.go
  internal/mcp/code.go
  internal/mcp/code_test.go
  internal/mcp/handler.go
  internal/mcp/handler_authorization.go
  internal/mcp/storage.go
  internal/mcp/storage_test.go
  internal/oauth21/gen/code.pb.go
  internal/oauth21/proto/code.proto
Labels: enhancement

#5590 storage: use a fake DNS server in TestLookup
  go.mod
  pkg/storage/postgres/backend_test.go
Labels: ci

#5587 mcp: token: handle authorization_code request (pt1)
  internal/mcp/handler_token.go
  internal/mcp/token.go
  internal/oauth21/buf.gen.yaml
  internal/oauth21/gen/authorization_request.pb.go
  internal/oauth21/gen/code.pb.go
  internal/oauth21/gen/token.pb.go
  internal/oauth21/pkce.go
  internal/oauth21/pkce_test.go
  internal/oauth21/proto/token.proto
  internal/oauth21/token.go
  internal/oauth21/validate_token_test.go
Labels: enhancement
